### ISSUE TITLE
Zvětšení infopointů

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#100]
Prosím o zvětšení ikonek infopointů, jsou na fotografiích špatně vidět a to nejen na neideálním podkladu (viz fota), díky. 

![infopointy-zvetseni](https://user-images.githubusercontent.com/15922183/56588538-db230e00-65e3-11e9-9129-c4f631ece37d.png)

![infopointy-zvetseni2](https://user-images.githubusercontent.com/15922183/56588756-479e0d00-65e4-11e9-86d4-a1c00af8af42.png)

**Comment by nnis** [comment]
ještě jsem dnes narazila na tuhle stránku: http://www.hairthusiasts.cz/#team a mají tam něco jako naše infopointy a zaujalo mě, jak je to pěkně vidět, uživatel hned ví, že na to má kliknout a co mi přijde fajn, tak hned nemizí. Všimla jsem si totiž, že když je u fotky animace, tak jakmile nejsem myší na íčku (které je navíc malé), tak infopoint zmizí. Ten bílý box je poměrně robustní, ale zvažte, jestli by nestačily prostě puntíky, případně větší puntík i ikonou "i", ale přijde mi to celkem elegantní. 

![infopointy- napad](https://user-images.githubusercontent.com/15922183/56819408-f2633500-6849-11e9-9a98-1dd67b9089ff.png)

**Comment by rudky4** [comment]
@nnis úprava implementovaná

**Comment by rudky4** [comment]
@nnis upraveno

**Comment by nnis** [comment]
Super!
