### ISSUE TITLE
Pamatování vyplněných údajů - "našeptávač" u infopointů

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#101]
Při tvorbě výstavy jsem narazila na to, že si editor pamatuje dříve vyplněné údaje. To je takové dvousečné - na jednu stranu je to super, když třeba požívám dvakrát stejnou informaci, na druhou stranu je pak matoucí to množství, které s dalšími infopointy narůstá. Samozřejmě se to objevuje nejen u infopointů, ale i u přidávání lidí v tiráži. A stejný obsah je napříč editorem - u jedné fotogalerie je to ještě i celkem logické a užitečné, ale když se mi text nabídne u úplně jiné stránky, je to podle mě spíš chyba. A pkud to testuji správně, stejné texty u infopointů se mi nabídnou i u jiné výstavy.

Zkuste se prosím zamyslet, jak s tím, nevím, jak tohle funguje, jestli jde nějak nastavit, že se to po čase vymaže, nebo jak dlouho si to editor bude pamatovat? 

viz: 

![naseptavac-infopointy](https://user-images.githubusercontent.com/15922183/56589307-40c3ca00-65e5-11e9-9aa2-7b7184257001.png)

**Comment by rudky4** [comment]
@nnis našeptávač vypnutý

**Comment by nnis** [comment]
Díky, super!
