### ISSUE TITLE
Odstranění Google+ se sdílení

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#102]
Vzhledem k rušení soc. sítě Google plus prosím o zrušení sdílení na závěrečné stránce výstavy, díky. 

![google-plus](https://user-images.githubusercontent.com/15922183/56655807-1da42380-6694-11e9-8753-c53131f0b28c.png)

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
Říkám si, zda by nešlo do sdílení přidat ještě "staré dobré" sdílení mailem, ten FB a Twitter působí tak trochu chudě, nemyslíte?

**Comment by rudky4** [comment]
@nnis šlo by to, v štýle:
Zadejte e-mail pro zaslaní odkazu na výstavu.
Zadejte e-mail: [__________]

Prosím o vytvorenie nového issue, pôjde o enhancement :)

**Comment by nnis** [comment]
Vytvořeno issue #104
