### ISSUE TITLE
Zobrazení názvu "Obrazovky s externím objektem"

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#103]
Ve výpisu obrazovek se "Obrazovka s externím objektem" zobrazuje s uříznutým nápisem u slova objekt. Můžete to prosím upravit tak, aby se to vešlo do rámečku. Viz: 
![obrazovka-externi-objekt](https://user-images.githubusercontent.com/15922183/57220356-5086d980-6ffb-11e9-9cc4-8a837107f38d.png)

Ještě mě napadá, že je u přípravy výstavy šikovné vědět, jaký typ obrazovky konkrétní obrazovka je, což když obrazovku pojmenuji, zmizí. Mohu se orientovat jen pomocí ikonek, ale nešlo by tam tu informaci mít třeba po najetí myši na rámeček nebo právě na tu ikonku? Jde mi totiž o to, že když tvořím obsah, chci střídat typy obrazovek a mít hned přehled, která obrazovka následuje po které je šikovné. Nebo třeba lépe pracovat s ikonkami - udělat je větší, aby byly výraznější? A nejsem si jistá, jestli každá obrazovka má svou ikonku a hry mají stejnou, což by nevadilo. Zkrátka mě napadlo, že by ty ikonky šly nějak lépe využít. Díky

**Comment by rudky4** [comment]
@nnis upraveno, přidán tooltip s typem obrazovky

**Comment by nnis** [comment]
Tooltipy jsou super, to určitě pomůže. Text se tam taky teď pěkně vejde, i když je to menší, ale to asi nevadí. 

Předpokládám, že teď jsou ty ikonky v jednom poli jako ten text, nešlo by to oddělit? Ten text malý nevadí, ale ty ikonky jsou teď fakt blechy a pak nejdou od sebe prakticky rozeznat. Nešlo by je zvětšit a přestěhovat vedle třítečkového menu? A zároveň by se ten tooltip s typem obrazovky zobrazil i po najetí na tu ikonku nejen na text.

**Comment by rudky4** [comment]
@nnis upraveno

**Comment by nnis** [comment]
Super, krása!
