### ISSUE TITLE
Menu - rodina produktů INDIHU

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#105]
Prosím o přidání menu vpravo vedle políčka přihlášení a po kliknutí se objeví menu 

INDIHU OCR (nástroj na konverzi obrázků na text)
O projektu INDIHU (odkaz na web) 

(Stejné menu bude i v liště INDOHU OCR), viz: 
![menu-rodina-indihu](https://user-images.githubusercontent.com/15922183/57686760-74b96a80-763a-11e9-87c8-2881dd4be434.jpg)
viz: https://github.com/LIBCAS/INDIHU-OCR/issues/2#

**Comment by rudky4** [comment]
@nnis implementované

**Comment by nnis** [comment]
Funguje to, bezva!
