### ISSUE TITLE
Ořezávání obrázků (úvod do kapitoly, stírací los)

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#106]
Je možné nějak ovlivnit ořezávání obrázku na pozadí v úvodu do kapitoly, respektive tuto možnost vypnout? V současnoti program ořezává obrázky automaticky, což není vždy vhodné. Nápříklad v tomto případě:

Náhled souboru:

![vys2](https://user-images.githubusercontent.com/42067492/57700765-e86b6f80-765a-11e9-92c3-b1adb0d541e3.jpg)

Náhled úvodu do kapitoly:

![vys1](https://user-images.githubusercontent.com/42067492/57700802-f620f500-765a-11e9-81f2-e594a168a6d2.jpg)

**Comment by Kolemkoukolem** [comment]
Problém s nekontrolovatelným ořezem je i u "stíracího losu". Oba obrázky jsou stejné velikosti (1927_TGM_Musov), ale při maximalizovaném okně na sebe "nepasují":
![mas1](https://user-images.githubusercontent.com/42067492/57851396-be43ba00-77e0-11e9-997a-55275d2160c4.png)

Před stíráním:
![mas2](https://user-images.githubusercontent.com/42067492/57851416-d1568a00-77e0-11e9-8455-b0572e5b9535.png)
Po setření poloviny smínku:
![mas3](https://user-images.githubusercontent.com/42067492/57851436-dddae280-77e0-11e9-90a0-54b52876f75c.png)

**Comment by rudky4** [comment]
@Kolemkoukolem do editoru úvodu kapitoly přidána možnost Bez animace na celou obrazovku (může dojít k ořezu při přizpůsobení obrazovce) a možnost Bez animace a bez ořezání obrázku (nedojde k ořezání, ale obrázek nemusí pokrývat celou obrazovku), u hry stírací los opraveno zobrazení obrázků.

**Comment by Kolemkoukolem** [comment]
Vyzkoušeno. Funguje. Děkuji.
