### ISSUE TITLE
Více / méně informací

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU-Exhibition#108]
Po rozkliknutí "více informací" v úvodu výstavy by to zas chtělo změnit tlačítko na "méně informací", aby to dávalo nějak smysl.

Viz printscreen.
![méněinfo](https://user-images.githubusercontent.com/42234445/57705639-8a438a00-7664-11e9-8aae-aa43c0504834.jpg)

**Comment by rudky4** [comment]
@matulovaklara upraveno
