### ISSUE TITLE
Insecure přihlášení

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#110]
Nově se mi objevil problém s nezabezpečeným přihlášením, prosím, mrkněte se na to. 
![https](https://user-images.githubusercontent.com/15922183/58867929-98148a00-86bb-11e9-9215-bd9eee941cfa.png)

**Comment by rudky4** [comment]
@nnis je to hláška Chrome, ktorá preventívne upozorňuje pokiaľ web nebeží na HTTPS, vyrieší sa to spustením na produkčnejšej doméne.

**Comment by nnis** [comment]
OK

**Comment by nnis** [comment]
Pořád jsme se nepřesunuli na produkční doménu, ale zabezpečné přihlášení by nemělo být těžké naimplementovat. Prosím o nasazení https již v této fázi, uživatelé pomalu přibývají a není to dobré.

**Comment by motyc** [comment]
Doména s certifikátem je již podle mě aktivní: https://exhibition.indihu.cz/

**Comment by nnis** [comment]
Jo super, je, takže vyřešeno
