### ISSUE TITLE
Špatný ořez přihlašovací stránky

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#111]
Všiml jsem si, že v různých prohlížečích a na různě velkých monitorech se přihlašovací stránka různě ořezává. Vlevo na menším monitoru Internet Explorer, vpravo na větším v Mozilla Firefox - viz:
![obrazek](https://user-images.githubusercontent.com/42067492/59021992-3ab04280-884d-11e9-9ffe-63f5b2c31423.png)
Zde zobrazení na malém monitoru v Mozilla Firefox:
![INDI](https://user-images.githubusercontent.com/42067492/59022439-0e48f600-884e-11e9-9894-c11d4417b1ee.png)

Myslím, že nikterak zásadně nejde o to, jak velká část obrázku na pozadí je zobrazena, ale ořez přihlašovací tabulku v první obrázku vlevo by se měl doladit.

**Comment by rudky4** [comment]
@Kolemkoukolem v rámci možnosti upravené

**Comment by Kolemkoukolem** [comment]
Zkoušel jsem zobrazení přihlašovací stránky na mobilu. Jak na Androidu (aplikace Seznam, Google Chrome), tak na IPhonu (Safari) vypadá přihlašovací stránka takto (omlouvám se za horší kvalitu fotek). Je možné na tom ještě zapracovat?
![67882924_212151793069695_2934117804594429952_n](https://user-images.githubusercontent.com/42067492/62131210-fedcab00-b2da-11e9-87d9-90ac434473b7.jpg)
![67416685_417758542172836_6164088220851109888_n](https://user-images.githubusercontent.com/42067492/62131227-069c4f80-b2db-11e9-80cb-900decbf093f.jpg)

**Comment by jirkacechak** [comment]
opraveno a odkazy z patičky přesunuty do menu v pravém horním rohu kvůli šetření místa a odstranění duplicity

**Comment by Kolemkoukolem** [comment]
Vyzkoušeno, funguje. Problém však přetrvává při prohlížení výstavy - viz #157
