### ISSUE TITLE
Internet Explorer - nefunkční náhled

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#112]
V prostředí prohlížeče Internet Explorer náhled výstavy nefunguje a progress bar je zcela odlišný od ostatních prohlížečů - viz:

![obrazek](https://user-images.githubusercontent.com/42067492/59023902-10608400-8851-11e9-9a44-3c3fbd43cdb9.png)
![obrazek](https://user-images.githubusercontent.com/42067492/59023921-18b8bf00-8851-11e9-863d-747b4a23c77f.png)

**Comment by rudky4** [comment]
@Kolemkoukolem podpora IE je všeobecne peklo, zvlášť u takto náročnejšej aplikácie.
Zvážil by som, či chceme IE podporovať dlhodobo pretože to navyše vytvára nemalú pracnosť pri vývoji.
Používanie IE dlhodobo klesá: http://gs.statcounter.com/browser-market-share/all/czech-republic (aktuálne sme na 4%, pred rokom to bolo 6%)

**Comment by Kolemkoukolem** [comment]
Také jsem si zjišťoval jak na tom prohlížeče v současnosti jsou a překvapilo mi, jak IE jde dolů. Nemyslím si, že je tedy bezpodmínečně nutné, aby výstavy fungovaly i na něm. Musíme ale myslet na to, že to musí být návštěvníkovi nějak sděleno. Bylo by náročné pro IE vytvořit nějakou hlášku, která by návštěvníkovi doporučila přehrání v jiném prohlížeči?
A propós, s jakými prohlížeči se počítá, že by v nich měla výstava fungovat? Chrome, Firefox, Safari (?), Android (?)?

**Comment by rudky4** [comment]
@Kolemkoukolem opraveno a přidána varovná hláška při otevření v IE

**Comment by Kolemkoukolem** [comment]
Děkuji za přidání chybové hlášky. Ještě bych měl otázku, jak je to s podporou prohlížečů Safari a Android?

**Comment by rudky4** [comment]
@Kolemkoukolem Safari na Mac by malo byť v pohode.
Android obecne, tam veľmi záleží na verzii prehliadača. Pokiaľ pôjde o novšie telefóny, budeme pre na optimalizovať (+ väčšina ma i tak Chrome).
