### ISSUE TITLE
Zvuková stopa obrazovky - náhodné chyby při přehrávání

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#113]
V současné době se u jedná naší dokončené výstavy zcela náhodně (ale velmi často) vyskytuje problém s přehráváním zvukové stopy obrazovky v prostředí prohlížeče Mozilla Firefox. Přímo po jejím dokončení jsme si ji několikrát různí lidé přehráli na různých počítačích a vše bylo v pořádku. Problém se poprví vyskytl při ukázce výstavy na konferenci na Slovensku. Nyní při každém přehrání v některé kapitole (i ve více či ve všech) se v průběhu přehrávání objeví chybová hláška a po chvíli je zvuková stopa ukončena (není to problém špatné doby časování). Někdy se v závěru zvuková stopa začne přehrávat samovolně znova. Bohužel netuším jak bych Vám mohl poskytnout nějaká data, která by Vám pomohla odhalit důvod chyby. V prostředí prohlížece Google Chrome se problém patrně nevyskytuje.

![obrazek](https://user-images.githubusercontent.com/42067492/59032089-b8804800-8865-11e9-825c-cdc15dd68f75.png)

Další problém je, pokud návštěvník během prohlížení výstavy si obrazku stopne, aby si pročetl další informace a poté znovu spustí, tak zvuková stopa kapitoly je po nějaké době ukončena před svým koncem.

Chyba se vyskytuje u výstavy PPA - 2019 - Kočovce - INDIHU:
http://inqooltest.libj.cas.cz/view/PPA2019KoovceINDIHU2019-05-22T081056459Z/2/1

**Comment by rudky4** [comment]
@Kolemkoukolem jestli se problémy objevily pouze u výstavy se soubory wav, tak by to možná mohlo souviset s tím, že nemusí být všude podporovány... pokud se to děje i s podporovanými soubory, tzn. mp3, tak jde o něco jiného, samotný problém tedy ještě když tak více prověřím...  zatím jsem doplnil chybějící omezení na podporované formáty při nahrávání souborů na tyto typy: `video/mp4, audio/mp3, image/jpeg, image/png, application/*, text/*` (jestli jsem něco zapomněl tak doplním)

**Comment by Kolemkoukolem** [comment]
Ano, bylo to u souborů .wav. Napadá Vás nějaký důvod, proč stopa během několika testů fungovala a pak najednou začala dělat problém?

**Comment by jirkacechak** [comment]
Nejspíš se daný problém týkal prohlížeče. Pokud nejsou problémy s mp3, tak navrhuji prozatím zavřít issue.

**Comment by Kolemkoukolem** [comment]
Problém se u nových výstav zatím naštěstí neprojevil. Uzavírám tedy.

**Comment by Kolemkoukolem** [comment]
Co čert nechtěl, včera se opět objevil problém. Jedná se podporovaný formát mp3. Zatím se vyskytl pouze v jednom případě.
![chyba1](https://user-images.githubusercontent.com/42067492/70150004-87b08c80-16a9-11ea-9d4f-99b5ffd7ebd7.jpg)

**Comment by Kolemkoukolem** [comment]
Opět problém s přehráváním zvukové stopy - viz obrázek. V čem by mohl být problém?
Výstava: https://exhibition.indihu.cz/view/epozitury-ARU/2/2
Prohlížeč: 
Google Chrome je aktuální
Verze 80.0.3987.149 (Oficiální sestavení) (64bitový)

![INDIHU-chyba](https://user-images.githubusercontent.com/42067492/77229947-154cb500-6b91-11ea-8ea0-310bd6479879.png)

**Comment by motyc** [comment]
Podle mne je problém v názvu souboru, protože je v něm použitá tečka i jinde než před příponou. Podobné problémy jsem viděl už v jiném případě u výstav, co jste dělali. Dbejte na již mnohokrát opakovaná pravidla pojmenovávání souborů a problémům se vyhnete.

Obecně by ale jistě bylo dobré, kdyby se i s tímto nástroj poprat dokázal.

**Comment by Kolemkoukolem** [comment]
Teď jsem si vzpomněl, že jsme něco takového řešili. Upravím a vyzkouším.

**Comment by jirkacechak** [comment]
V některých případech, i když má soubor příponu mp3, se může jednat např. o kontejner WAVE, který není některými prohlížeči podporován. Většina prohlížečů podporuje čisté mp3. Tečka v názvu souboru by na funkčnost souboru neměla mít vliv.

**Comment by Kolemkoukolem** [comment]
Po upravě jména se zatím problém už nevyskytuje.
