### ISSUE TITLE
Zoom in - umístnění popisu

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#114]
V současnosti je popis u obrzovky Zoom in vždy v pravém dolním rohu. Myslím si, že se může stát, že si návštěvník tohoto popisu nevšimne. Bylo by možné přidat funkci, která umožní vložení popisu i na jinou část obrazovky (např. levý horní roh)?

**Comment by motyc** [comment]
Také mi přijde, že se tam infopoint trošku ztrácí. Osobně myslím, že by možná stačilo, aby byl text v nějakém opticky více vyděleném boxu, který by na sebe více "upozornil".

**Comment by rudky4** [comment]
@Kolemkoukolem @motyc tooltip zvýrazněn a přidána možnost volby pozice
