### ISSUE TITLE
Tlačítko "Výstavy" v horním modrém pruhu u výpisu výstav

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#116]
![obrazek](https://user-images.githubusercontent.com/42305589/59561312-4bb43d00-901f-11e9-913d-4fd7ea61e785.png)
Toto tlačítko je nastaveno jako klikací, ale nikam nevede - možná by šlo využít pro založení nové výstavy.

**Comment by nnis** [comment]
Tlačítko v menu je odstraněné, možné zavřít issue.

**Comment by rudky4** [comment]
tlačítko slouží (stejně jako titulek INDIHU Exhibition) pro přesměrování uživatele na seznam výstav např. pokud je ve správě profilu, případně administrátor v nastavení apod. - odteď se navigační tlačítka schovají, pokud je uživatel na dané stránce, aby to nebylo matoucí, že na té konkrétní stránce nic nedělají (protože na ni odkazují)
