### ISSUE TITLE
Vyhledávání v názvech výstav - nechat case sensitive?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#119]
V názvech výstav lze zatím vyhledávat jen na základě absoltní shody (včetně velkých a malých písmen) - ponechat takto?

**Comment by nnis** [comment]
Jsem pro změnu aby vyhledávání bylo citlivější nebo jak to říct.

**Comment by malinekv** [comment]
Tj. aby dotaz "pokus" našel opravdu jen "pokus" (tak je to nyní), a naopak nenašel "POKUS", "Pokus" či "POkus"? Já bych intuitivně volil druhou variantu, ale je to na zvážení...

**Comment by nnis** [comment]
Souhlas

**Comment by rudky4** [comment]
Vyhľadávanie upravené, aktuálne už nie je case-sensitive.
