### ISSUE TITLE
Úvod výstavy - tiráž - nefunkční odkazy

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#120]
![obrazek](https://user-images.githubusercontent.com/42305589/59564435-f3913100-9046-11e9-96e4-053b2a42fc33.png)
Názvy sloupců v záhlaví (Role, Osoba nebo text) i vyplněné hodnoty se jeví jako klikací, prokliknout se z nich ale nikam nedá...

**Comment by nnis** [comment]
Nějak nevím, co tím myslíte @malinekv , nemohl byste to prosím vysvětlit?

**Comment by rudky4** [comment]
upraveno
