### ISSUE TITLE
Ikonka koš - maže bez dalšího varování

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#121]
![obrazek](https://user-images.githubusercontent.com/42305589/59564603-f55bf400-9048-11e9-9b55-3c35f7ed7116.png)
Kliknu-li na koš, řádek se bez dalšího varování smaže (zdá se mi, že takto nastaveno všude); možná bych vyžadoval ještě jedno potvrzení, jinak hrozí, že se někdo uklikne.

**Comment by nnis** [comment]
Te už hlášky přibyly, nicméně jsem teď namátkou narazila na 3 druhy potvrzení o smazání včetně různých stylů potvrzení. (Možná existuje někde nějaká další verze). Navrhuji následujcí sjednocení.  Používala bych všude u mazání tu popelnici, ať je to jednotné. Proto prosím o přidání popelnice i do menu ke smazaní obrazovky). 

Zároveň jsem si všimla, že ne všude mají ikony stejnou barvu - ikony včetně poplenice u souborů jsou černé a u tiráže jsou šedé, takže to působí tak, že jsou jiné. Byla bych pro černé, je to výraznější a zároveň íčka jsou šedivá a tím méně výrazná, což mi přijde dobré, neboť v íčkách je informace doplňková. 

![smazani1](https://user-images.githubusercontent.com/15922183/60098379-b5d28d80-9755-11e9-9fd8-48da9639aef2.png)
![smazani2](https://user-images.githubusercontent.com/15922183/60098380-b66b2400-9755-11e9-967a-9387eac2868a.png)
![smazani3](https://user-images.githubusercontent.com/15922183/60098741-7d7f7f00-9756-11e9-899e-206946b2b35b.png)

Přišlo by mi fajn využít ikonku koše a pak se zeptat na to, zda položku smazat. Položka mi přijde jako dobré pojmenování jak u položky v tiráži, tak pro soubor v adresáři, ale kdyby nebyl problém, tak u položky v tiráži by se hláška ptala na položku, u souboru na smazání souboru. prosím dodejte vykřičník s upozorněním, že smazání je trvalé. 

Návrh na výslednou podobu potvrzení smazaní: 
![smazani-navrh](https://user-images.githubusercontent.com/15922183/60099317-aeac7f00-9757-11e9-9db1-85274e324b61.jpg)
Místo Warning: na google drivu bych tam dala červený vykřičník a u obrazovky i vysvětlení. Textaci vysvětlení jsem mírně zkrátila: Opravdu chcete obrazovku smazat? ! Akce je nevratná. Smažete obrazovku, ale dokumenty obrázky v adresáři zůstanou. 

Inspirovala jsem se zde. 
![smazani-google-drive](https://user-images.githubusercontent.com/15922183/60099325-b2d89c80-9757-11e9-851d-c04086e3b06c.png)

**Comment by rudky4** [comment]
@nnis upraveno

**Comment by nnis** [comment]
Funguje to a navíc se mi to líbí :)
