### ISSUE TITLE
Hláška o uložení stránky

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#122]
Zobrazovaní hlášky o uložení stránky se mi zdá příliš dlouhé na to, abych intuitivně nezačal reagovat myší; než jí ale stihnu najet, hláška zmizí. Možná bych délku zobrazování zkrátil, nebo naopak natvrdo vyčkal na odkliknutí.

Zároveň v okně vyskakuje 2x v zásadě stejný text:
![obrazek](https://user-images.githubusercontent.com/42305589/59564747-cfcfea00-904a-11e9-96e2-1cfe3f55ef9f.png)

**Comment by nnis** [comment]
Opraveno, super postřeh, teď je to mnohem lepší, je to tam jednou a navíc větším písmem.

**Comment by rudky4** [comment]
upraveno
