### ISSUE TITLE
Volba nové obrazovky - chybky v názvech položek

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#123]
![obrazek](https://user-images.githubusercontent.com/42305589/59564780-38b76200-904b-11e9-885f-a1fad7343197.png)
 V roletce s volbou miniher jsou dvě drobné chybky v délkách samohlásek. Mělo by být:
a) "NAjdi v obrázku", nikoli "NÁjdi v obrázku"
b) "Posuň na správnÉ místo", nikoli "Posuň na správnE místo"

**Comment by nnis** [comment]
Super postřeh, díky za něj a když už jsme u toho, vhodnější by mi přišla předložka **na** u minihry "Najdi **na** obrázku". Prosím o opravu, délka samohlásek je již v pořádku.

**Comment by rudky4** [comment]
@nnis upraveno

**Comment by nnis** [comment]
Teď je to správně
