### ISSUE TITLE
Upload souborů jiného formátu

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#124]
Systém mě nechá (zřejmě odkudkoli) uložit jakýkoli soubor, ale pokud daný soubor typem neodpovídá očekávanému, nic se neděje - tj. např. u zvukové stopy v minihře mohu uložit obrázek, ten se i fyzicky uloží, ale uživatel o tom nedostane přímou zprávu.

**Comment by nnis** [comment]
právě se mi podařilo nahrát soubor s příponou .exe, což by nemělo jít. Máme někde seznam podporovaných formátů? Pokud většinu podporujeme, co to vymezit negativně, tedy vyjmenovat ty, které nepodporujeme nebo alespoň nějakým opisem (třeba jako pracovní soubory z grafických programů nebo jako soubory k instalaci (exe). 

Jak ověřím, zda hláška o nepodporovaném formátu vypadá? 

prosím o úpravu zarovnání hlášky o překročení limitu - teď vyskočí položka nahrát soubor nahoru, měla by zůstat na stejném místě a možná nechte pod tím prostor pro tu hlášku. Viz: 

![maximalni-velikost](https://user-images.githubusercontent.com/15922183/60097560-ef09fe00-9753-11e9-87ba-f1d479f5d130.png)
