### ISSUE TITLE
Práce se soubory - možnost stáhnout si soubory k dané výstavě

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#125]
Zatím jde do systému soubory jen nahrát; šlo by nastavit i možnost jejich stažení, by je uživatel nemusel zpětně dohledávat na svých úložištích? Využil bych např. při úpravě obrázků pro minihiry...

**Comment by nnis** [comment]
Mě už stahování funguje pěkně.
