### ISSUE TITLE
Hra Dokresli - obrázek uskakuje

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#126]
Ve hře dokresli se úvodní obrázek centruje na střed - při zobrazení původního, který je vždy širší,
pak dokreslený obrázek uskakuje doleva. Bylo by asi lépe dokreslovaný obrázek rovnat nikoli na střed, ale k levému/pravému okraji obrázku původního, neboť se pak nepřekrývají - srov. printscreeny
![obrazek](https://user-images.githubusercontent.com/42305589/59566073-44ab2000-905b-11e9-8ef4-2aa66602050d.png)
![obrazek](https://user-images.githubusercontent.com/42305589/59566077-4bd22e00-905b-11e9-97b4-8b6c7d3bbb0b.png)

**Comment by rudky4** [comment]
Pôvodná motivácia pri návrhu tejto hry bola, že tvorca hry pripraví 2 identické obrázky (čo sa týka pomeru strán). Zatmaviť požadovanú časť je potrebné v rámci prípravy mimo aplikáciu.

**Comment by malinekv** [comment]
OK, díky. Asi by to stálo za vysvětlení v nápovědě.
Jen mě pak napadlo, co se stane, kdyby uživatel ořízl obrázek zleva, popř. z obou stran?
Možná by pak bylo jednodušší ořezávat přímo v aplikaci, ale to je k uvážení.

**Comment by jirkacechak** [comment]
Obrázek by se právě ořezávat neměl, jak již bylo zmíněno, ale měly by oba obrázky být rozměrově identické (stejná výška i šířka) a uživatel si zatmaví část obrázku, kterou požaduje dokreslit. Není tedy vázán na ořez zleva, zprava apod. Může zatmavit například prostředek obrázku, případně více částí.
Pokud by se toto mělo řešit ořezem obrázku, muselo by se navrhnout jiné řešení, kde by například uživatel musel zvolit umístění ořezaného obrázku, aby nebyl vázán na to, že bude obrázek vždy umístěn například k levému okraji, ale to již hodně odbočuje od původní motivace.
