### ISSUE TITLE
Výpis souborů - umožnit pohyb i šipkami+využití kláves Insert, Delete atp.?

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#127]
V adresáři s názvy uložených souborů se lze pohybovat jen myší - možná bych uvážil doplnění ovládání pomocí šipek

**Comment by nnis** [comment]
Pohyb šipkami by byl super. Zároveň by bylo asi fajn, kdyby menu k souborům bylo vidět rovnou a ne až po kliknutí, protože takhle jsem zjistila, že je tam nějaké menu vlastně náhodou. 

Položka Přesunout funguje jen v případě, když mám vytvořenou složku, takže na první pohled není zřejmé, co tato položka dělá. Navrhuji přejmenovat položku na Přesunout do složky. 

Počet souborů ve složce - bylo by možná fajn u složky mít v závorce informaci, kolik obsahuje souborů.

**Comment by nnis** [comment]
K menu u souboru - problematické je zobrazení menu u posledního souboru na konci seznamu. Menu se zprvu nezobrazí a zobrazí se až po scrollování, viz: 

![menu-posledni-soubor](https://user-images.githubusercontent.com/15922183/60097686-2e384f00-9754-11e9-9c28-ddde1fee712a.png)

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
Perfektní, funguje to pěkně!
