### ISSUE TITLE
Možnost stranově otočit obrázek

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#129]
Systém, zdá se, neumí rozpoznat orientaci obrázku, tj. obrázky focené na výšku načítá na šířku - chybí přitom možnost toto upravit.

**Comment by nnis** [comment]
Během prezentace virtuálních výstav více kolegů projevilo zájem o to, aby alespoň bazální úpravy obrázků mohly být prováděny přímo v editoru. Mezi naše návrhy patří: 
- otočení (změna orientace o 90 stupňů
- crop (oříznutí) 
- případně resize/scale image s funkcí zachování poměru stran

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Super, díky moc. Na první pohled mi to funguje, poprosila jsem ještě kolegy, ať se na to podívají. 
Mám jen prosbu, abyste upravili šířku sloupce u změny poměru stran, není to pořádně vidět a ideálně tak, aby nebylo nutné scrollování, zas tolik možností tam není. 

![pomer-stran](https://user-images.githubusercontent.com/15922183/61589543-a0f9e600-abab-11e9-9f30-687b9a63f690.png)

a ještě o úpravu délky řádku u přejmenování souboru - prosím o zkrácení. Nešlo by také vlevo na půlce přejmenování a vpravo potom uložení? že by to bylo na jednom řádku? 

![nazev-souboru-editor-obrazku](https://user-images.githubusercontent.com/15922183/61589546-b4a54c80-abab-11e9-9395-a4447f9a72b5.png)

**Comment by jirkacechak** [comment]
upraveno

**Comment by nnis** [comment]
Perfektní
