### ISSUE TITLE
Nahrávání více souborů (chybové hlášky)

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#13]
Bylo by vhodné mít možnost nahrávat více souborů najednou.

**Comment by nnis** [comment]
Mě jdou vložit dva dokumenty, ale jen .pdf, nechceme mít možnost vložit i doc, docx či txt? Zkoušela jsem to v úvodu výstavy i ve stránce s obrázkem.

**Comment by rudky4** [comment]
@motyc @nnis nahrávání více souborů je hotové, prosím o test.

**Comment by nnis** [comment]
Nahrávání více souborů funguje, ale ještě to nějak není ono. Nahrávala jsem to ze záložky Soubory v záložkách k celé výstavě. Jenže jsem pak ty soubory nemohla přidat, když jsem přidávala dokumenty k výstavě v editaci Výstavy pod Úvodem výstavy - Dokumenty. 
To znamená, že je sice nahraji, ale pak je nevidím.  Nahraji tam více souborů různých formátů (.pdf, .doc, .docx., .md), ale když je chci přidat k výstavě, tak vidím v seznamu jen soubory .pdf.
Přikládám raději obrázky, nějak špatně se mi to vysvětluje. 
![soubory](https://user-images.githubusercontent.com/15922183/54609027-58da8380-4a52-11e9-8208-158dfe2d67f9.png)
![soubory2](https://user-images.githubusercontent.com/15922183/54609076-7871ac00-4a52-11e9-8e37-a40cac1cd8aa.png)

**Comment by rudky4** [comment]
@nnis upraveno, povoleny všechny soubory při přidávání dokumentů výstavy

**Comment by Kolemkoukolem** [comment]
Prosím o informaci do nápovědy, jaká je maximální velikost pro hromadné nahrávání souborů.

**Comment by rudky4** [comment]
@nnis nastavíme to na 20MB/file a 100MB hromadne v ramci jedného hromadného uploadu?

**Comment by nnis** [comment]
Zkusme to tak a uvidíme, jestli to bude vyhovovat. Můžete tuto informaci rovnou dát do íčka prosím? Asi tedy přidat nové íčko vedle políčka "Nahrát soubor"

**Comment by Kolemkoukolem** [comment]
Co jsem teď zkoušel, tak nahrávání mi selhalo u všech souborů nad 10 MB.

**Comment by rudky4** [comment]
@Kolemkoukolem dnešný test:
Skúšal som nahrať 20MB súbor, išlo v pohode, ešte skúsim 5 takých súborov
Tie súbory sa aj tak nahrávajú po jednom (každý v samostatnom requeste) takže ten limit čo som nastavoval 125MB na celý request sa zrejme nikdy neaplikuje.
![image](https://user-images.githubusercontent.com/7311447/56293714-ebda0c80-6129-11e9-82cb-009f25475fc7.png)
![image](https://user-images.githubusercontent.com/7311447/56293725-f3011a80-6129-11e9-861b-62687eec4022.png)

**Comment by Kolemkoukolem** [comment]
@rudky4 Dnes jsem také opět zkoušel. Hromadné nahrání i nahrání jednotlivého souboru nad 20 MB šlo. Před tím byla chyba na mé straně. Nahrával jsem soubory *.TIF, které nejsou podporovány. Omlouvám se za falešný poplach.

**Comment by Kolemkoukolem** [comment]
V kontextu výše zmíněného bych se chtěl zeptat, zda by bylo možné doplnit současnou chybovou hlášku "Nahrávání souboru x selhalo." o bližší specifikaci, proč se tak stalo, např. z důvodu velikosti souboru či nepodporovaného formátu. Uživatelům by to jistě v začátcích pomohlo s orientací v programu.

**Comment by rudky4** [comment]
@Kolemkoukolem skusime implementovat :)

**Comment by rudky4** [comment]
hlášky pridané

**Comment by Kolemkoukolem** [comment]
Chybová hláška oznamující příliš velký formát funguje.

Zkušebně jsem se pokusil nahrát i nepodporovaný formát *.TIF, abych vyzkoušel funkčnost chybových hlášek. Kupodivu se mi podařilo soubor nahrát do "zásobníku" bez žádné chybové hlášky - viz:
![Obrázek3](https://user-images.githubusercontent.com/42067492/57389840-51666980-71bb-11e9-9e0b-e1ecd7316c85.png)

Když takto nahraný soubor vkládám do výstavy opět žádná chybová hláška nevyskakuje a pouze se stále točí "nahrávací kolečko"
![Obrázek2](https://user-images.githubusercontent.com/42067492/57389565-bf5e6100-71ba-11e9-8ee2-31c8fe4c55da.png)
