### ISSUE TITLE
Minihra Hádej velikost

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#131]
![obrazek](https://user-images.githubusercontent.com/42305589/59567894-d7f04f80-9073-11e9-81a8-c7eae2e98f61.png)
a) pokud se nastaví stejná velikost obrázků, nejsou symetricky vedle sebe (srov. printscreen)
b) nastavení velikosti druhého obrázku není úplně jednoduché (není úplně jasné, jak přesně vyvolat zvětšení/zmenšení obrázku - pojezdem po šipce/taháním za obrázek?; aplikace reaguje i při pohybu
ve spodní liště k tlačítku "Hotovo"
c) druhý obrázek nelze nastavit jako větší než první, tj. vždy by se měla nastavovat velikost menšího objektu z dané dvojice

**Comment by jirkacechak** [comment]
a) opraveno
b) opraveno - ke zvětšení dochází při stlačení levého tlačítka myši a pohybu doleva nahoru a ke zmenšení při pohybu doprava dolů dle naznačené šipky
c) zvětšovaný/zmenšovaný obrázek je vždy ten, který je zvolen jako "Obrázek porovnávaného předmětu" v editoru

**Comment by nnis** [comment]
Neintuitivní ovládání, je třeba vymyslet znovu způsob práce s hrou. je třeba řešit v týmu.

**Comment by nnis** [comment]
Řeší nový design a přidání sady referenčních předmětů pro využití tvůrcem
