### ISSUE TITLE
Tlačítko Kapitoly v průběhu výstavy - slepý odkaz

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#133]
Tlačítko "Kapitoly" při průběhu výstavy vpravo nahoře zatím nevyvolává žádnou akci.
Nebo funguje jen tehdy, pokud výstava obsahuje nějakou kapitolu (v cvičné výstavě žádnou nemám)?

**Comment by nnis** [comment]
U výstavy, která má kapitoly to částečně funguje - měla jsem ve výstavě dvě kapitoly, nepojmenované a zobrazovalo to jen jednu kapitolu s názvem Úvod do kapitoly. Když jsem kapitoly přejmenovala na kapitola 1 a kapitola 2, už jsem ve výpisu měla obě se správným názvem. 

Zkoušela jsem výstavu bez kapitol a ve frontendu v záhlaví položka kapitoly není, což je super, pak to není slepý odkaz. 

Mělo by to fungovat tak, že když mám kapitoly, mám to i ve frontendu, když nemám, nic tam vpravo nahoře není.

**Comment by malinekv** [comment]
Já to viděl v té mé pokusné výstavě, kde byly jen minihry, teď už to tam, zdá se, nevidím.

**Comment by rudky4** [comment]
@malinekv @nnis je teda funkcionalita správna? pokiaľ áno, prosím o uzavretie issue.

**Comment by nnis** [comment]
Mě to s tím jedním zakolísáním fungovalo, jak jsem psala výše, takže jestli jste to zkontrolovali, je možné to uzavřít (já tu mám zas jen možnost komentovat a ne uzavírat issues).

**Comment by rudky4** [comment]
tlačítko je odteď skryto, pokud výstava neobsahuje žádné kapitoly+
