### ISSUE TITLE
Dvě scrollovací lišty na jedné obrazovce

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#135]
Pokud jsou na obrazovce dvě scrollovací lišty (např. výpis souborů či strom se strukturou výstavy, pokud se zvolí výběr nové obrazovky - srov. printscreen), je u delších výpisů potřeba hýbat s oběma
- nešlo by alespoň jednu ukotvit, aby nebylo nutné hýbat s oběma? Obzvlášť u výpisu souborů to není úplně pohodlné...
![obrazek](https://user-images.githubusercontent.com/42305589/59568787-0ffd8f80-9080-11e9-89d2-8b78ec035b31.png)
![obrazek](https://user-images.githubusercontent.com/42305589/59568788-29064080-9080-11e9-9dc3-eefbb1f8fbe2.png)

**Comment by nnis** [comment]
Scrolovátko u menu u obrazovky bylo už odstraněno, což je super. 

**U souborů**
U metadat je lišta pro srollování vlastně zbytečná, nic to tam nedělá, tak jí prosím zrušte. Zkoušela jsem to u různých souborů a nikde nebylo víc řádků než ty 3 stávající. 
U toho seznamu souborů se tomu zřejmě nevyhneme a záleží to na velikosti obrazovky. Tam bych to asi nechala, protože když myší najedu na okno se seznamem souborů, pohybuji se kolečkem jen v tomto okně a ne s celou obrazovkou, což podle mě funguje dobře.

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
odstraněno
