### ISSUE TITLE
Po přejmenování url adresy se výstava nezobrazuje

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#136]
Přejmenovala jsem výstavu z "ošklivého" názvu na pěkný a přestal fungovat náhled. Chybová hláška se odkazovala na to, že výstava není zveřejněná, ani změna stavu na zveřejněná tomu ale nepomohla. 

![zmena-stavu-nefunkcnost](https://user-images.githubusercontent.com/15922183/60088363-d3e0c380-973e-11e9-9335-0f720652a8b4.png)

Zároveň prosím o úpravu pole pro editaci URL, aby URL byla na jednom řádku: http://inqooltest.libj.cas.cz/view/....  

Viz: 

![url-vystavy](https://user-images.githubusercontent.com/15922183/60088405-e529d000-973e-11e9-9b17-e6ecc20c8ad0.png)

**Comment by rudky4** [comment]
Skúšali sme to s odstupom času nasimulovať, ale neporadilo sa. 
Aktuálne funguje zmena názvu korektne. Ak by došlo k problémom znovu, prosím o vytvorenie nového issue.
