### ISSUE TITLE
Úprava názvu dokumentu/bibliografie

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU-Exhibition#137]
Nelze upravovat název položky v sekci Dokumenty/bibliografie. Pouze se zobrazí. 

![uprava-dokumentu](https://user-images.githubusercontent.com/42234445/60175092-dad90600-9812-11e9-9f48-ff19764236b8.jpg)

**Comment by rudky4** [comment]
upraveno

**Comment by nnis** [comment]
Vyřešeno, opravit název jde. S přidáváním souborů je však stále problém, je třeba řešit issue #247
