### ISSUE TITLE
Nahrazení ikony Play (šipka) ikonou pro Text u textové verze

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#139]
Prosím o nahrazení ikony s pauzou, viz 
![ikona-textova-verze](https://user-images.githubusercontent.com/15922183/60265657-8c953700-98e6-11e9-98fd-2a463a68b2ea.png)
ikonou pro text. Pro vrácení do prezentačního módu ikona play funguje dobře, takže ta tam může zůstat. 
Dále by byla skvělá implementace zastavení prezentačního módu pomocí mezerníku a dodání pauzy (asi do pravého dolního rohu nebo mě ještě napadlo nějak využít ten progress bar u obrazovky, ale nevím, jestli by to nebylo matoucí, když je tam ještě ta ikona pro vypnutí zvuku). Nicméně mezerník by měl být asi subtilnější'a méně výrazný, aby na sebe nestrhával pozornost.

**Comment by rudky4** [comment]
ikona změněna. K tomu mezerníku... to je myšleno přechod do textového módu (a zpět) pomocí mezerníku nebo přímo zůstat v prezentačním módu a jen aby vše bylo zastaveno? Pokud se jedná o druhou variantu, tak to bude v této fázi asi komplikovanější a nejspíše tato rozsáhlá úprava přinese zase řadu chyb.

**Comment by nnis** [comment]
Díky, takhle je ta ikona srozumitelnější. 
Myslela jsem to jako druhou variantu - jsem v prezentačním módu, ubíhá čas, je to vidět na progress baru a mezerníkem to stopnu, zastaví se progress bar a po opětovném zmáčknutí pokračuji dál. Pokud by ale byla implementace složitá, není to priorita a můžeme si to poznamenat jako tip na vylepšení do budoucna.

**Comment by jirkacechak** [comment]
ponecháme jako tip pro vylepšení do budoucna

**Comment by Kolemkoukolem** [comment]
V praxi se mi ukázalo, že ikona textu je pro některé návštevníky málo srozumitelná a trvá jim delší dobu, než zjistí její pravou funkci. Co takhle ji nahradit textem: "více k tématu/pozastavit". 
Mám totiž zkušenost, že prvo-návštevníci se soustředí na téma výstavy a nenapadne je zkoumat ikony.

**Comment by nnis** [comment]
Já bych se snažila vyhnout textu, zaměříme se na to a uvidíme, zda s tím uživatelé budou mít problém častěji a najdeme třeba jinou ikonu, ale text bych nedodávala, bude to rušit

**Comment by Kolemkoukolem** [comment]
Co takhle doplnit současnou ikonu "textu" ještě ikonou "stop". Opravdu se nám ukazuje, že návštěvníci jsou zvláště v počátku zmateni přepínáním mezi módy. 
Možná by také stálo za zvážení, zda stránky jednotlivých módů by neměli mít pojmenování viditelné pro návštěvníka, aby i jemu bylo jasné, že se nachází v "prezenčním" nebo "textovém" módu.

**Comment by motyc** [comment]
Týká se požadavku 3

**Comment by nnis** [comment]
Zavíráme issue, protože se kocepčně řeší integrace obou módů dohromady.
