### ISSUE TITLE
Přebarvení ikony s otazníkem u infopointů

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#140]
Na základě diskusí k infopointům a jeho zobrazení na různých pozadích prosím o to, abyste se podívali na možnosti barevnosti. Ukázalo se, že není úplně vhodné, aby byl otazník průhledný, byla také navrhována černobílá/šedobílá varianta. Zkuste prosím něco navrhnout. 
![infopoint](https://user-images.githubusercontent.com/15922183/60266024-7340ba80-98e7-11e9-936c-2208c65a5065.png)

Dále prosím o úpravu barvy vyjížděcího boxíku z modré na bílou/světle šedou/s černým textem tak, aby to ladilo s otazníkem. A dále o nastavení, že od určité výšky se bude boxík zobrazovat pod infopointem a ne nad ním (aby neujel do horní lišty).

**Comment by motyc** [comment]
Souvisí s požadavkem 9

**Comment by nnis** [comment]
Řešíme v souvislosti s novým designem.
