### ISSUE TITLE
Přebarvení zelené na jinou zelenou (úvod, hry)

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#141]
Prosím o výběr nějaké jiné zelené namísto stávající "jedovaté". Zkoušela jsem několik variant a celkově jsem měla lepší pocit z nějakých tmavších zelených (nicméně to by se zase muselo asi upravit písmo, protože ta černá na tom nebyla nejlépe čitelná). Zkuste to zvážit, ty tmavé mi přišly takové méně nápadné, že na sebe nebudou strhávat pozornost oproti obsahu. 
 
Stávající verze
![zelena-hry](https://user-images.githubusercontent.com/15922183/60268693-48f1fb80-98ed-11e9-8131-e5fb6f05a312.png)
![zelena-uvod](https://user-images.githubusercontent.com/15922183/60268699-4becec00-98ed-11e9-9131-933dd33e8ba3.png)

Vyzkoušené verze
#4b8c61
![zelena-napad](https://user-images.githubusercontent.com/15922183/60268732-5e672580-98ed-11e9-99d4-c61b94d97b4b.png)

#01796f
![zelena-napad3](https://user-images.githubusercontent.com/15922183/60268772-763ea980-98ed-11e9-8ad6-abeb488516e2.png)

#0f7063
![zelena-napad4](https://user-images.githubusercontent.com/15922183/60268917-ccabe800-98ed-11e9-86ba-731788a509a2.png)

#014421 (nutná úprava písma)
![zelena-napad5](https://user-images.githubusercontent.com/15922183/60268844-a423ee00-98ed-11e9-9494-b2891bfd3cc5.png)

#c5e0c5
Světlejší varianta, která je víc jako označení obrazovky na dokončenou. 
![zelena6](https://user-images.githubusercontent.com/15922183/60288877-6d61ce00-9915-11e9-8248-eb27aaa5d50c.png)

zároveň prosím upravte šířku okraju i lišty (nejen u her, ale třeba i u texto verze), aby byla až do krajů - v případě, že volím hru, tak to vytváří nezarovanosti a myslím, že ten kraj není třeba rámovat černou, ať je to až dokonce. Mezera mezi pruhy (např. zadání úkolu a políčka přeskočit) naopak funguje dobře, to tam může zůstat, jde o ten vnější kraj. myslím, že to napomůže vizuální jednotnosti. 
![uprava-okraju](https://user-images.githubusercontent.com/15922183/60269259-65dafe80-98ee-11e9-92bb-cbbcce10ccd3.png)

**Comment by motyc** [comment]
A nešlo by se prostě zbavit zelené a používat jinou, decentnější barvu? Např. mou oblíbenou šedou? :)

**Comment by nnis** [comment]
Pro mě taky klidně šedou, v těch větších plochách mi taky nepřišlo, že by ty ostatní zelené varianty, které jsem vyzkoušela, fungovaly nějak víc než ta původní zelená. Nebo ne radikálně. Zas u šedé by bylo třeba zohlednit, že v kvízu se u výběru správné varianty po najetí myši zbarví podklad do šeda (viz poslední screenshot).

**Comment by jirkacechak** [comment]
upraveno, u textového módu ponecháno původní kvůli symetrii s horní lištou

**Comment by nnis** [comment]
Jak původní, myslíte původní zelená? U her nemůžu měnit módy. Nevím, co tímmyslíte, můžete prosím dokumentovat screenshotem? Zatím vidím u her šedou lištou, jinou než podkladová barva u obrázků v kvízu, ale na úvodní stránce vidím stále tu zelenou.

**Comment by jirkacechak** [comment]
Barva na úvodní stránce změněna na šedou, omlouvám se za předchozí opomenutí.
Tím "původní" bylo myšleno, že lišta byla upravena, aby byla do okrajů pouze u her, ale u textové verze obrazovek ne, protože by to nebylo symetrické s horní lištou, která je černá (což by nebylo tak pěkné).
Šedá v kvízu a šedá na liště jsou odlišné kvůli přehlednosti, pokud by byly stejné, tak by to mohlo spolu na oko splývat.
Módy u her nelze měnit, existuje pouze prezentační, pokud tím myslíte toto.

**Comment by nnis** [comment]
OK, zatím to tedy tak nechme, díky.
