### ISSUE TITLE
Orámování textu u názvu kapitoly

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#143]
Prosím o nahrazení bílého orámování u názvu a podnázvu kapitoly na zmiňované rozmazání/rozmlžení. 
![nazev-kapitoly](https://user-images.githubusercontent.com/15922183/60269854-8b1c3c80-98ef-11e9-99e6-14804371bff8.png)

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Díky, u černého podkladu a u černobílé fotografie to vypadá dobře. U barevných je to docela výrazné. každopádně nechte to prosím zatím tak, zeptám se kolegů, zda jim to takhle vyhovuje. Bylo by případně možné to bílé rozmlžení trochu zmenšit?

**Comment by jirkacechak** [comment]
Ano, rozmlžení lze zmenšit
