### ISSUE TITLE
Přejmenování 2 obrazovek

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#144]
Prosím o přejmenování: 
1. "Obrazovka s externím objektem" na "Obrazovka s externím obsahem". 
2. "Zoom in" na "Animace přiblížení"

**Comment by rudky4** [comment]
@nnis upraveno

**Comment by nnis** [comment]
Díky za úpravu, jen ještě poprosím, aby se rozšířilo okno, aby se tam název "obrazovka s externím obsahem" vešla na šířku. Díky
![obrazovka-ext-obsah](https://user-images.githubusercontent.com/15922183/60650860-45a6c480-9e45-11e9-918c-5bfab3855f85.png)

**Comment by jirkacechak** [comment]
upraveno

**Comment by nnis** [comment]
Díky, bezva
