### ISSUE TITLE
Změna textace u her

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#145]
Prosím o nahrazení textace "Reset" u všech typů her na "Zahrát znovu"

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
Reset už tam není, jen jsem si všimla, že u her
1. Posuň na správné místo není položka Zahrát znovu
2. Výběr ze 3 možností obsahuje jen Přeskočit úkol
3. Hádej velikost chybí Zahrát znovu. 

Dávalo by smysl, aby byly všude všechny akce, ne?

**Comment by jirkacechak** [comment]
upraveno

**Comment by nnis** [comment]
Zkontrolováno, díky.
