### ISSUE TITLE
Výpočet délky mluveného slova 

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#147]
Prosím o navýšení času u mluveného slova - autoři si stěžovali, že editor vypočítává kratší délku audia. Pravděpodobně bude komentář klidnější a pomalejší než jsme si mysleli. Případně je možné spojit s kolegyní (matulova@arub.cz), která podhodnocení nahlásila a dokázala by vyčíslit o kolik.

**Comment by rudky4** [comment]
@nnis výpočet předpokládané délky mluveného slova u perex byl snížen na 100 slov za minutu (z původních 130)

**Comment by nnis** [comment]
Super, díky. Issue zavírám a píši mail kolegyním, které s tím přišly.
