### ISSUE TITLE
Zarovnání položek u obrazovky

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#149]
Prosím o zarovnání položek "Vypnuout zvukovou stopu kapitoly" a "Obrazovka je dokončená", je to skoro u všech typů obrazovek i u her. A to tak, aby: 
1. tyto dvě položky byly pod sebou
2. aby zarovnání těchto položek navazovalo na předešlé řádky (aby byly součástí pomyslného čtverce a ne zarovnané na střed a každý řádek jinak) - tedy všechny položky pod sebe

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
Zarovnané, zavírám.
