### ISSUE TITLE
Nová registrace = notifikace pro administrátory

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Exhibition#150]
Overiť, či je takáto notifikácia implementovaná.
Pokiaľ nie, je potrebné ju implementovať.

**Comment by nnis** [comment]
Notifikace o schvalování uživatelů chodí. Předmět emailu prosím opravte z INDIHU Virtuální výstavy - Nová registrace ke schválení na nové: **INDIHU Exhibition - Nová registrace ke schválení**

Znění emailu: 

V aplikaci INDIHU Virtuální výstavy byla vytvořená nová registrace a čeká na schválení administrátorem: d330b3e2-d749-4cac-8312-e9c2f21f7856

Prosím o úpravu jednak textace: 
V aplikaci INDIHU Exhibiton byla vytvořená nová registrace a čeká na schválení administrátorem: [e-mail/jméno]. 

Doplňte cokoli, aby bylo možýné identifikovat žádost. V zásadě není špatný ani ten kód, kdyby v ap,likaci byl nebo byl klikatelný na konkrétní žádost. Ještě mám otázku, jak jsou v současnosti řazeny žádosti? Podle data nebo podle abecedy? Navíc mi přijde, že jich je tam víc stejných.  Nebylo by možné udělat tam nahoře nějaký seznam "Nové žádosti"  nebo "Žádosti k vyřízení" třeba od posledního přihlášení administrátora do systému nebo od posledního schvalování?

Zároveň prosím po schválení žádosti o implementaci e-mailové notifikace novému uživateli v totmo znění: 

Předmět: Registrace do INDIHU Exhibiton byla schválena

Dobrý den, 
od této chvíle můžete na adrese: http://inqooltest.libj.cas.cz využívat nástroj INDIHU Exhibition k tvorbě virtuálních výstav. Informace o tvorbě výstav a používání editoru najdete v manuálu: https://nnis.github.io/indihu-manual/. 
Přejeme Vám mnoho úspěšných virtuálních projektů. Tým INDIHU

Více o projektu INDIHU nalezenete na: https://indihu.cz/
Mezi další produkty INDIHU patří nástroj OCR (http://inqooltest.libj.cas.cz/ocr-web/).

**Comment by motyc** [comment]
Vzhledem k tomu, že výstavy už běží na https://exhibition.indihu.cz/, nebylo by lepší odkazovat na tuto adresu?

dtto s manuálem - neměl by se umístit někam ,kde skutečně zůstane?

**Comment by nnis** [comment]
Kdybych věděla, o přesunu, určitě, ta informace mě nějak minula, to se omlouvám. Manuál je zatím u mě na Githubu a právě ho dokončuji, tak jsem ho chtěla přesunout až to dodělám.

**Comment by motyc** [comment]
To je asi rozumné (přesun manuálu), ale je otázka, zda tedy do mailu už teď rovnou nedat budoucí adresu, aby se to pak zas nemuselo upravovat (snadno se na to zapomene)...

**Comment by nnis** [comment]
A víme kam s ním? Teď mám manuál zveřejněný přes GitHub pages

**Comment by motyc** [comment]
A nešlo by vytvořit třeba https://exhibition.indihu.cz/manual, zatím tam dát nějaký redirect a časem se rozhodne, kde to přesně bude? Šířili bychom ale už jen ten první odkaz...

**Comment by rudky4** [comment]
E-mail pre administrátora upravený.
