### ISSUE TITLE
[N8] Základní úprava fotek - nástroj do editoru

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Exhibition#151]
To by totiž zřejmě nejvíc pomohlo u her, kde hůř funguje přesný překryv obrázků např. u hry Dokresli a i u jiných a tím pádem by se asi vyřešila řada problémů, které se teď s hrami pojí.

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Super, poslala jsem výzvu kolegům, aby pořádně otestovali.

**Comment by motyc** [comment]
- [ ] Při úpravě obrazovky (např. https://exhibition-test.indihu.cz/expo/a9d66bb3-4f53-432c-a235-fb2631e62e5f/screen/image/1-0/image) je nevhodná ikona tužky pro změnu obrázku. Místo ní tam dát ikonu složky a doplnit také proklik přímo na editaci aktuálního obrázku (ikona paleta)

- [ ] V editoru (např. https://exhibition-test.indihu.cz/expo/a9d66bb3-4f53-432c-a235-fb2631e62e5f/screen/image/1-0/image)
-- přisunout ikonu pro zavření (křížek) v liště úplně vpravo

**Comment by motyc** [comment]
Dohodnutá funkcionalita doplněna, ale má to nějaké nedostatky:

- [ ] Na některých obrazovkách ale zůstalo původní řešení (např. ve fotogalerii: https://exhibition-test.indihu.cz/expo/9b5c54c8-a92e-4ad1-a58b-db5deab83d1b/screen/photogallery/0-4/photogallery). Prosím o dohledání a úpravu všude.
- [ ] V některých případech se mi obrázek načte až na druhé otevření téhož (https://exhibition-test.indihu.cz/expo/9b5c54c8-a92e-4ad1-a58b-db5deab83d1b/screen/image-zoom/0-2/sequence). Musím jednou otevřít editor přes ikonu palety (zobrazí se prázdný editor), pak zavřít a znovu otevřít a teprve poté vidím foto.

**Comment by Werxis** [comment]
Nové riešenie pridané na obrazovky začiatku kapitoly, fotogalérie a všetky herné obrazovky. Druhý problém sa mi nepodaril zreplikovať, nechávam na dotaz na najbližšiu schôdzu.
