### ISSUE TITLE
Špatné umístění rozbalovacího okna v editoru

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#156]
Poslední dobou v editoru při rozkliknutí tlačítka pro přidání nového okna se nabídka zobrazí částečně za hranou zobrazení - viz příloha:
![obrazovka_chyba](https://user-images.githubusercontent.com/42067492/63348258-3201df80-c359-11e9-9120-a93a8af2a264.jpg)

**Comment by jirkacechak** [comment]
opraveno

**Comment by Kolemkoukolem** [comment]
Děkuji.
