### ISSUE TITLE
Sekvence zoomu

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#158]
Bylo by možné přidat možnost nastavení jednotlivých časů, jak dlouho budou přiblíženy jednotlivé sekvence? Podobné se již řešilo #22 , ale pro naše účely by bylo vhodnější přímo nastavení času (v některých případech potřebuje prezentaci zdynamičtit, tj. nastavit kratší čas, jindy by bylo vhodnější mít možnost čas nastavit na delší dobu, aby bylo možné se přiblíženému prvku věnovat delším komentářem ve zvukové stopě.

**Comment by jirkacechak** [comment]
hotovo

**Comment by Kolemkoukolem** [comment]
Super. Odzkoušeno. Děkuji.
