### ISSUE TITLE
Šířka horní lišty - vizuální kompaktnost

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#159]
Všimla jsem si, že v textovém a prezentačním módu je jinak široká horní lišta. V jednom případě je téměř poloviční, což pak kazí vizuální jednotnost výsledné obrazovky. 

Jedním z hlavních cílů bylo vytvořit prezentaci, která bude stát na obsahu, bude mít to nejsubtilnější ovládací prvky a výsledný dojem bude pěkný a kompaktní. To se bohužel nedaří. Jednak kvůli horní liště a kvůli spodní liště s šipkami, které překrývají obsah, nejsou uprostřed lišty a jen těsně jsou u horního okraje lišty. Jednou jsem také natazila na to, že obrázek byl na fullscreen, opravdu až dolů k okraji stránky a šipky byly na obrázku. A vůbec to nevypadalo špatně (viz druhý obrázek). 

Prosím o odstranění srcollování u textového módu v části s přiloženými dokumenty ke stránce. a zarovnání horní lišty. Toto je obrazovka Úvod do kapitoly. 
![sipky2-scrolovani](https://user-images.githubusercontent.com/15922183/66378149-3179e280-e9b3-11e9-9002-a9ba2939c459.png)

Lišta nahoře je úzká, dole šipky na fullscreen (obrazovka před a po v textovém módu, kde zcela chybí obrázek po a lišta pro přesouvání): 
![lista-nahore-pred-po-textovy](https://user-images.githubusercontent.com/15922183/66378932-c92c0080-e9b4-11e9-8244-9bef6b6a1b7c.png)

Lišta v prezentačním módu v Obrazovce před a po zasahuje do horní lišty, tentokrát úzké. Prosím aby končila s lištou. Zároveň prosím upravte lištu do designu lišty, která ukazuje dobu trvání obrazovky - progress bar nahoře vpravo. U této obrazovky je obrázek na fullscreen, což by vlastně nevadilo, kdyby tam pak bílý box s názvem obrazovky tak nějak netrčel. Bylo by potřeba se na to podívat a sjednotit to u všech typů obrazovek a buď zachovávat napevno danou lištu dolní i horní ve stejné šířce u obou bódů, nebo fullscreen, ale tak aby to byl opravdu fullscreen a ne ořezávat fotyk z různých stran různě.  
![pred-po](https://user-images.githubusercontent.com/15922183/66379011-f1b3fa80-e9b4-11e9-91fe-fc15fb500fd1.png)

Další varianta jiné šíře lišt: ![sipky3](https://user-images.githubusercontent.com/15922183/66379094-1c9e4e80-e9b5-11e9-9acf-06bf201e952e.png)

**Comment by motyc** [comment]
Souvisí s požadavkem 19

**Comment by nnis** [comment]
Řešíme v novém designu.
