### ISSUE TITLE
Default action - editace obrázků

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#161]
Prosím, aby po zmáčknutí klávesy enter fungovalo uložení obrázku v editoru, teď to reaguje jen na kliknutí myší. Default actions by měly fungovat napříč editorem. Díky. Viz: 

![potvrzeni-enter](https://user-images.githubusercontent.com/15922183/66392944-8d536400-e9d1-11e9-808a-0e9f0c4ae4e4.png)

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Funguje, díky
