### ISSUE TITLE
Web organizace

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#163]
Prosím o přidání řádku, kam by bylo možné vložit odkaz na web hlavního pořadatele výstavy. Odkaz v záhlaví by potom byl klikací a vedl na oficiální stránky instuce. Pokud by to uživatel nevyplnil, název organizace by nefungoval jako odkaz.  

![web-organizace](https://user-images.githubusercontent.com/15922183/66399947-cd6e1300-e9e0-11e9-84a2-bf4af02f6989.png)

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Super, funguje a hezky se to otevře v novém tabu.
