### ISSUE TITLE
[7] Limit nahrávání souborů - video

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#164]
Chtěla jsem vyzkoušet zobrazení a práci s videem v Obrazovce s videem. Ale přes limit 25 MB by neprošlo žádné video, co mám v počítači a to ani 18 vteřin dlouhé video nahrané obyčejně na telefon. Nebylo by lepší v případě videa limit zvýšit?

**Comment by jirkacechak** [comment]
limit nastaven na 75MB

**Comment by nnis** [comment]
Ve výstavě je uveden v kontextové nápovědě limit souboru 250 MB. Při nahrávání videa velikosti 209 MB to trvá, ale nahrálo se. Při takhle velkém souboru, se ale v rozumném čase nenačte obrazovka v režimu náhled (v řádu minut) a i nahrávání celé výstavy při jejím spuštění trvá extrémně dlouho a odradí návštěvníka. 

Je tedy třeba řešit optimalizaci a asynchronní nahrávání výstavy při jejím spuštění, požadavek 7, řádek 15 z tabulky požadavků (https://docs.google.com/spreadsheets/d/1HWOnQdXIHPNG04QQbJ5IEx2OHncj5dU5/edit#gid=1542837833)
