### ISSUE TITLE
Video- chybějící infopoint

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#165]
Prosímo dodání textu k infopointu u obrazovky s videem v záložce video: "Nahrajte video z počítače nebo vyberte z nahraných souborů." Díky

![video-infopoint](https://user-images.githubusercontent.com/15922183/66486520-0d99c800-eaab-11e9-99f3-6448c1c1428d.png)

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Super, díky
