### ISSUE TITLE
Smazaní testovacích výstav

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#167]
Prošla jsem výstavy a přejmenovala očividné výstavy bez obsahu na SMAZAT. Prosím o jejich smazání, protože nemám právo mazat výstavy jiných uživatelů.

Kontrolu dost komplikoval fakt, že jsem se po zavření detailu výstavy dostala opět na začátek seznamu a musela jsem scrolováním najít to správné místo. Když jsem ale mazala jednu ze svých výstav, zůstala jsem po smazání na stejné části stránky. nebylo by možné zůstat vždy tam, kde člověk byl? 

Ještě mě napadlo, jestli má admin možnost kontaktovat uživatele - například by se hodilo, kdybych jako admin mohla uživatele vyzvat, ať si zkontroluje výstavy a případně je smaže, pokud již na nich nepracuje Jsou tam výstavy, které naposledy někdo upravoval před rokem a toto bude jen narůstat.

**Comment by jirkacechak** [comment]
Co se týče pozice ve výpisu výstav, tak po návratu z jiné stránky by již měla zůstat stejná pozice, můžete vyzkoušet.

Admin nemá možnost kontaktovat uživatele v rámci systému. Má přístup k jejich emailu, takže jim může poslat mail. V jaké přesně podobě by měla být pro admina možnost kontaktovat uživatele?

**Comment by nnis** [comment]
Nefunkční výstavy jsou smazané. Díváme k diskusi možnost kontaktovat autory u výstav, které byly naposledy upravovány např. před rokem a nejsou ve stavu zveřejněná a hromadně je kontaktovat. Zvážit, zda to nezařadit funkci filtru do statistiky a Grafany #241

**Comment by nnis** [comment]
Na tuto issue navazuje filtrování uživatelů/výstav. Bude řešena novou issue.
