### ISSUE TITLE
Úprava popisku u obrazovky Animace přiblížení

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#168]
Prosím o úpravu formátu popisku u obrazovky Animace přiblížení, tak, jak je to u infopointů, když do kolonky dám delší text. U Animace přiblížení text zůstává v jednom řádku, u infopointů je to obdélník reagující na délku textu. Díky.

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Hotovo
