### ISSUE TITLE
Bug - menu

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#170]
Všude, kde je menu, jsou místo menu názvy kódu. Prosím o opravu

![bug-menu](https://user-images.githubusercontent.com/15922183/68942585-43685580-07a9-11ea-8cb9-2ad0a2217133.png)

**Comment by rudky4** [comment]
@nnis prosím o preventívne premazanie cache, testoval som nahlásený problém a nepodarilo sa mi ho nasimulovať. Ak bude problém pretrvávať, prosím o zaslanie názvu prehliadača a verzie. Ďakujem
