### ISSUE TITLE
Přejmenování textace Závěr obrazovky

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#173]
Prosím o přejmenování textace Bibliografie na závěrečné stránce výstavy na "Soubory k výstavě". 

Zároveň prosím o úpravu tak, aby názvy přiložených souborů, i když jsou trochu delší, byly na jednom řádku. Díky. Viz: 

![zaver-ukazka-dokumenty](https://user-images.githubusercontent.com/15922183/68947507-eb841b80-07b5-11ea-9fb9-560bca7d0ae0.png)

**Comment by jirkacechak** [comment]
hotovo
