### ISSUE TITLE
Obrazovka s videem - přehrávání v textovém/interaktivním módu

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#174]
Pokud si v prezentačním módu v průběhu sledování videa překliknu do textového/interaktivního módu, začně se mi video přehrávat opět od začátku. = špatně
V případě proklikávání obrazovek v textovém/interaktivním módu je video po překliku na obrazovku s videem vždy nespuštěno (připraveno ke spuštění). = správně

Doporučoval bych, aby se to samé nastavilo i po překliknutí z prezentačního do textového/interaktivního módu. V současném nastavení je nový návštěvník, který správně nepoužívá prvky, zmaten, proč se video stále přehrává dokola.

**Comment by jirkacechak** [comment]
hotovo na testovacím prostředí https://exhibition-test.indihu.cz/

**Comment by Kolemkoukolem** [comment]
Vyzkoušeno, funguje. Děkuji!
