### ISSUE TITLE
Statické menu

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#177]
Nevím, jestli to není tím, že jsem v roli admina, ale prosím o to, aby menu bylo statické a byly tam stále všechny položky. Pokud z hlavní stránky kliknu na Uživatelé, počet položek v menu sice zůstane stejný, ale na pozici Uživatelé se dostanou Výstavy. Zároveň položka Výstavy ve výchozím menu vůbec není, protože je to výchozí pozice pro menu. 

Prosím ještě o to, aby aktivní aktuální pozice se odrazila v menu nějakým zvárezněním/jinou barvou. Myslím, že to pomůže uživatelům v orientaci v systému. 

Díky

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
Menu je třeba řešit: 

- není jasné, co je klikací položka a co ne
- je nutné ukazovat stav výstavy tam, kde jsou klikací položky? 
- když upravuji výstavu, zmizí položka manuál
