### ISSUE TITLE
Problém se zobrazením vložených dokumentů

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#178]
Začal se nám vyskytovat problém u výstavy se zobrazováním dokumentů - odkazů. 

Viz:
![chyba_dokument](https://user-images.githubusercontent.com/42067492/70149619-c72aa900-16a8-11ea-8e79-d901077b7371.jpg)

Před vložením byl pdf-soubor normálně čitelný. Tušíte v čem by mohl být problém? Případně napište, co byste potřebovali za doplňující informace.

**Comment by jirkacechak** [comment]
Bylo vyzkoušeno otevření daného PDF souboru v Adobe Acrobat a v Google Chrome, pokaždé bez problému. Používáte nejnovější verzi? Zkuste případně otevřít v jiných programech, jestli se bude problém opakovat.

**Comment by Kolemkoukolem** [comment]
Ukázalo se, že se primárně jednalo o problém s nastavením proxy serveru. Nicméně problém stále přetrvává na prohlížeči Mozilla. Lze to nějak řešit?

**Comment by jirkacechak** [comment]
Jedná se o nejnovější verzi prohlížeče? Zkoušeli jste soubory PDF otevřít a zobrazit i v jiných programech, jestli se všude tváří jako poškozené?

**Comment by jirkacechak** [comment]
Otevření vyzkoušeno ve Foxit Reader, Adobe Acrobat, Google Chrome, Mozilla Firefox, Chromium, Opera, Internet Explorer i Microsoft Edge a vždy bez problému.
Přetrvává problém stále? Případně v jakých operačních systémech?
Pokud přetrvává, tak poprosím o nasdílení (např. přes google disk) původního souboru a staženého poškozeného souboru.

**Comment by Kolemkoukolem** [comment]
Opět vyzkoušeno. Při spuštění výstavy na Google Chrome bez problémů. Na Mozilla Firefox nelze dokumenty už ani stáhnout (pdf), respektive se po kliknutí na ně objeví bílá obrazovka - viz foto:
![indihu](https://user-images.githubusercontent.com/42067492/80490422-9a31a800-8961-11ea-97ae-5861171700a6.png)
Firefox 75.0 (64 bitů)
operační systém Win 10 Home, 64 bitový

**Comment by jirkacechak** [comment]
o jakou výstavu a obrazovku se jedná?

**Comment by Kolemkoukolem** [comment]
Jedná se o výstavu 100 let Archeologického ústavu v Praze

https://exhibition.indihu.cz/view/100letARU

např. okno 5.2.

**Comment by Kolemkoukolem** [comment]
Vyzkoušeno v testovací verzi a zdá se, že vše již funguje jak má. Děkuji.
