### ISSUE TITLE
[17] Synchronizace stopnutí zvukové a obrazové stopy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#179]
Při přesunu z prezentačního módu do textového v průběhu přehrávání obrazovky a opětovném vrácení do prezentačního módu dojde k zastavení zvukové stopy a poté k jejímu opětovnému spuštění nikoli od začátku ale z místa přerušeného poslechu při přechodu mezi módy. U vizuální složky - video, fotogalerie - ale k navrácení na stejné místo nedochází a návštěvník se dostává opět na začátek. Bylo by možné, aby se vizuální složka chovala při přesunu návštěvníka mezi jednotlivými módy stejně jako zvuková stopa obrazovky?

**Comment by jirkacechak** [comment]
U videa by možná nemusel být velký problém s touto úpravou, u fotogalerie a dalších obrazovek by se ale jednalo o rozsáhlou úpravu, která by asi zabrala spoustu času. Zatím bych nechal na zvážení do budoucna.

**Comment by Kolemkoukolem** [comment]
Na základě dalších zkušeností návštěvníků bych tuto úpravu označil za zásadní. Mám zpětnou vazbu, že opakované přehrávání návštěvníka odrazuje od přepínání mezi textovým a prezenčním módem, což nakonec vede k upřednostnění prezenčního módu a rezignaci na získávání rozšířených informací z odkazů v textovém módu.

**Comment by motyc** [comment]
Ano, to bych celkem potvrdil. Samotného mne to "otravuje" a textovému módu se spíše vyhýbám.

**Comment by H-a-n-k-a** [comment]
MUO: Dobrý den, tento požadavek bych chtěla vrátit do hry. Po přeskočení z prezentačního do textového modu by se zvuk měl zastavit přesně tam, kde skončil. Opětovné přehrávání od začátku je nešikovné.

**Comment by motyc** [comment]
Již vyřešeno
