### ISSUE TITLE
Fotogalerie - posuvník

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#181]
Rozvíjím #23. Při současném testování návštěvníky se nám ukázalo, že současný posuvník v textovém módu je natolik nenápadný, že část návštevníků ho nezaregistrovala a část ho pokusila použít jako "progressbar" a pokusila se použít kliky namísto popotáhnutí. Přimlouval bych se za:
1) větší zvýraznění - např. do modré barvy stejně jako jsou infopointy, guma, vlaječky a pod.
2) vložení nějaké tečky, šipek či něčeho obdobného, aby bylo jasné, že se jedná o scrollbar a nikoli progressbar - např.
![scroll-bar-icon-vector-21286476](https://user-images.githubusercontent.com/42067492/70152497-a022a600-16ad-11ea-8e7d-612a08d26fa4.jpg)

**Comment by jirkacechak** [comment]
hotovo

**Comment by Kolemkoukolem** [comment]
Děkuji!
