### ISSUE TITLE
Fotogalerie - časování

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#182]
Současný stav je takový, že čas se přidělí fotogalerii jakožto celé obrazovce a tento čas se rovnoměrně rozloží mezi všechny snímky. Bylo by možné přidat časování i k jednotlivým obrázkům ve fotogalerii? Např. podobně jako je tomu u obrazovky "Animace přiblížení". Máme za to, že by to pomohlo dynamičtějšímu provázání mluveného slova a doprovodu.

**Comment by jirkacechak** [comment]
hotovo na testovacím prostředí [https://exhibition-test.indihu.cz/](https://exhibition-test.indihu.cz/)

**Comment by Kolemkoukolem** [comment]
Vyzkoušeno. Funguje. Děkuji.
