### ISSUE TITLE
Interaktivní infopointy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#184]
Na zvážení do budoucna nechávám, zda by nebylo vhodné, aby samotné infopointy nebyly interaktivní. Při sledování návštěvníků se nám často stávalo, že se snažili klikáním na infopoint získat další informace.

**Comment by jirkacechak** [comment]
Kurzor změněn na klasický, pokud tím bylo myšleno "interaktivní". Případně, prosím, blíže specifikujte.

**Comment by Kolemkoukolem** [comment]
Nikoli. Myšleno to bylo tak, aby po kliknutí na infopoint se stala nějaka akce typu rozbalení okna s rozšiřujícími informacemi, odkazy apod.

**Comment by jirkacechak** [comment]
Tento požadavek bude potřeba více specifikovat.
Co vše má být umožněno vložit k infopointu a jakým způsobem? Jakým způsobem by se například měly přidávat odkazy? Přímo v textu dodatečných informací nebo zvlášť do vlastních polí?
Jak by se měly poté informace zobrazovat po kliknutí na infopoint? Ve vyskakovacím okně, které bude překrývat část obrazovky nebo nějak jinak?

**Comment by Kolemkoukolem** [comment]
Po domluvě s kolegy prosím o ponechání tohoto bodu jako otevřeného jako námět na budoucí vylepšení. Shodli jsem se, že úprava by byla v současnosti příliš rozsáhlá a je potřeba v budoucnu případně šířeji prodiskutovat.

**Comment by motyc** [comment]
Souvisí s požadavkem 59 a 6
