### ISSUE TITLE
Obrazovka "Foto před a po"

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#186]
Bylo by možné přidat možnost, aby si návštěvník mohl sám určit přesun z této obrazovky na další? V praxi se ukázalo, že některým návštěvník čas nastavený autory výstavy vyhovuje, některým přišel krátký. Navrhujeme, aby zůstala pro autory možnost nastavení jako dosud a navíc přibyla možnost trvání dle potřeb návštěvníka.

**Comment by jirkacechak** [comment]
hotovo

**Comment by Kolemkoukolem** [comment]
Tuto novou možnost se mi nepodařilo v nastevení najít, abych mohl otestovat... Jakým způsobem byla tato možnost implementována?

**Comment by jirkacechak** [comment]
Nastavení se nachází v sekci "Obrázky" v editoru obrazovky "Foto před a po". Je možné, že je potřeba ještě vynutit aktualizaci stisknutím Ctrl+F5. Kvůli tomuto byl přidán automatický tvrdý refresh stránky v prohlížeči, který zajistí, aby od příště měl již vždy každý k dispozici nejnovější verzi aplikace a prohlížeč nezobrazoval svou starou uloženou verzi.

**Comment by Kolemkoukolem** [comment]
Odzkoušeno. Děkuji!
