### ISSUE TITLE
Nekonzistence vypisu vystav

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Exhibition#189]
Po zavření detailu výstavy dostala opět na začátek seznamu a musela jsem scrolováním najít to správné místo. Když jsem ale mazala jednu ze svých výstav, zůstala jsem po smazání na stejné části stránky. nebylo by možné zůstat vždy tam, kde člověk byl?

**Comment by jirkacechak** [comment]
hotovo

**Comment by nnis** [comment]
vyřešeno
