### ISSUE TITLE
Nefunguje delete

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#191]
Při psaní textů v editoru nefunguje tlačítko delete pro mazání, funguje jen backspace, což je nepraktické - nelze tedy označit pomocí šipek text a najednou ho smazat. Označení pomocí šipek funguje jen po jednom a ne na delší část textu pomocí šipky dolů. Prosím o nápravu, díky.

**Comment by nnis** [comment]
A teď nefunguje ani enter. Díky.

**Comment by jirkacechak** [comment]
opraveno

**Comment by nnis** [comment]
funguje
