### ISSUE TITLE
Zveřejnění - URL výstavy

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU-Exhibition#192]
Když jsem dala "zveřejnit" naši výstavu (Pavlov: V krajině lovců a sběračů), URL je pořád ve formátu "http://inqooltest..". 

Je to ok? Všichni se mě na ústavu ptají, zda je to nějaký polotovar nebo se to dá už dávat na web a veřejně výstavu šířit. Odkaz funguje, jen se lidem nelíbí, že je to pod takovou zvláštní adresou. 

Odkaz na výstavu:
http://inqooltest.libj.cas.cz/view/Pbhlokality2019-04-12T070156004Z

Najdu někde lepší znění URL? Nebo je to zatím takto poslední verze a máme ji užívat?

**Comment by motyc** [comment]
Ono je to zaměnitelné. Bude to fungovat i pod odkazem: http://exhibition.indihu.cz/view/Pbhlokality2019-04-12T070156004Z

Co je za lomítkem po view lze stanovit přímo v nastavení výstavy.
