### ISSUE TITLE
Fotogalerie - nefunkční posuvník v textové verzi

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#194]
Prosím o opravu nefunkčního posuvníku v textové verzi - zkoušeno na tabletu Lenovo Yoga Android.
Díky 
![posuvnik](https://user-images.githubusercontent.com/15922183/77301308-c36e7100-6cef-11ea-8c98-8504956e2286.JPG)

**Comment by jirkacechak** [comment]
opraveno

**Comment by nnis** [comment]
Posuvník na stejném mobilním zařízení Lenovo Yoga Android stále nefunguje, nicméně funguje swipe doprava v posunu ve fotogalerii na dotykové obrazovce. Takže 

- změnila se podoba lišty a nefunguje
- dále není v prohlížeči Chrome výstava na fullsreen, takže musím posunout dolů, abych viděla nefunkční lištu, čímž ení videt šipky doprava a doleva a soubory k obrazovce  

Je třeba se k ovládacím prvkům vrátit a aktuálně probíhá velká revize prezentačních módů jako takových v novém designu

**Comment by nnis** [comment]
Stále nefunguje, ale možná můžeme počkat na novou mobilní verzi.
