### ISSUE TITLE
Načtení souborů 

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#195]
![nacteni-souboru](https://user-images.githubusercontent.com/15922183/77302955-6aeca300-6cf2-11ea-8df9-c279ba543937.JPG)
Během tvorby výstav docházelo k problémům se soubory - objevilo se to i u obrázků. Teď při testování výstavy na tabletu Lenovo Yoga Android byl problém s audiem. 

je to tahle výstava: https://exhibition.indihu.cz/view/rika-se-ji-sametova/start

Napadá Vás, v čem to vězí a jak to odstranit? Na desktopu mi to žádnou chybu nehlásilo, takže je to pak problém u návštěvníka a jeho koncovým zařízení? Je hloupé, že to je jedna z věcí, co se návštěvníkovi hned zobrazí, i když většina souborů jede.

**Comment by jirkacechak** [comment]
Jedná se pravděpodobně o problémy s danými soubory přímo v koncovém zařízení. U některých souborů byl i problém se samotným načtením aniž by to ukazovalo nějakou chybu, takže byl přidán časový limit 5 minut u načítání každého souboru. Při vypršení se zobrazí podobná hláška, jako u chyby.
Zatím by bylo asi vhodné přidat minimálně do manuálu informaci o tom, ať si uživatelé svoje výstavy vyzkouší i na nějakém zařízení s operačními systémy Android a iOS (případně jiné), pokud chtějí, aby byly podporovány.

**Comment by frantis** [comment]
Pozoruji výrazné zhoršení, cca v 80 % případů tvrdých refreshů výstavy mám chyby. Výstava Labyrint během přípravy a testování ze stejného pc nikdy chybu nevykazovala. 
Nejde vždy o stejné soubory.
![labyrint1](https://user-images.githubusercontent.com/4487667/77731763-d640b880-7003-11ea-9290-b116a3f21f9e.png)
![ractevstoupit](https://user-images.githubusercontent.com/4487667/77731772-da6cd600-7003-11ea-9fcb-fd76639d3cb1.png)

**Comment by rudky4** [comment]
@frantis Dobrý deň, akú máte +-rýchlosť internetového pripojenia?
Výstavu som skúšal bez cache v anonymnom okne, načítala sa bez problému, ale bolo to celkovo 80+ MB.

![image](https://user-images.githubusercontent.com/7311447/77734472-0c346b80-7009-11ea-917e-b67bbd7707ea.png)

To môže teoreticky u niekoho robiť problémy. Máte nejaké bližšie informácie k tomu, ako by sme mohli nasimulovať tento problém? Ďakujem

**Comment by frantis** [comment]
Mám pomalejší, cca 20 Mbit/s.
Začalo se to dít časově v době cca https://github.com/LIBCAS/INDIHU-Exhibition/issues/195#issuecomment-603433029 , proto jsem to připojil k této issue. Ale souvislost pochopitelně pouze odhaduji

**Comment by rudky4** [comment]
Preveríme to, ďakujem za upozornenie.

**Comment by jirkacechak** [comment]
časový limit byl zvýšen na 12 minut

**Comment by nnis** [comment]
Z aktuálního výzkumu mezi dospělými návštěvníky INDIHU to stále trvá

**Comment by xkollar3** [comment]
Ahoj, na výstave ktorá je priložená v issue pôvodne sa to nedeje, vedeli by ste mi poslať nejaké výstavy ktoré majú s tým problém momentálne? Najlepší by bol priamo odkaz na otvorenie výstavy kde vidno chybu ostátne dáta si už dohľadám k výstave.

**Comment by motyc** [comment]
Děje se to např. zde: https://exhibition.indihu.cz/view/Vzniksamostatnhoeskoslovenskhosttu2022-05-26T135737330Z/start

![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/8dd1a30c-3071-4954-ad20-df5b380513ee)
