### ISSUE TITLE
Výstavy Národního muzea

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#196]
Namátkovým testováním (https://www.nm.cz/virtualne-do-muzea#online-vystavy) zjištěno:

1) Ani jedna se mi neotevře v Google Chrome - problikne načítání a pak se zobrazí černá obrazovka s informací, že výstava není zveřejněná. V Mozille funguje, v anonymním okně Chrome také. Cache jsem smazal a nepomohlo to. Testováno na dvou PC.

2) https://exhibition.indihu.cz/view/rika-se-ji-sametova/3/2 - zde se výstava zasekla (bílé okno) a nepokračuje (v Mozille). Přitom další kapitoly tam jsou, ale asi bude nějaká chyba ve struktuře výstavy.

**Comment by krizovj** [comment]
Já jsem zkoušela tu o novinách (Labyrint informací a ráj tisku) a v Google Chrome mi funguje. 

Google Chrome je aktuální
Verze 80.0.3987.149 (Oficiální sestavení) (64bitový)

**Comment by krizovj** [comment]
Tak mi funguje i ta druhá opět Google Chrome...

**Comment by motyc** [comment]
Je to zvláštní chování. Ale nedokážu rozklíčovat, čím to může být.
Také Verze 80.0.3987.149 (Oficiální sestavení) (64bitový)

**Comment by motyc** [comment]
![image](https://user-images.githubusercontent.com/20186892/77525716-bbe2cf80-6e89-11ea-834e-f4b5aad60b87.png)

**Comment by motyc** [comment]
Stejný problém se objevil už dříve: https://github.com/LIBCAS/INDIHU-Exhibition/issues/136

**Comment by frantis** [comment]
Setkal jsem se s tím podruhé teď taky. Restart prohlížeče/reload stránky bez cache nepomůže. Z anonymního okna funguje. Mně pomohlo znovu se přihlásit do platformy. 


[exhibition.indihu.cz.har.txt](https://github.com/LIBCAS/INDIHU-Exhibition/files/4380245/exhibition.indihu.cz.har.txt)


![image](https://user-images.githubusercontent.com/4487667/77526355-b76ae680-6e8a-11ea-8e8a-089983eea180.png)

**Comment by frantis** [comment]
Včera se mi to stalo taky ráno potom, co jsem zkusil poprvé načíst na PC, kde jsem v noci na výstavě dělal.

**Comment by frantis** [comment]
Uživatelé se s tím setkávají s železnou pravidelností, vždy druhý den poté, co výstavu editovali. Radím jim znovu se přihlásit. U jiných výstav (které needitovali) se jim to nestává.

**Comment by jirkacechak** [comment]
nejspíše vyřešeno, prosíme o kontrolu

**Comment by motyc** [comment]
Ano, zdá se, že už to běží dobře.

**Comment by frantis** [comment]
U mě v pořádku taky funguje
