### ISSUE TITLE
Posunutí obrázků - useknutí textu

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU-Exhibition#197]
U některých fotek máme nahoře text, který ještě nedávno šel bez problémů přečíst - nyní je useknutý. Nejde o to, že bych nemohla fotky předělat, ale předtím to přečíst šlo - lze fotky zmenšit / posunout? 
Konkrétně je to v naší výstavě Pavlov. Nechce se mi zobrazit vložený printscreen, tak snad bude fungovat odkaz na google disk:
https://drive.google.com/file/d/1Cq8wMQt_qFaohrj_BiwIxp0LnHGWivkL/view?usp=sharing 

![text](https://user-images.githubusercontent.com/42234445/77651352-f6716880-6f6c-11ea-9f7e-9ed5c401a2c2.jpg)

**Comment by jirkacechak** [comment]
opraveno

**Comment by nnis** [comment]
Na tento problém jsem nenarazila, takže asi OK.
