### ISSUE TITLE
Obrazovka před a po - nepřehrává se audio stopa

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#199]
Ve výstavě "Na Sibiř z domova" Sibiře nefunguje přehrávání u obrazovky typu foto před a po. V náhledu běží bez problémů, ale při celkovém projíždění výstavy se nespustí. Týká se obrazovek 2.1 a 2.5. 

Prosím o rychlou opravu, výstava se zvěřejňuje zítra, díky

**Comment by jirkacechak** [comment]
opraveno

**Comment by nnis** [comment]
Při aktuálně dokončené výstavy audio u obrazovky před a po funguje dobře
