### ISSUE TITLE
Obrazovka před a po - nefunguje táhlo v textovém módu

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#200]
U horizontálního i vertikálního táhla nefunguje u obrazovky před a po táhlu v textovém módu. Viz schreenshot. Prosím o opravu. 

![pred-po-prezentacni](https://user-images.githubusercontent.com/15922183/78574730-b80c6100-782a-11ea-9864-05dbf605405e.png)
![pred-po-textovy](https://user-images.githubusercontent.com/15922183/78574733-b8a4f780-782a-11ea-8675-6b91833bcff7.png)

**Comment by jirkacechak** [comment]
V textovém módu je tato obrazovka řešena podle specifikace tak, že jsou pro každou variantu obrázky vedle sebe (bez táhla apod.). Bylo opraveno zobrazení, aby byly obrázky viditelné pomocí scrollbaru.

**Comment by nnis** [comment]
Aktuálně to funguje tak, že se udělá posuvná lišta dole a obrázky jsou za sebou a tedy zcela nefunguje pointa u před a po. Je třeba řešit v novém designu.

**Comment by nnis** [comment]
Řeší to nový design, protože všechny interaktivní prvky v textovém módu "ztrácí pointu".
