### ISSUE TITLE
Zaměnitelnost typu dokumentů

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#201]
"Související dokumenty" různých typů jsou v textovém módu zobrazeny stejnou ikonkou, ač při tvorbě výstavy je možné nastavit typ (bez odkazu, URL, soubor). V důsledku to znamená, že divák netuší, k čemu ho odkaz dovede, resp. v případě pouhé citace (žádný odkaz) se domnívá, že je odkaz nefukční - viz obrázky.
![Obr 1 1](https://user-images.githubusercontent.com/42067492/80471212-65165d00-8943-11ea-8cf7-d182b507432a.png)
![Obr 1 2](https://user-images.githubusercontent.com/42067492/80471216-66478a00-8943-11ea-8901-3df70fef14d3.png)
![Obr 2 1](https://user-images.githubusercontent.com/42067492/80471224-68a9e400-8943-11ea-8a43-654325de91a6.png)
![Obr 2 2](https://user-images.githubusercontent.com/42067492/80471230-6ba4d480-8943-11ea-84bc-d899454a2cea.png)

**Comment by jirkacechak** [comment]
hotovo na testovacím prostředí [https://exhibition-test.indihu.cz/](https://exhibition-test.indihu.cz/)

**Comment by Kolemkoukolem** [comment]
Ozkoušeno. Funguje.
