### ISSUE TITLE
Červený štítek Test je vidět při prohlížení

### ISSUE THREAD

**Issue by frantis** [LIBCAS/INDIHU-Exhibition#202]
Červený štítek Test je nyní vidět ve všech módech bez ohledu na přihlášení, nevím, jaký je jeho záměr, ale předpokládám, že při prolhížení výstavy nepřihlášeným uživatelem je to jistě bug.

![image](https://user-images.githubusercontent.com/4487667/80983192-9b187d00-8e2c-11ea-983b-d927cc070ad1.png)

**Comment by jirkacechak** [comment]
opraveno

**Comment by nnis** [comment]
Teď tam není, takže asi OK
