### ISSUE TITLE
Neúplné zobrazení delších názvů výstavy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#206]
V případě delšího názvu výstavy se na úvodní obrazovce tento název nezobrazuje celý.
![Obrázek1](https://user-images.githubusercontent.com/42067492/91743580-51f8ef80-ebb8-11ea-9b29-e68e2a2dfee7.png)

**Comment by jirkacechak** [comment]
celý název se bude zobrazovat po přesunutí kurzoru nad text

**Comment by Kolemkoukolem** [comment]
V testovacím režimu funguje. Děkuji.
