### ISSUE TITLE
[47] Statistiky zhlédnutí výstavy + hodnocení

### ISSUE THREAD

**Issue by jirkacechak** [LIBCAS/INDIHU-Exhibition#210]
- statistiky, které autor uvidí v administraci výstavy

@rudky4 BE

**Comment by motyc** [comment]
Souvisí s požadavkem 47

**Comment by nnis** [comment]
Zvážit, jak statistiky chceme a jaký využít nástroj (viz kauza Google Analytics a jeho zákaz v Evropě) anebo zda to neudělat sami. 

Viz alternativa: https://matomo.org/

**Comment by nnis** [comment]
Probrat s InQool - chceme tvůrcům říct jednoduchý údaj "počet zhlédnutí" jako má YT a dodat výsledky z hodnocení výstav z konce (komu se to líbilo, co hodnotili, komentáře).

**Comment by kristynahubickova** [comment]
Počet zhlédnutí (64) | Hodnocení (4.2) | Komentáře (3💬) | ☆ (Hry) | +*
* advanced funkce: nabízí se graf počtu zhlédnutí za týden/měsíc/rok/od počátku, údaje o návstěvnících: pohlaví, věk, zdroj návstěvnosti, lokalita, porovnat videa

počet zhlédnutí = přesáhne 30sec (jako u youtube, kontinuálně i s prokliky)
kam umístit? do dlaždice ke každé výstavě nebo jako seznam u "Čtení pro zápis" alá přehled youtube

**Comment by motyc** [comment]
Základní statistiky zahrnout do dlaždice i do tabulky. V této souvislosti provést redesign dlaždice tak, aby:
- celkově byly přehlednější (podstatné informace zvýrazněné atd.)
- nadpis byl lépe viditelný
- zvýraznit stav
- "Poslední editace" -> "Upraveno" 
- formát u Upraveno: "28. 11. 2017 12:22 (filiphyza)"
- formát u Vytvořeno: "28. 11. 2017 (filiphyza)"
- "Naposledy upravováno" - odstranit (sloučeno do Upraveno)
- zbavit se rolovátek
- umožnit výběr a kopírování z boxu (nyní se po kliknutí otevře výstava, takže to nejde - na výstavu jde přejít přes Upravit, takže tento proklik není třeba)

**Comment by Werxis** [comment]
- došlo k celkovému prerobeniu kartičky (dlaždice) expozície

**Comment by motyc** [comment]
Chování je násobně lepší, jde o velký posun vpřed. K doladění:
- [ ] Na kartu výstavy doplnit ještě:
-- počet zhlédnutí
-- počet komentářů
-- nejlépe hodnocená vlastnost (téma, média, texty, hry)
- [ ] Umožnit snadný proklik přímo do části "Hodnocení a návštěvnost", např. hyperlinkem či ikonou u souvisejících údajů.
- [ ] Doplnit nové údaje také do tabulkového zobrazení (nyní chybí prům. hodnocení)

**Comment by motyc** [comment]
@Werxis
- [ ] chybí počet zhlédnutí (viz @kristynahubickova počet zhlédnutí = počítá se, přesáhne-li doba u výstavy 30sec)
- [ ] i pro https://exhibition-test.indihu.cz/expo/9b5c54c8-a92e-4ad1-a58b-db5deab83d1b/rating se pro nejlépe hodnocená vlastnost zobrazuje "zatím žádná", přestože data existují, stejný problém je se zobrazeným počtem komentářů
- [ ] zapomněli jsem probrat bod: Umožnit snadný proklik přímo do části "Hodnocení a návštěvnost", např. hyperlinkem či ikonou u souvisejících údajů.

**Comment by Werxis** [comment]
Všetky tri body zapracované.

**Comment by motyc** [comment]
Přidání hodnocení se propíše do data poslední úpravy, což nedává smysl. To by mělo zohledňovat jen skutečnou editaci výstavy, nikoli jen uživatelskou interakci. Jinak ok.

**Comment by Werxis** [comment]
Posledné dva body zapracované.
