### ISSUE TITLE
Ikonka volume-up (zvuk/reproduktor) na úvodní stránce výstavy

### ISSUE THREAD

**Issue by cironis-adam** [LIBCAS/INDIHU-Exhibition#212]
Na úvodní stánce výstavy je v levém dolním panelu Nadpis a podnadpis výstavy a napravo od něj je ikonku Hamburger menu a Reproduktoru/zvuku s popiskem Více informací. Obě ikonky včetně textu Více informací slouží k tomu, že je možné na panel kliknout a on se otevře, kde se zobrazí ještě perex a seznam kapitol.
Nebylo by vhodnější odebrat ikonku zvuku a nahradit (případně ponechat) hamburger menu něčím příznačnějším pro otevření více informací?

**Comment by motyc** [comment]
Souvisí s požadavkem 9

**Comment by nnis** [comment]
Řeší nový design
