### ISSUE TITLE
Možnost nastavení velikosti textu

### ISSUE THREAD

**Issue by cironis-adam** [LIBCAS/INDIHU-Exhibition#217]
Toto spíše feature request na zamyšlení. Máme na jedné prohlídce Obrazovku s textem a při větším množší textu (není to nějaká esej) se sice velikost textu přizpůsobí (což je super), přesto je ale moc velké pro celý odstavec (hůře se to čte).
Na tyto případy by bylo skvělé mít možnost velikost nastavit ručně.

**Comment by nnis** [comment]
Řešíme v novém designu. Zavedení wisiwig editoru apod.
