### ISSUE TITLE
Fake news ikony na závěrečné obrazovce

### ISSUE THREAD

**Issue by klodner** [LIBCAS/INDIHU-Exhibition#218]
Na závěrečné obrazovce jsou ikony kontroverzních korporátních fake news platforem, které nelze vypnout.

**Comment by rudky4** [comment]
Prosím o screenshot.

**Comment by klodner** [comment]
![Screenshot 2021-02-22 141921](https://user-images.githubusercontent.com/35034190/108713937-317f7180-7519-11eb-87b0-83c17a0f6448.jpg)
