### ISSUE TITLE
Nastaveni - dlaždice se založenou výstavou

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Exhibition#219]
Jak mají fungovat 3 tečky nad sebou v pravém dolním roku dlaždice se založenou výstavou. Když na ně kliknu, tak se mi objeví prázdná obrazovka a nemůžu se ani vrátit zpět. Stejná reakce nastane, když si chci prohlédnou dokument přiložený k výstavě (seznam použitých zdrojů a literatury).

Má tam být menu k výstavě (tedy přejmenovat, sdílet apod.), ale je to prázdné.

**Comment by nnis** [comment]
To teď funguje, otázkou je, zda tam nedat ikonu ozubeného kola jako nastavení. Dále se mi také u menu nelíbí zarovnání položek na střed. proto bych se k tomu vrátila. Otázkou také je, zda u výstavy držet rozdělené záložky Nastavení a Sdílení a nesloučit je a zároveň nepřidat nějaké funkce, které jsou u toho výpisu a ne už nikde jinde (Přejmenovat, Náhled nebo Duplikovat) 

![menu-u-vystavy](https://user-images.githubusercontent.com/15922183/154049740-07970877-3c00-43ab-ad68-c1faa2dd9099.png)

**Comment by nnis** [comment]
Není třeba řešit
