### ISSUE TITLE
[9] Hezčí a dynamičtejší rozhraní a ovládacích prvků

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#239]
**Issue slouží ke sběru podnětů pro uživatelské rozhraní a design**
Vždy napište, co vás na prvku zaujalo, popište chování prvku, udělejte screenshot a dejte link na stránku

**Comment by kristynahubickova** [comment]
**Tohle asi není ani tak inspirace, jako ukázka toho, že velmi podobně pracují s virtuálními výstavami on site ve Švédsku (konkrétně Museum of World Culture)**

![IMG_6892](https://user-images.githubusercontent.com/79597746/145985323-9e4d47fb-caaf-456b-a6c3-4de9c23265ca.jpg)
![IMG_6898](https://user-images.githubusercontent.com/79597746/145985336-f1930b26-832b-48ee-a605-ce79e78bbbb7.jpg)

**infopointy**

https://user-images.githubusercontent.com/79597746/145991295-997e27b7-b5fd-4b4c-9375-8d6006130187.mp4


**Kahoot - inspirace a alternativa progress baru v levém dolním rohu** a taky využití pozadí.

<img width="1429" alt="Snímek obrazovky 2021-12-14 v 11 25 03" src="https://user-images.githubusercontent.com/79597746/145985410-c7b5a0fd-743a-4f62-a4b6-4cbffa41cf4a.png">

Quizlet a jejich **"subjects" rozřazení** - inspirace ke vzniku**"centrální databáze" výstav právě třeba podle tématu (nebo délky, publika, hodnocení, atd)**

<img width="1437" alt="Snímek obrazovky 2021-12-14 v 11 28 35" src="https://user-images.githubusercontent.com/79597746/145986591-5a44b189-3b50-48e3-a76d-8180c15d5690.png">

Líbí se mi idea **featured výstavy na landing page**, mohla by se třeba i obměňovat
<img width="1436" alt="Snímek obrazovky 2021-12-14 v 11 34 32" src="https://user-images.githubusercontent.com/79597746/145989788-9736d37d-a20a-40b9-98c2-35bea63d844a.png">

<img width="1425" alt="Snímek obrazovky 2021-12-14 v 11 35 14" src="https://user-images.githubusercontent.com/79597746/145989918-9716b8dd-52c4-407f-b144-f116fe3015a8.png">

**Comment by nnis** [comment]
Mě se líbí chování ovládacích prvků na stránce DOXu (https://www.dox.cz/). A to konkrétně: 
- zbarvení prvků, když na ně najedu myší
- krátky s tím, že se kolečko změní ve čtverec 
- že když na něco kliknu, prvky se objeví v pohybu a pak až se ustálí 
![ovladaci-prvky](https://user-images.githubusercontent.com/15922183/146049624-a5fe6c87-1791-4bc3-830e-673d304f7c5f.png)

Tady na té stránce se stejně jako u DOXu pohybují prvky, než se "načtou" (https://jankelley.com/about/) - zároveň tam mají celkem hezky udělaný info boxíky, když člověk najede myší na nějaký prvek
- taky tammají vpravo nahoře ikonu menu a křížku, která se mění, to mi taky přijde dobrý
![ovladaci-prvky2](https://user-images.githubusercontent.com/15922183/146050715-bca1d045-5856-4fd1-bd0c-2ccc5241c77d.png)

**Comment by H-a-n-k-a** [comment]
Pár podnětů k ikonám a tlačítkům obecně: 

- rozlišit klikací a neklikací ikony (barva, pulzování)
- užití i neviditelných/průhledných tlačítek/ikon jako dosud, ale doplnit vysvětlující zprávy o funkci ikony/tlačítka zobrazující se při najetí myší a/nebo přímo v ikoně
- "button states" - odlišit tlačítko (barva, pulzování) při přejetí myší, rozlišovat použité tlačítko či neaktivní tlačítko (užití např. v kvízech, jiných minihrách?)
- plující tlačítka, případně celá plující lišta (budou zasuté a ukáží se jen při pohybu myší)

Příklady:

Construct Klee app
- velmi se mi líbí spodní lišta
- skvělé řešení práce s umístěným objektem (rohy výřezového čtverce mají funkci)

![ConstructKlee_c](https://user-images.githubusercontent.com/93780817/146277490-7d4cc7af-357b-4956-b6a8-170e202625f0.jpg)

![ConstructKlee_bb](https://user-images.githubusercontent.com/93780817/146277573-0fabbab7-42c0-4428-bd75-1a6a9c7e9f5b.jpg)

![ConstructKlee_b](https://user-images.githubusercontent.com/93780817/146277559-72894822-2edd-4f24-bfc8-a5c4356898a2.jpg)

![ConstructKlee_a](https://user-images.githubusercontent.com/93780817/146277833-c0c14b9a-16de-4cd4-beb4-700060f68af2.jpg)

KHM Stories app
- líbí se mi infopointy

![Google Play Store](https://user-images.githubusercontent.com/93780817/146278057-e03e341f-b5ee-426d-801e-b30ab387b281.jpg)

KUB app
- líbí se mi naddimenzované neviditelné ikony

![KUB_audioguide01_480](https://user-images.githubusercontent.com/93780817/146278124-d583c613-8c25-4e26-88c6-2355abf5a089.jpg)

Unravel Van Gogh app
- moje oblíbená aplikace
- pěkné řešení ikon, nevtíravé umístění ikony Informace:
![app_touch_van_gogh_1](https://user-images.githubusercontent.com/93780817/146278347-3ad0a4c7-634d-40c2-b210-a7b677dbf19c.png)

- elegantní popisky obrázků, dobrá ikona šipky
- rozvrstvení stránky, která má hloubku:
![app_touch_van_gogh_3](https://user-images.githubusercontent.com/93780817/146278521-88e14e97-8cea-4ea0-8761-049a91d3b8ba.png)

- dobré užití neviditelných tlačítek:
![app_touch_van_gogh_5](https://user-images.githubusercontent.com/93780817/146278579-36e00703-e97c-4326-b8cd-fa6010d5ac47.png)

- příklad užití posuvníků "před a po":
![app_touch_van_gogh_2](https://user-images.githubusercontent.com/93780817/146278619-4f2d859d-fa89-4d8d-bc31-6b3f41305216.png)

- skryté rozšiřující informace a jak vypadají po rozkliknutí:
![app_touch_van_gogh_4a](https://user-images.githubusercontent.com/93780817/146278703-a944a8bc-bc3b-4db7-9082-358e93bc721d.png)
![app_touch_van_gogh_4b](https://user-images.githubusercontent.com/93780817/146278711-2b601115-c9a0-4a3f-8b58-3aea05e8486f.png)

- čtverec rozrolovaného infopointu/kukátka/zoomu:
![app_touch_van_gogh_6](https://user-images.githubusercontent.com/93780817/146278791-fe53be57-1d65-452a-a5c9-864fed0193d8.png)

- příklad neviditelné ikony s přímo vepsaným pokynem k funkci či činnosti:
![app_touch_van_gogh_7](https://user-images.githubusercontent.com/93780817/146278855-e73d57e9-3ce2-4895-b314-c775bb4eaff4.png)

**Comment by nnis** [comment]
Tady je také hezky řešený infopoint a tím, že tak trochu jemně pulzuje, zve k rozkliknutí, tak dávám jako inspiraci 

![infopointy-nabytek](https://user-images.githubusercontent.com/15922183/161099201-a12892ee-d022-4d37-8e6f-8f029cbfd588.png)

Viz: https://www.triant.cz/kategorie/kolekce/stela/
