### ISSUE TITLE
Úvod výstavy - čas obrazovky a animace (MUO)

### ISSUE THREAD

**Issue by matulovaklara** [LIBCAS/INDIHU-Exhibition#24]
Je někde možnost ovlivnit animaci obrázku na pozadí na první obrazovce (úvod výstavy)? 

Při náhledu výstavy se spustí animace, která sjíždí shora dolů, takže se pak zastaví v bodě, kde už na fotce nic podstatného není. Je možné přidat tuto položku (výběr: bez animace, shora dolů, zdola nahoru), jako je tomu u dalších hlavních obrazovek ("úvod do kapitoly")?

**Comment by rudky4** [comment]
Bude doplnená možnosť výberu animácie (Bez animace / Shora dolu / Zdola nahoru)

**Comment by nnis** [comment]
Obrazvka úvod do kapitoly bývá zobrazená relativně krátkou dobu - třeba 5 vteřin, když dám animaci obrázku, jede to poměrně rychle a je tak trochu hrubě ukončená uprostřed animace. Navýšení času animaci jen zpomalí a useknutí zůstává a navíc se prodlužováním vlastně navyšuje čas celé výstavy. 

Navrhuji, aby defaultně byla animace u tohoto typu obrazovky pomalejší a v závěru tam bylo malé setrvání bez pohybu. 
Natočila jsem video, jak to vypadá: https://drive.google.com/file/d/1NVcKs8pFcPnvjcJ4MaR7JAUlQv1RjKYL/view?usp=sharing

**Comment by jirkacechak** [comment]
V závěru zůstane obrazovka 3s bez animace. Samotnou animaci nelze zpomalit, jelikož se odvíjí od doby zobrazení obrazovky, která se nastavuje v editoru (odteď bude doba animace jako doba zobrazení obrazovky bez 3s).

**Comment by nnis** [comment]
Animace funguje dobře, ale není možné nastavit čas trvání obrazovky, proto: 

1. Prosíme o přidání možnosti nastavit délku obrazovky (kvůli rychlosti animace) 
2. Nezobrazovat progress bar s plynutím obrazovky jako je tomu u ostatních obrazovek 

Po uplynutí času obrazovky se nic nestane a čekáme na kliknutí návštěvníkem na "Projít si výstavu"
