### ISSUE TITLE
[21] Velikost pole u popisku k infopointům

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#243]
Prosím o zvětšení pole, do kterého píšu popis u infopointu - vidím v podstatě jen dvě slova a špatně se text opravuje. Ideální, aby bylo pole tak velké (dlouhé), jako je ideální počet znaků (tedy těch cca 100-120 znaků). 

**Aktualní**
![infopointy-velikost-textu](https://user-images.githubusercontent.com/15922183/147483584-9898bfaf-e57a-408f-b40d-65f56bd61919.png)

**Nové**
![infopointy-velikost-textu-new](https://user-images.githubusercontent.com/15922183/147484712-07d8655a-006b-40d6-bdb0-27d910b0f0fb.png)

Infopointy jsou u 
- Obrazovky s obrázkem
- u Animace přiblížení
- u Fotogalerie

**Comment by motyc** [comment]
Jen mne napadá, že vzhledem k novým požadavkům na infopointy (možnost vložit obrázek, vložit URL atd.) se asi bude editační rozhraní stejně měnit, bylo by dobré řešit to nějak najednou...

**Comment by Werxis** [comment]
Samotné infopointy v administračnom rozhraní tvorcu vyzerajú podobne, ale pri editácii textu sa otvorí dialóg s text fieldom, kde sa dá text po novom editovať. Označujem teda momentálne na test.

Napadá ma ešte, že neprebehla zmena infopointov pre obrazovku animácia priblíženia, avšak táto obrazovka má aj tak samostatné issue, ktoré mám v pláne čoskoro zapracovať #267
