### ISSUE TITLE
Vypršelý SSL certifikát

### ISSUE THREAD

**Issue by cironis-adam** [LIBCAS/INDIHU-Exhibition#244]
Je možné, že vypršel SSL certifikát na doméně exhibition.indihu.cz? 

<img width="724" alt="Screenshot 2022-01-03 at 15 55 11" src="https://user-images.githubusercontent.com/2216357/147945667-eca4d8e5-8336-4984-a9b1-ee274531cab6.png">
<img width="469" alt="Screenshot 2022-01-03 at 16 03 49" src="https://user-images.githubusercontent.com/2216357/147946228-31b1404a-38c9-4cfd-8948-7076d089f561.png">

**Comment by rudky4** [comment]
Opraveno, diky za upozorneni.
