### ISSUE TITLE
Úvod výstavy - čas obrazovky a animace

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#246]
Navazuje na #24

- [ ] Přidání možnosti nastavit délku obrazovky (kvůli rychlosti animace)
- [ ] Nezobrazovat progress bar s plynutím obrazovky jako je tomu u ostatních obrazovek

**Comment by motyc** [comment]
@nnis Tady si nejsem úplně jistý - původní issue se dotýkalo úvodů do kapitol, mluví se zde tedy o úplně úvodní obrazovce, když přijdu na výstavu? Prosím jen o potvrzení...

**Comment by nnis** [comment]
Řeší nový design, je třeba komplexně zohlednit chování animací ve výstavách.
