### ISSUE TITLE
Nejde přidávat některé typy souborů

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#248]
Navazuje na #62

Formáty by podle dřívějších informací neměly být omezeny (https://github.com/LIBCAS/INDIHU-Exhibition/issues/62#issuecomment-431037526), nejde však přidat např. doc, .docx a .pdf

**Comment by nnis** [comment]
V nové verzi na https://indihu.inqool.cz nelze přidat pdf ani docx soubor. Při procházení souborů mohu přidávat pouze obrázkové soubory png/jpg. 

Na ostré verzi https://exhibition.indihu.cz/ jsem to otestovala a pdf, a docx funguje.

**Comment by nnis** [comment]
Otestováno a pdf už jde, docx také, díky moc!
