### ISSUE TITLE
Problémy s dokumenty typu pdf v prohlížeci Mozilla Firefox

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#251]
V prohlížeci Mozilla Firefox se chybně zobrazují dokumenty pdf. V současnosti nejde ani tento typ souboru nahrát při tvorbě nové výstavy. V Google Chrome se problém nevyskytuje.

![pdf_firefox](https://user-images.githubusercontent.com/42067492/150939465-0cedac86-7a7b-44e8-8f27-59e22ebf1525.png)

**Comment by nnis** [comment]
V nové verzi (https://indihu.inqool.cz) nelze přiložit soubory docx a pdf v mozilla firefox. 

V chromu v nové verzi u výstave Akce K u obrazovky s obrázkem 1.1 jsem přidala v pořádku oba soubory, ale v náhledu se návštěvníkovi nikdy nezobrazují. 

![chromium-soubory](https://user-images.githubusercontent.com/15922183/218419092-3dc2df2c-1873-402d-9e96-70d49dbe8583.png)

**Comment by StastnyP** [comment]
Problém taktéž v Chromu při uploadu souborů

**Comment by motyc** [comment]
@nnis Můžeš to prosím vyzkoušet, zda je to už ok? Já nevím, jak se to před tím chovalo...
