### ISSUE TITLE
Nabídka "Filtr projektů" v řádku výstavy

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#26]
Nyní se zarovnává vpravo --) vznikají různé odskoky při změnách; nezarovnat nalevo? (může být problém u užších monitorů)
Nejširší varianta:
![obrazek](https://user-images.githubusercontent.com/42305589/43996545-2d5d915a-9dc5-11e8-8e86-b0b5b5dc9139.png)
Nejužší varianta:
![obrazek](https://user-images.githubusercontent.com/42305589/43996549-3a4ff7ea-9dc5-11e8-86fe-7e232a6ebe1a.png)

**Comment by rudky4** [comment]
Z obrázku nám nie je úplne jasný popis problému. Prosím o došpecifikovanie.

**Comment by malinekv** [comment]
Omlouám se, omylem jsem přiložil stejné obrázky. Nejužší varianta je tato (jde o řádek začínající "Výstavy"). Při zúžení okna prohlížeče se ale kdyžtak nabídky z menu posunou na nový řádek, čili to není nic fatálního.
![gt](https://user-images.githubusercontent.com/42305589/45206475-5fa76300-b285-11e8-85a9-08a2c81e2c0d.png)
