### ISSUE TITLE
Animace ovládacích prvků - infopoint

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#266]
Aktuální podoba ovládacích prvků např. infopoint, táhlu u před a po není vidtelné, navrhujeme přidat drobnou animaci (např. pulzování, vrtění), viz issue na Githubu pro sběr inspirace

**Comment by nnis** [comment]
Pulzování u infopointů funguje hezky. 

Táhlo u Před a po umístit doprostřed a ne na stranu, díky

**Comment by Werxis** [comment]
Myslím, že toto issue hodne súvisi (ba dokonca je duplicita pre issue #289).
