### ISSUE TITLE
Animace přiblížení

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#267]
1) Pole pro popis infopointu je úzké, rozšířit tak, aby bylo vidět více textu, ideálně celý
2) Pohyb animace je takový do oblouku, nastal tam překryv textů a textových polí u textu infopointů, když jsem neupřesnila umístění tak, že je to vlevo dole a překrývá název obrazovky a ubíhání. Vlevo dole by v možnostech vůbec nemělo být

**Comment by nnis** [comment]
1. super, teď je to v editaci vidět hezky
2. Animace je teď spíš do písmena S. Divně se to vrtí 

Umožňujeme teď dvě **pozice infopointu** nahoře, to je fajn. Nicméně ten popis není moc vidět a zároveň je to jeden řádek, takže když napíšu delší text, je to jeden dlouhý řádek, což se špatně čte. Dávám na zváženou, zda to nedat do poloviny stránky (cca tam kde je spustit výstavu, bylo by to blíže tomu detailu). 

Také mi přijde, že na detailu je to moc krátce, vlastně mohu ovlivnit pouze rychlost, kterou jedu na detail, ale nemámčas detail vnímat. Navrhuji přidat funkcionalitu "čas setrvání na detailu", abych umožnila návštěvníkovi si to prohlédnout. 

Měla bych mít možnost pouze vybrat infopointem detail a nedávat popisek (Třeba bude v komentáři)- když teď nevyplním, objeví se Vložte popis infopointu. 

Nastavení hlášky o délce je na 149 znaků, melo by být od 151. 

![pozice-infopointu](https://user-images.githubusercontent.com/15922183/205657905-2ae10419-72e3-42a0-8942-1353e3f461e2.png)

**Comment by Werxis** [comment]
- pridať políčko "doba zobrazenia obrazovky" na hlavný, prvý tab
- v tab sekvence spraviť z disabled inputu klasický text

**Comment by motyc** [comment]
- [ ] Podle mne zde nedává smysl volba "Automaticky podle mluveného slova" - může být někdy vůbec aktivní? Pokud ne, tak skrýt, případně to vypsat stejně, jako je to na tabu "Sekvence".
- [ ] Desetinná čísla či nula stále nejdou (viz https://github.com/LIBCAS/INDIHU-Exhibition/issues/267#issuecomment-1766671946)
