### ISSUE TITLE
Dokresli - zakončení

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#270]
Nelogické je vyústění minihry Dokresli, pokud je to kreativní úkol. Je problematické to správné řešení, protože kreativní úloha žádné nemá.

- [ ] U této hry změnit hlášku po dokončení.

**Comment by StastnyP** [comment]
Řešení vyžaduje změnu ve struktuře

**Comment by H-a-n-k-a** [comment]
Prosím o změnu textace: Správné řešení přepsat na "Výborně! Splnil jsi zadání a toto je výsledek".
Fotografie ze hry stírací los, ale princip je stejný.

![stiraci_los_reseni](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/377f984d-e47c-4cef-b232-bf733110c2b2)
