### ISSUE TITLE
[23] Slideshow

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#271]
Pozvolné prolnutí nefunguje, jen to proklikne

**Comment by nnis** [comment]
Prolnutí funguje. K ostatním: 
- zleva doprava: strašně rychlé, hrozně to blikne, chtělo by to subtilnější přechod. U varianty s rozmlženým pozadím to není tak hrozné. A ta první fotka tam přiletí pocitově tak nějak náhle

**Comment by nnis** [comment]
Nemám bohužel jak otestovat - při náhledu se obrazovka nenačte
![fotogalerie-indihu](https://github.com/LIBCAS/INDIHU-Exhibition/assets/15922183/0b396c23-354e-4542-94b3-fb50819ea254)

**Comment by motyc** [comment]
@nnis Je to rozbité jen ve chvíli, kdy výstava není zveřejněná. Přepni si ji na zveřejněnou a můžeš testovat. K chybě udělám nové issue.

**Comment by nnis** [comment]
OK, tak ve zveřejněné už náhled vidím, díky. Jinak mám k tomu pár postřehů: 

- čekala jsme, že nastavit čas si můžu u obrázku rovnou, nehledala bych to v záložce "Název, popis, audio". Funkce se zobrazí až potom, co zapnu manuální
- když nastavím manuálně na 3 - 7 4 vteřiny, dopočítá se mi 14 vteřin, což je fajn, ale v náhledu to nefunguje

Dala bych kompletně časování do záložky Slideshow, jinak ta funkce bude schovaná. Myslím, že tvůrci mají spíš tendenci využívat funkce přímo u té věci a ne klikat zpět, kde je to schované

**Comment by motyc** [comment]
Domluveno tak, že řádek s časováním zůstane jak na hlavní záložce, tak bude zároveň i na záložce slideshow.
