### ISSUE TITLE
Kvíz

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#275]
- [x] Nejsou další varianty, více možností, jen text, bez obrázků apod. - DEV

- [x] Nevyvážený layout - nahoře hodně prázdné, dole moc textu, odpověď vlevo dole se až překrývá s názvem obrazovky, obrázky jsou relativně malé, není to škoda? 
- [ ] "Barevné označení je fajn, nemohla by správná odpoěď udělat nějaký pohyb? Jako ta šipka u Najdi správné místo. Další možnost: kdyby po kliknutí na hotovo trochu ""poskočila"" ta 
návštěvníkem*cí vybraná odpověď? Aby nezapomněl/a, co vlastně vybral/a." - QUESTION

**Comment by StastnyP** [comment]
2) k testovní

**Comment by StastnyP** [comment]
- [ ] Ad 3) Jakmile potvrdím výběr "Hotovo", vložit animaci u vybrané odpovědi.

**Comment by nnis** [comment]
2. lepší layout, díky. Zkoušela jsem si i pohrávat se změnou velikosti okna. Když jsem si tedy okno PC zmenšila úplně na nejméně, pořád byly možnosti vedle sebe, bylo by vhodnější dát je pod sebe. je potřeba vymyslet, jak se to bude chovat v mobilní verzi. 

Všimla jsem si, že není dobře zarovnaná info prohlídka ke hře - udělá se tam na celé obrazovce scroll bar a zároveň to překryje hlavní info box tak, že se to okno překrývá (viz screenshoty)

![prohlidka-kviz2](https://user-images.githubusercontent.com/15922183/205626248-13c82ecc-2e06-4d82-8b8b-533d5c5e340b.png)
![prohlidka-kviz1](https://user-images.githubusercontent.com/15922183/205626251-fd4bb93d-b342-4aa0-9b40-73a86afcad47.png)

**Comment by nnis** [comment]
souhlas, koukala jsem na kvíz v issue #318 a je potřeba se na to víc mrknout
