### ISSUE TITLE
Nahrání souboru/pracovního listu

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#276]
Nahrání souboru z adresáře i nahrání url funguje, ale při snaze založit soubor pod tlačítko "pracovní list" se vše uloží pod "soubory k výstavě", v editaci toto nelze kontrolovat -  na úvodní obrazovce pak tlačítko "pracovní list" nijak nereaguje

**Comment by StastnyP** [comment]
Potřeboval bych ujasnit jak má tohle fungovat. V jakém případě se mají soubory ukazovat pod pracovním listem? Může vyžadovat změnu ve struktuře

**Comment by Werxis** [comment]
- pridaný selectfield na výber či daný súbor sa má vložiť pod bežný súbor k výstave alebo pod pracovný list 
- selectfield pridaný do administrácie úvodnej (START) obrazovky
- je možno pridať viacero súborov k výstave a takisto je možno pridať aj viacero pracovných listov

![add-document-dialog](https://user-images.githubusercontent.com/62404840/231843983-fc461856-680c-4415-beb6-836aa5613e0b.jpg)

**Comment by motyc** [comment]
Funkčně ok, pouze modal okno se chová divně. Na obrazovce je dostatek místa, přesto se při nahrávání souboru objevuje rolovátko, místo aby bylo modální okno dostatečně velké i pro rozbalení combo boxu (ten je navíc zdola oříznutý)

![image](https://user-images.githubusercontent.com/20186892/234060194-8622906f-a998-47dd-b4b8-f41f2c6ab517.png)

**Comment by motyc** [comment]
https://github.com/LIBCAS/INDIHU-Exhibition/issues/276#issuecomment-1520493595 - funguje dobře při přidávání nového souboru, ale při editaci to stále zlobí
