### ISSUE TITLE
Nahrávání png

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#277]
Objeví se hláška "Nahrávání souboru jeptiska-vysledek.png selhalo. Seznam podporovaných formátů je k dispozici v manuálu." podporované formáty by měly být hned vypsané, proč nejde png?

**Comment by StastnyP** [comment]
Vyzkoušel jsem a nahrát png v pořádku fungovalo, prosím o podrobnější informace k prověření

**Comment by nnis** [comment]
Funguje - otestováno jak přidáním png souboru přes Soubory, tak v obrazovce s obrázkem.
