### ISSUE TITLE
[28] Obrazovka s externím obsahem

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#279]
deaultně malé, není to responzivní a přes celou obrazovku, je třeba nějak ošetřit v nápovědě nebo prolinkem do manuálu

**Comment by Werxis** [comment]
- [ ] Pridanie checkboxu do administrácie s možnosťou škálovať na celú obrazovku

**Comment by motyc** [comment]
@Werxis Tady jen poprosím - šlo by při migraci výstav to škálování u všech existujících výstav zapnout? On si toho jinak asi nikdo nevšimne a byla by to škoda. Nevím, kam to vhodně zapsat...
