### ISSUE TITLE
Ovládání na mobilu - iOS

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#283]
Zobrazí se disclaimer, že mé zařízení není podporováno (iPhone) a nemusí fungovat správně, po kliknutí na OK se začne protáčet "loading" kolečko a nic víc se neděje. [Upravit hlášku - jsou tam navíc čárky.](https://drive.google.com/file/d/1_cPo-FASrpzq_uL_bHww3FtHJdqd8_7M/view?usp=sharing)

**Comment by Werxis** [comment]
Upravený design, nech je viacej jednotný s inými dialógmi.

![warning_dialog](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/659a8908-2edb-4114-ae52-ae699f458143)

**Comment by motyc** [comment]
@nnis @annavandasova @H-a-n-k-a @kristynahubickova Prosím, nemáte některá k dispozici zařízení Apple, abyste to otestovaly? Já bohužel nic k dispozici nemám...

**Comment by motyc** [comment]
Teď ještě procházím dokumentaci a toto se svým způsobem tluče s #28, protože v požadavcích byla i podpora pro iOS. Myslím, že tento požadavek vznikl ještě na starou verzi.

**Comment by annavandasova** [comment]
@motyc já bohužel jablka nepoužívám :/

**Comment by motyc** [comment]
Dialog odstranit, nerelevantní.

**Comment by kristynahubickova** [comment]
Poznatky z testování na iPhone/iPadu:

- velmi zdlouhavé loadování na to, že jde o výstavu, která má ani ne 2 minuty
- kvízy se na mobilu vůbec nezobrazují, ale na iPadu ano, což je zvláštní (dostanu se na ně manuálně přes kapitoly, ale ve 
výstavě se samy neukáží)
- zvuk u obrazovky se zapne v jednom z pětí případů
- infoprohlídka nejde proklikat až do konce (spadne po 2/7)
- paralax potřebuje revizi

**Comment by Werxis** [comment]
- iOs warning dialog bol odstránený

**Comment by motyc** [comment]
Sloučeno do #157
