### ISSUE TITLE
Před a po

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#289]
- [ ] Nejdou dát infopointy k obrázkům (stačí, když půjde infopointy pevně ukotvit např. podle horního obrázku a nebudou nijak reagovat na pohyb táhla; ostatní chování bude standardní; potenciální rozvoj funkcionality viz #320)

- [x] Mluvili jsme o tom, že budou jen 3 možnosti, horizontální, vertiální a postupné prolnutí, zrušit ostatní dva

- [x] Pozvolné prolnutí nefunguje

- [x] Horizontální táhlo se objeví na horní hraně, není to vidět, totéž vertikální táhlo. Obecně u těchto ovládávacích prvků je na zváženou aktuáoní béžová barva (např. infopoint), protože často není vidět na podkladové fotce

- [x] Možnost nastavit táhlo jak po vertikální, tak po horizontální ose

- [x] U téhle obrazovky bude infoprohlídka

**Comment by StastnyP** [comment]
Možnost vkládat infopointy do této obrazovky bych nepřidával (problémové na implementaci). Je to doopravdy nutné?

**Comment by motyc** [comment]
@StastnyP Aktualizován první příspěvek.

**Comment by annavandasova** [comment]
Možnost nastavení táhla ne na hranu, ale do prostoru? Myslím, že už jsme to diskutovali - takto zaniká. Viz text v úvodní info issue

**Comment by StastnyP** [comment]
- [ ] Ve výchozím stavu bude táhlo uprostřed
- [ ] Horizontálního táhla - uprostřed, nahoře (25/ 75), dole (75/25
- [ ] Vertikální - uprostřed, vlevo (25/75), vpravo (75/25)

**Comment by Werxis** [comment]
Opraveno.

**Comment by Werxis** [comment]
- Prolnutí (to čo chýba)
- Automatický prechod (aktuálne pozvolný prechod)

**Comment by motyc** [comment]
Vše kromě základního přidávání infopointů je ok. Z tohoto bodu jsem udělal nové issue #349 a toto zavírám.
