### ISSUE TITLE
Přechody mezi obrazovkami

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#290]
- [ ] "Když si zapnu na jedné obrazovce textové pole, při přechodu na další ho mám také otevřené. Chceme to? Mně to asi rozčilovalo, protože mi to kazilo výhled, takže to je otázka.
 Co to udělat tak, že po několika opětovných rozkliknutí (např 4x) textové pole se tam prostě bude ukazovat."

- [x] Šipka zpět nejde zpět ale na spustit výstavu, při kliknutí na šipku zpět je to OK, dopředu to funguje

**Comment by nnis** [comment]
Šipka zpět funguje správně

**Comment by motyc** [comment]
- [ ] Šipka zpět je teď schovaná za textovým polem, takže nejde použít, když je otevřené.
