### ISSUE TITLE
Spustit výstavu 

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#294]
Na enter?

**Comment by nnis** [comment]
Dobrý nápad, ale nefunguje. Teď funguje jen šipka doprava na klávesnici. Říkám si, jestli by nešlo pustit výstavu na Enter i na mezerník?

**Comment by Werxis** [comment]
Pridal som spúštanie výstavy na enter a aj na medzerník.

**Comment by motyc** [comment]
Mezerník nefunguje (jen to poskočí ale přehrávání se nerozjede). Enter je ok.
