### ISSUE TITLE
Stírací los

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#295]
Pokyn vymaž obrázek, problémy se zadáním, maže se vrstva do kraje, i když je obrázek zúžený, chceme to? Chceme to zužovat?

- [x] Upravit, abychom mazali jen danou část obrázku, nikoliv okraje.

**Comment by motyc** [comment]
Stále se to nechová ideálně. Když normálně mažu, působí to ok, ale jakmile přetáhnu do nástrojové lišty prohlížeče, stane se toto:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/16185e41-7af6-490d-a352-69e435040082)

**Comment by H-a-n-k-a** [comment]
Stane se to vždy, pokud gumou přejedu přes horní či spodní okraj obrazovky - viz scrennshoty. Do stran to opravdu nemaže.

![stiraci_los_piombo](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/9f3c8f36-fd28-4b9b-bdbb-67517c4526b6)
![reseni_stiraci_los](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/074ad959-5c40-4669-a20e-4bb83d96d6b8)
![stiraci_los_bug](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/4153b3e4-98f2-45a7-bac4-623e96ea7ff1)

**Comment by H-a-n-k-a** [comment]
Ještě i zde prosím přepsat textaci závěru této hry.
Přepsat Správné řešení na "Výborně! Splnil jsi zadání a toto je výsledek".

![stiraci_los_reseni](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/74ea8640-4047-4092-b7f8-40ba40a77afd)
