### ISSUE TITLE
Textové pole

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#296]
Aktivní je jen ikonka íčko, proč ne celé pole? proč také nejde zavřít opětovným kliknutím kdekoli v poli?

**Comment by nnis** [comment]
Už je aktivní celé pole. Funguje i klávesa ESC, zavření je na křížek. 

problém je, že v textovém poli se automatický znásobuje text (viz obr editace a náhledu) 

![textove-pole-editace](https://user-images.githubusercontent.com/15922183/205676251-67aa0811-b132-49d8-8f5c-296d230d2d7b.png)


![textove-pole](https://user-images.githubusercontent.com/15922183/205675805-3b4806ea-94bc-478a-bd71-de8d435012ad.png)

**Comment by Werxis** [comment]
K tomu znásobenému textu už bola vytvorená nová issue: https://github.com/LIBCAS/INDIHU-Exhibition/issues/321. Tak si z tohoto dôvodu dovolím túto issue už uzavrieť.
