### ISSUE TITLE
URL výstavy

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#299]
píšeme URL malýma, nemělo by to být velkýma, URL adresa nejde zkopírovat z editace a není na jednom řádku

**Comment by StastnyP** [comment]
zkopírovat URL mi šlo, je potřeba potáhnout trochu dál, editace je rozdělena jelikož je potřeba zachovat prefix URL needitovatelný

**Comment by motyc** [comment]
- [ ] přidat tlačítko "Kopírovat" pro zkopírování celé URL výstavy
- [ ] zajistit, aby byl prefix celý na jednom řádku (patrně zlobí v Mozille):
![image](https://user-images.githubusercontent.com/20186892/211822624-1e864fdb-1546-4743-9eaa-a50af50e2fe6.png)
