### ISSUE TITLE
Úvod do kapitoly

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#300]
- [x] Animace je strašně rychlá, když mám krátký čas. Úvody do kapitol nemůžu nastavit na minutu, aby byla animace pomalejší, protože to žádoucí

- [x] nezměnění styl písma (okraje písma) - font i podbarvení je stejné.

- [x] Po rozkliknutí íčka se u úvodu kapitoly objeví textové pole, ale jen s názvem, neobsahuje podnázev a obsahuje text "obrazovka neobsahuje žádný text". A to i v případě, že vyplním dluhý text, tak v textovém poli není, ale je pod názvem kapitoly na několik řádků.

**Comment by nnis** [comment]
- rychlost animace mi přijde OK (co ostatním?)
- styl písma, asi OK, nevím, k čemu se to vztahovalo
- asi ok

**Comment by nnis** [comment]
Ověřit rychlost animace

**Comment by nnis** [comment]
- rychlost animace dobrá
- podbarvení a okraj odstraněny, ale čitelnost je slabší (viz screenshot) 
- když nevyplním podtitulek, nic se nezobrazí, to je ok 
- podtitulek je ale hodně široký, pokud je to dlouhé a špatně se to čte
![uvod-do-kapitoly2](https://user-images.githubusercontent.com/15922183/205701975-8a8c6b29-9500-4ad4-ba62-f4018eadec3d.png)




navrhuji zvětšit písmo a udělat možnost tmavší varianty kvůli čitelnosti

**Comment by motyc** [comment]
Funguje, nicméně na schůzce dohodnuto, že je třeba zachovat i možnost zapnout/vypnout zobrazení halo kolem textu. To by mělo být světlé pro tmavý text a tmavé pro světlý text.

**Comment by motyc** [comment]
- [ ] Chybí oprava podle @nnis tj. úprava max. šířky textu nadpisu a podnadpisu (např. na 50 % stránky - 40 by asi bylo málo).
- [ ] Efekt textu -> Zvýraznění textu
- [ ] Zvýraznění textu stále funguje jen jako stín, tj. zobrazuje se vpravo a dole. Je třeba zobrazovat ze všech stran, protože text stále snadno splývá s pozadím tam, kde ohraničení chybí.

**Comment by motyc** [comment]
Úpravy jsou skvělé. Jedinou drobností je, že:
- [ ] podnadpis je zalamován do bloku, nikoli na střed, což působí zvláštně
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/10eecef9-4c6a-405e-9a2a-5a93f3c85cef)
