### ISSUE TITLE
Úvod výstavy

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#301]
- [x] Když je text perexu delší, uřízne se Text "Kapitoly výstavy"
- [x] levý box vyjíždí nad úroveň pravého vyskočeného boxu a tlačítka spustit - zarovnat do jedné hladiny

**Comment by nnis** [comment]
Zarovnání funguje super. Nicméně nevím, jsetli to není zbytečně vysoké a jestli by nemělo být písmo v perexu větším písmem (jako je tomu u článků v médiích. 
Při testování jsem tam dala text dlouhý 1574 znaků, předpokládaná délka mluveného slova: 2 min 12 s (fakt dlouhý) a je tam pořád strašně moc místa, viz screenshot. Naznačila jsem, že by to mohlo být tak klidně do půlky, možná klidně do 40 % výšky vč. většího písma: 

![uvod-vyjete-boxy](https://user-images.githubusercontent.com/15922183/205678007-48433dcb-2349-4f5b-a415-bff3f0f46828.png)

Problém s překrytím tlačítka Kapitoly výstavy zmizel. Vejde se tam pohodlně 3200 znaků, což je délka textu 4 a půl minuty

**Comment by Werxis** [comment]
Upravené.

![start-screen-perex](https://user-images.githubusercontent.com/62404840/231844726-9374ae4a-b31d-4bda-824c-1ce5225e440f.jpg)
