### ISSUE TITLE
Závěr výstavy

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#303]
- [x] Neobsahuje obrázek, dříve se generoval z úvodního obrázku, není zřejmé, kde to v editaci nastavím
- [x] Když neobsahuje soubory ke stažení, nemělo by to tam být, ne všichni to tam budou mít
- [x] Proč je pod autory výstavy "test" Odkud se bere? 
- [x] Není vygenerovaný obrázek

**Comment by nnis** [comment]
- obrázek jde nahrát po kliknutí na obrazovku
- když jsem smazala soubory k výstavě, na Úvodu furt zůstaly a na závěrečné obrazovce se objevila 0

![soubory-k-vystave](https://user-images.githubusercontent.com/15922183/205687996-65becf05-4ebe-427c-ad1a-ee75090d0616.png)

- test tam je pořád
![zaver-vystavy](https://user-images.githubusercontent.com/15922183/205688483-4b64114f-a66c-44e9-ae00-ce5cc8e8be83.png)

**Comment by motyc** [comment]
- [ ] Soubory k výstavě - zobrazují se i ty kapitoly, u kterých není žádný soubor ke stažení:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/9fb27cc4-1927-4372-9da4-a4eb794b30a6)

Jinak ok
