### ISSUE TITLE
Zvuk

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#305]
"Zvuk nefunguje u obrazovky ""Úvod do kapitoly"", na dalších obrazovkách funguje. 
Mně teda nefungoval u poloviny obrazovek, nevím, jestli to byl záměr? Pokud to byl záměr a některé obrazovky zvuk nemají, tak se objevuje ikona zvuku i tam, kde žádný zvuk není a je to pro návštěvníka matoucí."

**Comment by Werxis** [comment]
Duplicitné issue, novovytvorené bolo: https://github.com/LIBCAS/INDIHU-Exhibition/issues/327
