### ISSUE TITLE
Prohození interakčních tlačítek

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#308]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/89975021/203555844-d90a1eb4-4c84-4140-9efc-21fd1074c374.png">

- [x] Přesunout tlačítka Hotovo a Zahrát znovu do pravé části obrazovky. 
Prohodit také pořadí: 
1. Interakční tlačítko - kreslení, guma atd.. 
2. Zahrát Znovu , Hotovo
3. Pauznutí, Kapitoly

**Comment by motyc** [comment]
Finální zadání:
- tlačítka se přesunou doprava (pořadí bude zrcadlově)
- tlačítka Hotovo a Zahrát znovu
-- se zredukují pouze na ikony (bez textu) - vysvětlení řeší úvodní infoprohlídka
-- tato dvě tlačítka se zvýrazní obarvením do stejného stylu, jako se používá např. pro "Spustit výstavu" na úvodní obrazovce

**Comment by Werxis** [comment]
Takže 
- tlačítka Hotovo a Zahrát znovu ostanú vľavo tam, kde momentálne sú, ale bez textu + pridať k nim infoprohlídku + ofarbenie
- tlačítka play / pause, audio atď.. už sú na pravej strane
- čo s interakčnými tlačítkami ? ostanú na ľavej strane vedľa tlačítok Hotovo a Zahrát znovu alebo pôjdu doprava k tlačítkam ako play / pause, audio, atď ?

**Comment by motyc** [comment]
Pokud si dobře vzpomínám, tak by to mělo být tak, že se VŠECHNA tlačítka přemístí doprava, jen se tam přemístí zrcadlově (v opačném pořadí), tj. tak, aby první byla tlačítka pro interakci, pak zahrát znovu, pak hotovo a potom standardní tlačítka. Vlevo by nic zůstávat nemělo.
