### ISSUE TITLE
Záložky - oblibené obrazovky

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#314]
- v pravém rohu nahoře (trojúhelník) 
aktivní - plná ikona
neaktivní - prázdná ikona
Na mobilní verzi - skrývat při neaktivitě
V závěru výstavy zobrazit uložené záložky (aktivní)

**Comment by nnis** [comment]
Jedná se o featuru pro online návštěvníky, což z popisu výše není úplně zřejmé - jde o to, aby se mohli podobně jako na Instagramu návštěvníci měli památku na výstavu. 
Chceme, aby se stahovaly obrazovky rovnou a ne až  ze závěrečné obrazovky, protože by bylo liché předpokládat, že všichni dojdou až na konec. 

Současně funkce funguje u Dokresli, ale pod ikonou stáhnout dole

**Comment by nnis** [comment]
**Aktualizované a finalizované zadání**

- [ ]  Přidat na každou obrazovku ikonu pro stažení do pravého horního rohu. Návrhy na ikony: 

- https://www.flaticon.com/free-icon/download_18281446?term=bookmark+download&page=1&position=28&origin=search&related_id=18281446
- https://www.flaticon.com/free-icon/download_18281446?term=bookmark+download&page=1&position=28&origin=search&related_id=18281446 

<img width="353" height="349" alt="Image" src="https://github.com/user-attachments/assets/7b73c373-4c24-4aa6-b530-e9165e354f4f" />
<img width="451" height="382" alt="Image" src="https://github.com/user-attachments/assets/4c3d09db-1b95-4765-aaa1-7c238dbcd2be" />

- [ ]  Funkce bude stejná jako u stažení a ikony s šipkou dolů u hry Dokresli. Tzn. - vytvoří se screenshot aktuálního zobrazení stránky, která se stáhne buď do galerie v případě telefonu, nebo do downloads (nebo jinam, jak má nastaveno online návštěvník). 
- [ ]  Jedná se pouze o obrázek bez dalších informací nebo linků. Pokud bude mít online návštěvník právě otevřené textové pole, screenshot to bude respektovat. 
- [ ] součástí issue je i zrušení ikony s šipkou dolů mezi ikonami pro kreslení u obrazovky Dokresli 
- [ ]  název staženého souboru: virtual_exhibition.png 
- [ ]  Screenshoty se NEBUDOU zobrazovat na závěrečné obrazovce, jedná se pouze o funkci na úrovní jedné (každé) obrazovky bez dalších návazností. Obrazovka závěr výstavy proto zůstává beze změn.
