### ISSUE TITLE
Infoprohlídka

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#315]
- [x] Informace a nápověda k ovládacím prvkům, jedná se o popisek, jakým způsobem s ovládacími prvky má uživatel pracovat
- [x] Uživatel bude moci uzavřít konkrétní infoprohlídku, nebo všechny inforpohlídky pro celou prohlídku.

- [x] Zobrazovat vždy novým uživatelům

- [x] Při zobrazení infoprohlídky se zvýrazní ovládací prvek + infoprohlídka. Na pozadí nebo další obrazovky se vloží tmavší filtr.

- [ ] Texty tvoří tvůrci (Administrátoři) - přidat v administraci kolonky pro překlady.

**Comment by Werxis** [comment]
Je tam ešte nejaký požiadavok na texty pro preklady do administrácie ale momentálne sa texty berú z dodaných súborov ?
A ešte pripomínam, že som dorábal do infoprohlídky aj klávesové ovládanie a do budúcna sa tam teda asi objaví aj tlačítko lupy (ako sme sa bavili na schôdzke z 11.07), tak možno budete chcieť dodať vlastné texty

**Comment by motyc** [comment]
Funguje ok. Textace dořešíme standardně v locales a případné ladění budeme řešit jako samostatná issue.
