### ISSUE TITLE
Klávesové ovládání

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#316]
- [x] ESC - zavře vyskakovací okno (u infopointů, infoprohlídky, ...)

- [x] šipka doleva / doprava- přejde na předchozí / následující obrazovku

- [x] mezerník - pause celé výstavy v případě časované obrazovky nebo obrazovky s videem se také pozastaví časovač

- [x] M - Mute - ztišení zvuku

- [x] Enter - spustit výstavu

**Comment by StastnyP** [comment]
- [ ] Zmínit ovládací zkratky i v infoprohlídce

**Comment by motyc** [comment]
- [ ] bug v chování mezerníku - když použiji mezerník po tom, co jsem ručně klikal na šipky pro listování obrazovkami, výstava se na mezerník zároveň posune, jako bych klikl na danou šipku

**Comment by Werxis** [comment]
Chcel by som sa opýtať, že či problém opísaný v predošlom komentári stále pretrváva ? Nedokázal som ho totiž nasimulovať. Medzerník sa mi javil, že aj po kliknutí na šípky, že je v poriadku.
