### ISSUE TITLE
Loga a vodoznaky

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#317]
- [x] Uživatel si bude moci nastavovat sám loga a vodoznak pro výstavu.

- [x] Zvolit si bude moci pouze logo / vodoznak. Nebude mít moci vložit obě najednou do výstavy.

- [x] umístění loga / vodoznaku - nahoře vpravo vlevo, dole vlevo

- [ ] Nastavená barva výstavy podbarví fotografii (shadow filtr nad obrázek)

**Comment by Werxis** [comment]
- v podstate silno súvisí s issue #313
