### ISSUE TITLE
[N2] Hra - Kvíz

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#318]
- [x] Možnost pracovat jak s obrázky, tak i pouze s textem (text v boxu podle velikosti roztahovat, aby nebylo nutné v boxu scrollovat)

- [x] V případě radiobuttonu - pouze jedna správná odpověď - do infoboxu propisovat informaci, že je pouze jedna správná odpověď.

- [ ] V případě checkboxu - více správných odpovědí - do infoboxu propisovat informaci, že je více správných odpovědí.

- [x] Po vyhodnocení označovat správné / špatně zvolené odpovědi.

- [x] Při najetí na obrázek / text se odpověď zvýrazní.

- [x] Při označení odpovědi se odpověď taktéž zvýrazní.

- [x] Maximální počet možností je 8 (2 řady po 4).

- [x] Při lichém počtu dávat více obrázků nahoru, 3 nahoře, 2 dole

- [x] možnost umístit infobox a infopoint, při jejich nevyplnění se na obrazovce nezobrazí (viz Figma)

- [ ] Po vyhodnocení - PNG podbarvit celý obrázek, v Případě JPEG ohraničit obrázek

**Comment by Werxis** [comment]
- ešte sa objavil nápad pridať podporu v administrácii pre možnosť zmeny poradia odpovedí

**Comment by Werxis** [comment]
- pridaná podpora pre možnosť zmeny poradia odpovedí kvízu v administrácii

**Comment by nnis** [comment]
jsem moc ráda, že máme nové funkce, ale je to možná pro mě těžší na ovládání. Co mě zmátlo: 

- šipky (zobáčky vpravo i vlevo), které vypadají stejně, ale každá dělá něco jiného. viz obr: 

![kviz-posuv](https://github.com/LIBCAS/INDIHU-Exhibition/assets/15922183/6bfea65e-40b1-4099-a18b-d20c0f690d4d)

- dále mi není jasné, kde ukládám tu odpověď, kteoru už mám, klikla jsem dole na uložto, což asi není chyba, ale přijde mi to nějaký divný

**Comment by motyc** [comment]
Závěr je, že:
- ikona pro smazání dopovědi se změní na koš
- při zavřené kartě se nebude zobrazovat šipka vpravo
- při otevřené kartě se v rohu zobrazí křížek (místo šipky)

**Comment by kristynahubickova** [comment]
dotaz: pracuje se na dalších variantách kvízu? (#337)

**Comment by motyc** [comment]
Chování je myslím nyní úplně jasné a příjemné kromě jediného - když posouvám odpovědi, vlastně se opticky nic nestane, protože označení "Varianta XY" není fixní, ale dynamické. V takové případě by bylo vhodné zobrazovat vedle označení i text odpovědi, ať je jasné, o kterou jde i při zabalené kartě. Rozložení by pak bylo zhruba takovéto:

![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/d319e6c2-df7e-4d93-b3a5-f5a62495b25d)

Kromě toho je k zapracování dnes diskutovaný [komentář Kristýny](https://github.com/LIBCAS/INDIHU-Exhibition/issues/318#issuecomment-1758019756)

**Comment by Werxis** [comment]
- zapracovaný podnet ohľadom doplnenia možnosti o zobrazení textu odpovedi až po vyhodnotení kvízu (pre formu kvízu v móde text aj obrázok zároveň)

**Comment by motyc** [comment]
- [ ] Testuji zde https://exhibition-test.indihu.cz/expo/9b5c54c8-a92e-4ad1-a58b-db5deab83d1b/screen/game-options/1-6/answers a nikde nevidím možnost jak tu volbu přepnout
- [ ] Zapracovat komentář https://github.com/LIBCAS/INDIHU-Exhibition/issues/318#issuecomment-1766689655

**Comment by Werxis** [comment]
Prvý bod by mal byť opravený

**Comment by Werxis** [comment]
- [ ] Možnosť editácie textu Varianty, užívateľ si bude môcť označiť vlastným textom jednotlivé odpovede, tento text sa nebude nikde inde zobrazovať

**Comment by Werxis** [comment]
Zapracovaný už aj posledný bod - možnosť označiť si variantu vlastným textom.
