### ISSUE TITLE
Dynamické infopointy před a po

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#320]
Na obrazovce před a po by mohly být infopointy vázány na konkrétní vrstvy a při pohybu táhlem se automaticky zobrazovat/skrývat.

**Comment by Werxis** [comment]
Oba vyššie spomínané body sú zapracované.

**Comment by motyc** [comment]
- [ ] Když v administraci najedu na infopoint u jednoho obrázku, popisek se zobrazí u obou a navíc ve druhém případě na špatném místě:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/34523ece-7623-4ed8-9bfc-b089833bb003)

- [ ] Pokud zvolím "Prolnutí", infopointy se vůbec nezobrazí. Nejlépe se s tím vypořádejme tak, že pro tuto volbu bude použitá jen jedna sada (z prvního obrázku). Druhá by pak měl při této volbě administraci zašednout, nebo se skrýt (nebo něco podobného).

**Comment by Werxis** [comment]
Vyššie opísané body by mali byť zapracované 
- čo sa týka druhého bodu, teda obrazovka s animáciou "Prolnutí", nebo Fade out, tak som sa s tým skúsil trochu pohrať a napadlo ma nasledovné: prvých 25% času obrazovky sa zobrazia infopointy prvého obrázku... a posledných 25% (75 až 100%) času obrazovky sa zobrazia infopointy druhého obrázku

Príklad: Ak je obrazovka nastavená na 12 sekúnd
    - potom prvé 3 sekundy sa zobrazia infopointy prvého obrázku
    - potom je 6 sekúnd bez infopointov
    - potom posledné 3 sekundy sa zobrazia infopointy druhého obrázku

Ono je to vlastne aj z toho dôvodu.. že napr. počas tých prvých a posledných 3s sa obrázky medzi sebou tak prelínajú, že by nebolo ani jednoduché jednoznačne určiť, že ktorý infopoint patrí ku ktorému obrázku.
