### ISSUE TITLE
Opakující se popisný text

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#321]
https://exhibition-test.indihu.cz/view/100letARU/0/1

Po rozkliknutí textového popisu se text v boxu nekonečně opakuje:
![image](https://user-images.githubusercontent.com/20186892/219692924-44bcdd9c-1fab-44bc-a4bb-ab43c44199c9.png)

**Comment by Werxis** [comment]
Opravil som.
