### ISSUE TITLE
Při pauze si nejde prohlédnout další obrázky v rámci galerie

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#322]
https://exhibition-test.indihu.cz/view/100letARU/1/1

Nově když výstavu zastavím, tak nemám možnost v rámci obrazovky projít všechen obsah, protože mi k tomu chybí nástroje. Dříve např. fotogalerie šla prolistovat, nyní to nejde. Možná se to dotkne i jiných obrazovek.

**Comment by StastnyP** [comment]
- [ ] Využijeme progressbar v info, kde budeme přepínat jednotlivé obrazovky (forma teček / obrázků).
