### ISSUE TITLE
U videí zmizela možnost posuvu

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#326]
V původní verzi bylo možné v textovém režimu posouvat videa. Nyní tato možnost úplně zmizela.

![image](https://user-images.githubusercontent.com/20186892/219695720-05339e89-cd2c-4099-8e16-ba859ecaa3a2.png)

**Comment by StastnyP** [comment]
- [ ] Timelinu pro video přidat do textového pole vlevo dole (kde již současně máme progressbar).
