### ISSUE TITLE
Vůbec se nepřehrává zvuk kapitoly

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#327]
https://exhibition-test.indihu.cz/view/100letARU/0/0

Lze testovat proti originálu na https://exhibition.indihu.cz/view/100letARU/. Podkres kapitoly zmizel.

**Comment by motyc** [comment]
Nyní to už sice hraje, ale nefunguje pauzování. Když dám pauzu na obrazovce, zvuk kapitoly se nezastaví.

**Comment by Werxis** [comment]
Tento konkrétny prípad pri pauzovaní by mal byť vyriešený, ale poprosím overiť, že či zvuk kapitoly sa chová vo všetkých prípadoch podľa predstáv.

**Comment by Werxis** [comment]
Predchádzajúce dva body opravené
