### ISSUE TITLE
Paralaxy jsou úplně rozbité

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#328]
https://exhibition-test.indihu.cz/view/100letARU/1/2

Paralaxy jsou nefunkční. Nevím, zda to nemůže být např. v tom, že vrstvy jsou nad sebou ve špatném pořadí.

**Comment by Werxis** [comment]
Upraveno, poprosím otestovať :)

**Comment by motyc** [comment]
Už to funguje, jen se myslím poměrně o hodně zvýšila rychlost posunu, což má také nezamýšlené důsledky. Upravit tak, aby odpovídalo dřívějšímu nastavení.
