### ISSUE TITLE
Posun infopointů

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#329]
Při migraci došlo k posunu infopointů oproti originálu. Srov:
https://exhibition.indihu.cz/view/100letARU/2/2
https://exhibition-test.indihu.cz/view/100letARU/2/2

**Comment by Werxis** [comment]
Akurát tesne po Vás som nasadzoval zmeny, ktoré riešili aj posun infopointov - riešili sme to aj na schôdzke 11.07, tak označujem znova na test, v prípade problémov sa na to opät mrkneme :)

**Comment by motyc** [comment]
- [ ] Při procházení této obrazovky https://exhibition-test.indihu.cz/view/100letARU/2/1 se při přechodu ze druhého na třetí obrázek objeví divný infopoint, který poté zase zmizí. Nenašel jsem ho ale ani v administraci, ani v původní výstavě:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/fa9b8763-2dcc-40a8-a704-4de155b16651)
- [ ] Opravu posunu nedokážu nyní posoudit, protože infopointy jsou oproti produkci posunuté všude, ale to je způsobeno nějakou chybou při posledních updatech, kdy došlo k vynulování pozice všech infopointů. Testovat to tedy půjde jedině pokud bude provedena nová migrace dat z produkce.

**Comment by motyc** [comment]
Ještě doplňuji, že se to chová opravdu divně. Přišel jsem teď na https://exhibition-test.indihu.cz/view/100letARU/2/2?preview=true a zobrazilo se toto:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/bf71d93d-7401-4eca-ba92-b3fa28903967)

Následně jsem upravil barvu infopointu a otevřel znovu náhled, a výsledkem je toto (přitom jsem však pozici cíleně nijak neměnil):
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/9d150f97-2d31-44b1-9cff-65b49274dd97)

**Comment by Werxis** [comment]
U infopointov je divné chovanie spôsobené aj tým, že infopointy sa zobrazujú posunuté už aj v editačnom prostredí, demonštrácia na obrázkoch nižšie.

![infopoints_outside_1](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/4ac510c7-54af-4531-bb07-e92c585110be)

![infopoints_outside_2](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/088eac8e-4584-4006-a9c0-0d9cc392dfbb)

Z obrázku vidno, že 3 infopointy sú umiestnené kompletne mimo obrázku
- to je spôsobené tým, že obrazovke už dôjdu posunuté súradnice (súradnice, ktoré ukazujú za obrázok), ja s tým moc neviem spraviť, pretože neviem súradnice a ani ich neviem žiadnym spôsobom dopočítať, kde boli infopointy predtým korektne umiestnené
- ako riešenie som aspoň kompletne upravil ten obrázkový box cez ktorý sa infopointy zobrazujú aj umiestňujú + som pridal kontrolu do každej obrazovky, ktorá používa infopointy, aby ak infopoint je zobrazený mimo obrázku, aby sa teda nezobrazil, kedže vlastne z logiky veci na obrázku byť podľa editačného prostredia ani nemá

Keď sa infopointy manuálne chytia a pomaly sa presunú (alebo vymažú a znova nastavia), tak sa infopointy zobrazujú správne. 

![infopoints_outside_3](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/e2cc0c7e-37c4-44fb-bd2a-2461242def42)

**Comment by motyc** [comment]
@Werxis To je samozřejmě fajn pomoc, ale není to úplně řešení, protože problém tedy zjevně bude někde v procesu migrace starých dat. Je mi jasné, že to nejde doplňovat zpětně, ale měli bychom v ideálním případě zajistit, že vše bude správně sedět jako v původní verzi, jinak to tiž vše budou muset autoři opravovat, což není úplně únosné. Asi bychom to měli zítra probrat na schůzce.

**Comment by Werxis** [comment]
Malo by byť vyriešené.
