### ISSUE TITLE
Chybí popisky ve fotogalerii

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#330]
https://exhibition-test.indihu.cz/view/100letARU/3/1
https://exhibition.indihu.cz/view/100letARU/3/1

V migrované verzi se nezobrazují popisky jednotlivých foto.

**Comment by nnis** [comment]
Myslíš popisky v textové verzi, tedy v textovém poli nebo v infopointech? To z toho není úplně jasné. 

V infopointech stále zůstává název Infopoint, když nevyplním název a to bude u všech migrovaných výstav, takže je potřeba tam mít prázdno, když to tam nebude a pak v tom případě pozor, aby tam nebylo moc velké prázdné místo a ošetřit zarovnání. 


![infopointy](https://user-images.githubusercontent.com/15922183/236507107-448933fd-c391-43af-be8b-f232695a4cab.png)

**Comment by motyc** [comment]
@nnis Měl jsem tuším na mysli popisky v infopointech. Když jsem to psal, tak se tam nic nezobrazovalo. Teď je to stále trochu ošidné - v původní verzi je rozevřený infopoint, v nové je úplně jinde a zavřený, takže to podle nefunguje podle původního záměru autora.
