### ISSUE TITLE
Progress bar - problémy se zobrazením a ovládáním

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#336]
- [x] náhled úvodní obrazovky se zasouvá úplně mimo zobrazení:
![image](https://user-images.githubusercontent.com/20186892/234070820-a140da61-8c88-4d4f-b118-ccc9ccf32c55.png)

- [x] u náhledů není nastaveno žádné zalamování a vypadá to velice divně; je to třeba nějak graficky pojednat:
![image](https://user-images.githubusercontent.com/20186892/234071120-9a31f0ed-667f-464a-871a-2c417f9f2cf1.png)

- [ ] uživateli není úplně jasné, na co má klikat; ukazatel myši není při najetí na osu vidět (je víceméně mimo obrazovku), takže není jasné, kdy jsem na aktivním prvku; aktivní prvky jsou ve skutečnosti jen ty body a většina prostoru osy je neaktivní; bude se řešit automatickým zdvojnásobením výšky lišty při najetí myší

- [x] špatná viditelnost progress baru proti některým podkladům (pokud je pozadí bílé, není vůbec jasné, co vlastně platí:
![image](https://user-images.githubusercontent.com/20186892/234071865-95e45022-2242-43bf-98a3-1c226b309fbb.png)

**Comment by Werxis** [comment]
- [ ] pri najetí myši na progressbar (on hover), animáciou zdvojnásobiť výšku progressbaru

**Comment by motyc** [comment]
Kromě potřeby implementovat https://github.com/LIBCAS/INDIHU-Exhibition/issues/336#issuecomment-1630392428 vše ok.
