### ISSUE TITLE
Tagování výstavy

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#341]

**Comment by motyc** [comment]
Funguje v pořádku, jen bych na schůzce probral:
- vhodné řazení tagů ve výběru (abecedně?)
- možnost přidat více tematických tagů než jeden (max. 3?)

**Comment by motyc** [comment]
@Werxis Ano, ale tady šlo primárně o řazení tagů při jejich výběru v administraci. Pro výpis to ale platí, jak říkáte.

**Comment by Werxis** [comment]
Vyššie opísané body by mali byť zapracované
