### ISSUE TITLE
[34] Fotogalerie

### ISSUE THREAD

**Issue by StastnyP** [LIBCAS/INDIHU-Exhibition#342]
- [x] Vytvořit nový typ obrazovky **Fotogalerie**

**Comment by motyc** [comment]
- [ ] Doplnit možnost přidání popisku k jednotlivým foto
- [ ] Zvýšit maximální počet položek na řádku ze 3 na 4

**Comment by Werxis** [comment]
Začnem od konca, druhým bodom o zvýšenie počtu fotiek na jednom riadku. Momentálne sa to chová tak, že to zobrazenie je rozdelené do dvoch spôsobov:

1. Počet fotiek je menší rovný 8 (<=8)
    - na malých obrazovkách od 0px do 767 px je **jedna** fotka na riadku
    - na stredných obrazovkách od 768px do 1279px sú **dve** fotky na riadku
    - na veľkých obrazovkách od 1280px sú **tri** fotky na riadku
 
2. Počet fotiek je väčši ako 8 (>8), tu je to trochu pestrejšie
     - na malých obrazovkách od 0px do 767 px je **jedna** fotka na riadku
     - od 768px do 1023px sú **dve** fotky na riadku
     - od 1024px do 1279px sú **tri** fotky na riadku
     - od 1280px sú už **štyri** fotky na riadku

Otázkou je či chceme takéto delenie, či treba pozmeniť limit 8 fotiek alebo by ste chceli layout ešte nejako ináč pomeniť. Celé toto delenie bolo vlastne inšpirované aj figmou, kde layout pri menšom počte fotiek vyzeral ináč ako pri väčšom počte.

---

Čo sa týka prvej pripomienky, pridanie popisku k jednotlivým fotkám, máte nejakú predstavu ? Mňa ešte napadlo, že by som relatívne ľahko mohol pridať nad otvorenú fotku takú lištu s "nástrojmi", kde by napr. na ľavej strane boli ikony tlačítok na zoom (mohlo by to byť zrejmešie pre užívateľa, že fotogaléria podporuje zoomovanie, keď uvidí aj tlačítko) a na pravej ikona zavretia. 

A ku tejto lište by sa ešte mohlo pridať tlačítko ikony, ktorá by otvárala a zatvárala popis k fotke. Teda by popis bolo možné užívateľom otvoriť aj zatvoriť, alebo by ste chceli popis fotky nutne stále pri fotke, napr. pod fotku?

**Comment by motyc** [comment]
@Werxis První části úplně nerozumím, proč se to váže k limitu osm foto, když u podmínky <=8 se pracuje max se šesti foto. Není v tom nějaká chyba? V podstatě by myslím stačilo zachovat variantu 2 pro všechny případy (ta podmínka úplně nedává smysl).

Ad popisek - Navržené řešení s lištou a ovládacími prvky mi přijde dobré. Bylo by ještě super, kdyby tam byl nějaký fade-out při delším zastavení myši, aby byla i varianta, kdy na foto nic neruší (ovládací prvky jsou skryté).

**Comment by Werxis** [comment]
@motyc Tá podmienka vznikla pri myšlienke, že aby sa layout pri nižšom počte fotiek choval trošku ináč. Preberali sme to myslím aj na jednej schôdzke a to číslo 8 bolo zvolené mnou v podstate náhodne a môžem kedykoľvek zmeniť. Prikladám aj screenshoty z figmy, že ako som to pochopil.

![photo_4](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/b52d3587-69b8-4754-bd75-3621a8b9b6b2)

![photo_more](https://github.com/LIBCAS/INDIHU-Exhibition/assets/62404840/e166a909-e443-414d-ba25-141ea0f5d828)

Príklad:
- aktuálnej nasadenej TEST verzii, keď bude na obrazovke 8 fotiek (alebo aj menej), tak jeden riadok bude obsahovať 3 fotky
- keď sa pridá jedna fotka, teda obrazovka bude obsahovať 9 fotiek, tak jeden riadok už bude obsahovať 4 fotky

Chápem, že limit 6 fotiek v danom prípade by dával väčší zmysel, otázkou je teda či mám tieto dva módy nechať alebo to vždy zlúčiť do jedného, aby boli na obrazovke 4 fotky v jednej rade (s predpokladom, že je dostatočne veľká obrazovka).

---

Lištu s ovládacími prvkami sa teda pokúsim pridať. A ten popisok k jednotlivej fotografii mám dať vždy zobrazený alebo si to užívateľ bude môcť aj manuálne vypnúť zapnúť jedným z tlačítok v lište ?

**Comment by motyc** [comment]
@Werxis Ad počet - asi bych nechal rozhodnutí na příští schůzku, co řeknou ostatní. Každopádně bych ten limit teď jen snížil na 6, aby to dávalo logiku a pak se ještě dohodneme, zda tu první variantu nevypustit.

Ad lišta - zapnout/vypnout; já jsem to bral tak, že to potvrzuji celé navržené :)

**Comment by Werxis** [comment]
- limit snížený na 6
- pridaná lišta s akciami lupa a otvorenie popisu fotky
- lišta obsahuje aj fade out animáciu
- v administrácii ku každej fotke pridané políčka pre nadpis fotky a popis fotky
- ak fotka obsahuje popis.. tak sa v lište ukáže ikona "popisu", ktorá otvorí dialóg

**Comment by motyc** [comment]
Je to pěkné, už jen úplné drobnosti:
- [ ] u otevřené první foto nezobrazovat šipku vlevo, u poslední pak vpravo
- [ ] fade-out aktivovat dříve (např. 3 s)
- [ ] doplnit tooltipy (platí pro všechny ikony v overlay obecně)

**Comment by Werxis** [comment]
K tomu druhému bodu v rámci fade out, momentálne sú nastavené 4s tak aby to bolo také isté ako fade out celého rozhrania. Môžem kľudne prestaviť na 3s, ale nebude Vám teda vadiť, že najprv po 3s zmizne lišta fotogalérie a potom o dalšiu 1s zmizne overlay ?

**Comment by motyc** [comment]
@Werxis Já když to teď měřil, tak to vycházelo někam na 5-6 s, ale nevím, kdy to začíná. Určitě bych to držel jednotné. Tak co to oboje dát na 2 s? Pokud je tam ještě nějaké zpoždění, mohlo by to být akorát.

**Comment by Werxis** [comment]
Hmm, ja som to teraz práve na testovacom prostredí skúsil a vychádza to na tie 4 sekundy. Samotný overlay sa skryje po 4 sekundách nečinnosti, teda po 4 sekundách, kedy užívateľ nehýbal ani neklikal myšou. Napr. ak prešli 2s a užívateľ pohol myšou, tak sa časovač akoby "resetoval". Ak užívateľ 4 a viac sekúnd nič nerobil, overlay sa skryje, ostáva skrytý, pri novom pohybe sa ihneď objaví a skryje sa znova až po dalších 4 sekundách nečinnosti.

Spozdenie by tam byť nemalo a kľudne to môžem prestaviť na 2 sekundy, ale nebude sa stávať, že užívateľovi sa ľahko stane, že 2 nehýbal a ten sa bude často otvárať a zatvárať. Napríklad ja osobne obecne pri vyvíjaní, zapracovávaní nejakých issues si dočasne tento limit aj navyšujem, aby sa mi to stále neskrývalo a nezobrazovalo, ruší ma to pri práci, tak to dávam na zváženie ale samozrejme s limitom môžeme manipulovať podľa potrieb, pre mňa je to zmena len jedneho čísla.

**Comment by motyc** [comment]
Máte pravdu, teď jsem to pořádně změřil a jsou to 4 s. Tak to dejme kompromisně na 3 s. Ono totiž jde o to, že většinu času bude uživatel jen koukat a když to bude moc dlouhé, tak u kratších obrazovek vlastně ke skrytí dojde poměrně pozdě. Změnit to jde vždycky, když by se to neosvědčilo.

**Comment by Werxis** [comment]
Hotovo.
Šípky vľavo sa nezobrazuje pri prvej fotke a takisto šípka vpravo pri poslednej fotke, fade out snížený na 3 sekundy a takisto boli pridané aj tooltipy do rozhrania fotogalerie a takisto aj do rozhrania obrazovky obecne.

**Comment by nnis** [comment]
nestíhám, omlouvám se, číst celou genezi issue, ale otestovala jsem bez čtení a za mě se to chová pěkně, šipky dopředu dozadu fungují, pohyb fotky fajn, esc funguje, řadí se to OK. možná bych dala do infoboxu (kontextové nápovědy doporučení, že lépe se to zobrazuje při sudých počtech, ale i ten lichý je ok

![fotogalerie](https://github.com/LIBCAS/INDIHU-Exhibition/assets/15922183/6bf0f528-26d9-4556-af58-1af96821d85d)
