### ISSUE TITLE
Sladění číslování obrazovek

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#348]
Přijde mi hrozně nepraktické, že číslování kapitol v URL je definováno od nuly, ale v rozhraní pro editora se to zobrazuje od 1. Obě číslování spolu tak nekorespondují a ztěžuje to orientaci při tvorbě výstavy a testování. Bylo by užitečné dát do souladu. Má to háček pouze v tom, že změnou buď rozhodíme případné existující odkazy, nebo to bude v editaci také od nuly, což bude vypadat asi divně. Možná je to ale menší zlo.

- [x] Řešením by mohlo být přidání prokliku ze zobrazení výstavy do editace (pokud jsem přihlášený a výstavu mohu upravovat).

**Comment by Werxis** [comment]
Asi sa radšej rovno opýtam, máte nejaké predstavu, že kde by sa tento preklik zobrazil? Hneď priamo do očí viditeľné v overlay spolu s buttonmi ako je audio, play / pause spolu s infoprohlídkou? Alebo radšej mierne schované do bočného informačného panelu?

A ešte ma rovno napadá drobnosť, text prekliku ?

**Comment by motyc** [comment]
Myslím, že místo textu by stačila ikona tužky (v tooltipu dát "Upravit obrazovku"). Ikonu bych dal normálně vpravo dolů k ostatním, jen bude viditelná pouze v relevantních případech.

**Comment by Werxis** [comment]
- ikona spolu aj s tooltipom a textom pridan0 do panelu
- na jej viditeľnosť bola použitá úplná rovnaká logika ako #347
