### ISSUE TITLE
Možnost vlastní ikonky v konkrétním infopointu 

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#351]
Navazuje na #273 
(možnost také nastavit pro celou výstavu v rámci #313

**Comment by Werxis** [comment]
Poprosil by som o drobné upresnenie, že čo to vlastne znamená vlastná ikonka **v** konkrétnom infopointe ? 

V konkrétnom infopointu --> nejaké použitie ikonky vo vnútri infopointu alebo by to bola nejaká ikona, ktorá by bola ako jedna z možností popri aktuálnemu infopointu v tvare štvorca, resp. krúžku ? V takom prípade máte aj nejakú predstavu, že ako by to cca malo vyzerať ? Aby to nebola len nejaká "levitujúca ikonka" ?

A dalšou otázkou je, aké ikonky vlastne užívateľovi poskytnút na výber ? Máte tiež nejakú predpripravenú sadu ?

**Comment by motyc** [comment]
Jde o to, aby místo kroužku/čtverečku mohl uživatel nahrát vlastní obrázek s průhledným pozadím, který se použije jako ikona.
