### ISSUE TITLE
U videa v infopointu nejde posouvat čas

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#352]
Tahání za posuvník nic nedělá (ostatní prvky fungují ok).

**Comment by Werxis** [comment]
Prerobil som kompletne ovládací panel videa, ťahanie za posuvník už posúva video + som pridal načítavacie kolečko počas načítavania videa.

**Comment by nnis** [comment]
Otestovala jsem a super, vypadá to fakt pěkně. Jen tedy nefunguje mezerník, ale to je myslím dobře, protože ten by měl fungovat na úrovni celku. Nezavírám issue, abychom se shodli na tom mezerníku
![video-infopoint](https://github.com/LIBCAS/INDIHU-Exhibition/assets/15922183/b47b00d9-0c3e-4117-8949-f656e241cf79)

**Comment by motyc** [comment]
@nnis U mne mezerník pro pauzu funguje (Chrome i Mozilla). Tak asi zavírám a pokud bys s tím měla nadále nějaké problémy, asi by to chtělo více specifikovat do samostatného issue.
