### ISSUE TITLE
Slideshow - manuálne nastavenie času jednotlivých fotografií

### ISSUE THREAD

**Issue by Werxis** [LIBCAS/INDIHU-Exhibition#353]
Pridanie funkcionality pre slideshow, kedy každej fotke je možné manuálne nastaviť čas (predtým nastavenie času pre samotnú obrazovku sa rozdelilo rovnomerne skrz všetky fotky)

- do administrácie slideshow obrazovku je pridaný nový checkbox s popisom "Manuálne každej fotke nastaviť čas"
- keď je tento checkbox vypnutý, tak ide o rovnomerné rozdelenie času obrazovky skrz všetky fotky (predošlá funkcionalita)
- keď sa tento checkbox zapne, tak sa disable možnosť nastaviť manuálne čas celej obrazovky, pretože tento čas sa automaticky dopočítava a upravuje na základe časov jednotlivých fotiek (ich súčet)
- keď sa tento checkbox zapne, tak sa pre každú fotku v administrácii zobrazí číselný input, kde je možné zvoliť čas v sekundách pre každú fotku (zmena týchto časov sa prejavuje aj v zobrazení času celej obrazovky)
- upravený progressbar vo výstave, pomocou ktorého je možné pretáčať obrazovku slideshow + takisto upravené aj náhľady

**Comment by motyc** [comment]
Jedinou drobnou chybou je, že když zapnu "Automaticky podle mluveného slova", tak se neaktualizuje celkový čas obrazovky trvale, ale po vypnutí se to vrátí na původní manuálně stanovenou hodnotu (. Původní hodnota by se takto měla přepsat, tím se to promítne i do přepočtu na jednotlivé foto, když pak použiji funkci pro manuální nastavení. Jinak je to ok.

**Comment by Werxis** [comment]
Issue zapracované, dúfam že som správne pochopil.
