### ISSUE TITLE
[53] Úpravy administrace

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#359]
- [x] Chybí možnost filtrovat vlastní výstavy (nyní vidím vše, ale nijak snadno nenajdu jen svoje).
- [x] Co znamená řazení podle "Právě upravováno"? Pokud jde o uživatele "naposledy upravováno", pak by se mělo přejmenovat např. na "Naposledy upravil"
- [x] V nastavení účtu by pro admina mělo jít vypnout zasílání emailových upozornění na nové uživatele. Ne každý admin chce být spamován...
- [x] Pokud otevřu nabídku "Záznamů na stránku:", tak se rozbalí za patičku a musím rolovat, abych seznam viděl. Obecně navrhuji zde patičku úplně odstranit a ponechat ji pouze na přihlašovací obrazovce (jinde pouze zabírá místo a obsah je irelevantní).

**Comment by motyc** [comment]
Zaškrtnuté opraveno, doplnil jsem jeden bod k problémům s patičkou.

**Comment by Werxis** [comment]
Zapracovaný prvý a posledný bod, teda
- pridaný filter na vlastné výstavy (som autor),
- prerobil som "selectfield", ktorý nastavuje počet záznamov na stránke, ale neviem, že či sme sa v tomto bode úplne zhodli

**Comment by motyc** [comment]
Zmíněné dva body ok, k dodělání je problém s náhledem a vypínání mailů pro adminy.

**Comment by Werxis** [comment]
Zapracovaný aj posledný tretí bod, pridaný checkbox do profilu pre admina s možnosťou vypnutia e-mailov ohľadom registrácií užívateľov.
