### ISSUE TITLE
Dokumenty k výstavě/k obrazovce (MUO)

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#36]
Volba Žádný odkaz/URL/Soubor mi nepřijde úplně jednoznačná (možná bude vyřešeno po doplnění nápovědy)
![obrazek](https://user-images.githubusercontent.com/42305589/43996637-482c260c-9dc7-11e8-88c8-b729df35c31f.png)

**Comment by rudky4** [comment]
Vyriešime v rámci vytvorenia nápovědy, aktuálne čakáme na zadanie.

**Comment by nnis** [comment]
**A. Dokumenty k celé výstavě (edituji na stránce "Úvod výstavy"** 
Prosíme o úpravu v totmo smyslu: 

1. Zrušit možnost "Žádný odkaz", není to praktické, ani funkční 
2. U možnosti URL změnit popis "Název dokumentu" na "Název" 
3. Do kontextové nápovědy přidat seznam podporovaných formátů dokumentů, které mohu přiložit a změnit znění nápovědy: 
"Dokumenty a soubory k výstavě, které budou zobrazeny na úvodní a závěrečné obrazovce výstavy. Podporované formáty: .png, .jpg, .jepg + ...DOPLNIT.. 
4. Přidat možnost přidání .doc, .docx a .pdf  
5. Sjednotit pojmenování na závěrečné obrazovce Soubory k výstavě i v pravé části obrazovky (aktuálně "Dokumenty k výstavě") - viz screenshot
![dokumenty-k-vystave](https://user-images.githubusercontent.com/15922183/149901690-41b33fe9-f099-46d4-b430-675e950c9d17.png)

**B. Dokumenty k jednotlivým obrazovkám** 
3. Do kontextové nápovědy přidat seznam podporovaných formátů dokumentů, které mohu přiložit a změnit znění nápovědy: 
"Dokumenty a soubory se zobrazí u konkrétní obrazovky a návštěvník si je může stáhnout. Podporované formáty: .png, .jpg, .jepg + .DOPLNIT.... Soubory se nezobrazí na závěrečné obrazovce. Pokud chcete umožnit zobrazení v závěru výstavy, přidejte je k souborům v obrazovce Úvod výstavy. " 

Poznámky: 
- přidání odkazu (možnost "URL") funguje dobře, na tom není třeba nic měnit
