### ISSUE TITLE
Nefunkční správa uživatelů

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#360]
https://exhibition-test.indihu.cz/users - nezobrazuje žádné uživatele (pokud tedy nejsou všichni smazaní)

**Comment by motyc** [comment]
Za mne také nefunguje, test nyní na: https://exhibition-test.indihu.cz/users

**Comment by xkollar3** [comment]
Ahoj, v skratke chybal index v elastic search a vytvaral som ho rucne cez controller pre adminov lenze pri kazdom restarte aplikacie sa index zmazal, uz je to automatizovane.

Detailne - elastic ma zlozku kde si drzi indexy, tato zlozka je priamo v api zlozke ktora je sucastou docker kontajnera INDIHU-api. Pri kazdom nasadeni novej verzie sa ale kontajner musi zmazat preto zmiznu pri nasadeni indexy a nevidite uzivatelov, povodne mi nedoslo, ze sa to zmaze a reindexoval som rucne. Teraz uz je to automaticke po nasadeni takze by sa nemalo stat, ze na to zabudnem.
