### ISSUE TITLE
Hry - přechod mezi obrazovkami

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#363]
Nefungují šipky na klávesnici, jen na kliknutí

**Comment by Werxis** [comment]
Tu by som sa tiež opýtal na doupresnenie, ja som teraz skúsil na výstave 100letARU prejsť šípkami cez obrazovku kvízu, dokresli a obrazovke gumovania a šípky doľava / doprava na pohyb medzi obrazovkami fungovali

**Comment by motyc** [comment]
@Werxis Dtto jako u #364. Netestoval jsem to, jen přenesl a proto je to označeno k revizi. Osobně také myslím, že už to bude ok.
