### ISSUE TITLE
Soubory k výstavě

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#364]
Když nenahraji soubory, stále se mi zobrazují na úvodní stránce a objeví se pop-up okno. Když nenahraji soubor, funcionalita zmizí

**Comment by Werxis** [comment]
V čom je prosím konkrétne problém? Z popisu som pochopil, že ide o súbory a úvodnú obrazovku výstavy, avšak nepochopil som to úplne a ani neviem, že o ktoré pop-up okno sa jedná ?

**Comment by motyc** [comment]
@Werxis Tohle je schválně v projektu jako "revidovat", protože sám nevím, co je tím myšleno. Je to vytažené jako poznámka z toho GD a musí se k tomu přihlásit někdo kdo to psal. Zatím tomu nevěnujte pozornost.
