### ISSUE TITLE
Zneplatnění cache v prohlížeči

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#378]
Je velký problém s tím, že v cache prohlížečů zůstává stará verze výstav a vyjma cíleného vymazání cache či využití anonymního okna se nová verze nenačte. Bude třeba nějak zajistit, aby se pro novou verzi stará cache nepoužívala, jinak budeme mít velký problém na straně uživatelů, protože většině nic nebude fungovat správně a nebudou vědět proč.

**Comment by motyc** [comment]
@Werxis @StastnyP Zkoušel jsem se podívat na novou verzi aplikace a hlásím akutní nutnost řešit ten problém s cache, a to pokud možno obratem. Aktuálně to vypadá tak, že když otevřu v Chrome aplikaci v běžném okně, vidím původní verzi:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/b26a8107-7da6-453e-825a-aa20834b9449)


Když otevřu anonymní okno, zobrazí se mi již nová:
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/1c1fe871-8cdd-41ef-880f-957a1603b27b)


Na mobilu i PC se to chová úplně stejně. Nepomůže ani Ctrl + F5, musel bych cíleně smazat cache.

**Comment by StastnyP** [comment]
Dobrý den, děkujeme za upřensění, o této problematice víme a zkoumáme. Vynucení cache na úrovní apache serveru nezabralo, kolega již zkouší jiné řešení, které vynutí promazání na frontendu.

**Comment by motyc** [comment]
@xkollar3 Textace mailu:
```
Vážení uživatelé,

v minulém týdnu proběhl avizovaný přechod na novou verzi INDIHU Exhibition. Dnes již tak můžete přistupovat k nové verzi, která v pořádku běží na původní adrese https://exhibition.indihu.cz/

Novou verzi snadno poznáte podle inovované úvodní stránky s přihlašováním (tmavě modrá stránka s videem v pozadí). Pokud po příchodu na web stále vidíte původní rozhraní (na pozadí holčička v brýlích), zůstala v mezipaměti Vašeho prohlížeče lokálně uložená stará verze webu. Jako dočasné řešení doporučujeme otevírat stránku https://exhibition.indihu.cz/ v anonymním okně prohlížeče, kde se Vám vždy zobrazí správná aktuální verze.

Jak otevřít anonymní okno:
Chrome: https://support.google.com/chrome/answer/95464?hl=cs&co=GENIE.Platform%3DDesktop
Mozilla: https://support.mozilla.org/cs/kb/anonymni-prohlizeni-prochazeni-internetu-bez-uklad
Edge: https://support.microsoft.com/cs-cz/microsoft-edge/proch%C3%A1zen%C3%AD-inprivate-v-aplikaci-microsoft-edge-cd2c9a48-0bc4-b98e-5e46-ac40c84e27e2
Safari: https://napoveda.seznam.cz/cz/anonym-safari/

My zatím usilovně pracujeme na tom, aby se vše správně zobrazilo i v běžném okně prohlížeče.

s pozdravem
Tým INDIHU Exhibition
```

Jinak se těmi spam filtry nevím, co je lepší. Asi by to chtělo najít nějako best-practice a řídit se podle toho. Vím, že jsme s tím jinde mívali problémy...

**Comment by motyc** [comment]
Ok, klidně to zkuste a potvrdím, až přijde.

Jinak kontrolovat ten seznam nemá teď smysl. Pošlete to všem aktivním **- vynechat smazané, nepotvrzené atd.** U něčeho se asi vrátí chyby, ale to je jedno.

**Comment by motyc** [comment]
@xkollar3 Mail přišel poprvé chybně, teď obratem podruhé už dobře.

**Comment by xkollar3** [comment]
okay, to som sa kopol pri prvom a vymenil predmet/telo + za vas teda ok ten druhy + predmet moze byt takto?

**Comment by motyc** [comment]
Ano, takto lze rozeslat. Děkuji.

**Comment by xkollar3** [comment]
Maily som rozposlal, vyslo to na 687 ludi, filtroval som vsetkych EDITOR + nezmazany + ACCEPTED (este som vynechal inqool ludi)

**Comment by StastnyP** [comment]
Byl nasazen update, který promazává cache webu v prohlížeči klienta. Je zapotřebí znovu načíst web. 
Prosím o otestování.

**Comment by motyc** [comment]
@StastnyP Potvrzuji funkčnost! Nešlo by jen nějak donutit prohlížeč, aby reload po příchodu na stránku udělal sám? Tvůrcům to sice můžeme napsat, ale problém s cache se projevuje i při prohlížení výstav a tam žádnou možnost napsat anonymním uživatelům nemáme... Můžeme to tam nějakou dobu nechat a časem to vypnout. Nebo vymyslet něco podobného.
