### ISSUE TITLE
Infoprohlídka - chyby

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#388]
- [x] Infoprohlidka na iphone vubec nenabehla
- [x] při prohlíce se nezastavila vystava, což je nutne, aby neubihal obsah
- [x] U her by bylo obecně dobré, kdyby se infobox s pokynem, co mám dělat, rozvinul při příchodu na obrazovku, protože jinak není možné chápat, co se děje.

**Comment by motyc** [comment]
@Werxis

- [ ] Infoprohlídka se mi teď spouští opakovaně na každé obrazovce, na kterou vstoupím, dokud jsem neklikl na "Přeskočit infoprohlídku" (tj. i v případě, kdy ji normálně projedu do konce.
- [ ] Po chvilce testování infoprohlídky teď (23. 1. cca ve 22:10) zjevně spadla DB nebo něco jiného na backendu. Nutno prověřit, co se stalo. Pohyboval jsem se pouze ve výstavě: https://exhibition-test.indihu.cz/view/100letARU3 (a nic jsem neupravoval).

**Toto jsem před pádem nestihl testovat:**
- [ ]  Infoprohlidka na iphone vubec nenabehla
- [ ]  U her by bylo obecně dobré, kdyby se infobox s pokynem, co mám dělat, rozvinul při příchodu na obrazovku, protože jinak není možné chápat, co se děje.

**Comment by Werxis** [comment]
Dobrý deň,

čo sa týka toho prvého bodu, ohľadom infoprohlídky, tak vedeli by ste mi iba povedať, ak si pamätáte, že o ktorú infoprohlídku išlo ? Ja som napr. teraz toto isté skúšal cez TEST server (`exhibition-test.indihu.cz`), dostal som sa hneď na prvú obrazovku po štartovacej obrazovke (obrazovka s názvom Založení ústavu), manuálne som sa preklikal skrz tých 10 krokov a táto infoprohlídka sa mi už následne opakovane nezobrazila. Zobrazili sa mi iné infoprohlídky, ale táto na rozhranie už nie. 

Čo sa týka druhého bodu, zaurgoval som na kolegu z BE, už to rieši a napíše sem, až to bude hotové s vysvetlením.

Zatiaľ ďakujeme za nahlásenia

**Comment by xkollar3** [comment]
> * [ ]  Po chvilce testování infoprohlídky teď (23. 1. cca ve 22:10) zjevně spadla DB nebo něco jiného na backendu. Nutno prověřit, co se stalo. Pohyboval jsem se pouze ve výstavě: https://exhibition-test.indihu.cz/view/100letARU3 (a nic jsem neupravoval).

Zdravím, dnes som to overoval, spadlo to na pamäti navýšil som tam limit (TEST kontajner/new PROD kontajner) bol nastavený veľmi nízko (300mb -> 4gb). Už by sa to stať nemalo, nechám zatiaľ otvorené.

**Comment by motyc** [comment]
@xkollar3 Díky za info. Zítra tedy zkusím otestovat zbytek.

@Werxis Dělo se mi to hned u té první základní infoprohlídky v uvedené výstavě. Zobrazila se jak na první stránce výstavy, tak na druhé znovu a znovu. Bylo to v anonymním okně, takže by to nemělo souviset s cache nebo něco takového. Pomohlo jen to kliknutí na "Přeskočit".

**Comment by motyc** [comment]
@Werxis Asi jsem zjistil, čím to je. Při klikání na "Další" se dostanu jen k sedmému kroku z deseti (pak se zavře a spustí), takže prohlídku nikdy vlastně nedokončím. Proto se stále dokola otevírá.

Jinak vše funguje.

@H-a-n-k-a Otestuješ prosím "Infoprohlidka na iphone vubec nenabehla"? Nemám to jak zkusit.
