### ISSUE TITLE
Nefunkční registrace

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#389]
Zkusil jsem přes registrační formulář vytvořit nový účet a po dlouhém načítání vyskočilo "Registrace neúspěšná":
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/20186892/cca4f0e8-4f31-4514-b80c-1b7c41bb4c1e)

**Comment by motyc** [comment]
@xkollar3 Zkuste to prosím dohledat. Bylo někdy v době vytvoření tohoto issue. Psal jsem to víceméně hned.

**Comment by xkollar3** [comment]
V logoch nič k tomu nevidím, opravil som zatiaľ aspoň to načítavanie, ak by sa to stalo znovu tak to nahláste prosím a pokúsim sa zistiť príčinu.

**Comment by motyc** [comment]
@xkollar3 Se stejným mailem už to neprověřím, protože účet už existuje, ale s jiným mailem to v pohodě prošlo. Tím že z testu nechodí maily, tak to nejde dotáhnout, ale snad to bude ok.
