### ISSUE TITLE
Infoprohlídka u prewiev 

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#394]
Uživatelé si stěžovali, že vždy u náhledu se rozjede infoprohlídka. Je třeba probrat, jak to bude fungovat

**Comment by StastnyP** [comment]
Potřebujeme více specifikovat, po přehrání se infoprohlídka opět spouštěla?
Možnost řešení: Tlačítko pro znovuvyvolání infoprohlídky, když ji uživatel přeskočí.

**Comment by motyc** [comment]
Ikona přibyla a funguje, ale narazil jsem na jiný problém. Když procházím infoprohlídku (např. u https://exhibition-test.indihu.cz/view/100letweb2019-07-30T080518814Z/4/1), tak při kroku 3 z 11 se tlačítko "Další" nachází nad levým ovládacím menu. Po kliknutí na "Další" se ale neposune dále infoprohlídka, místo toho se aktivuje ikona ležící pod modalem (tj. spustí se pokračování výstavy) a infoprohlídku tak nejde celou projít.
