### ISSUE TITLE
Motiv se neuložil 

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#396]
Je třeba ověřit funkčnost uložení Motivu, nepropsalo se to. Uživatelé si mysleli, že to musí vyplnit nejdřív, pak že už to nejde upravovat. 

Prosím o otestování: @kristynahubickova

**Comment by kristynahubickova** [comment]
Ahoj @nnis, teď jsem na to koukala a změna motivu mi funguje bez problému, propisuje se mi to. Je důležité klikat na "uložit změny" a ne na "resetovat nastavení" - to pak může uživatelům přijít, že se nic neděje.

Jediné co, tak nefunguje "malířské plátno" pro custom volbu barvy infopointu ad bod **3. Předvolený motiv pro infopointy** viz 
![image](https://github.com/LIBCAS/INDIHU-Exhibition/assets/79597746/93e2ca0d-ee28-42e0-9622-88941b4f8c36)

**Comment by H-a-n-k-a** [comment]
Souhlasím s Kristýnou, nešlo mi to na ws.
Prosím prověřit funkčnost nastavení barvy infopointu.

**Comment by StastnyP** [comment]
Nedaří se ukládat infopoint

**Comment by motyc** [comment]
@Werxis 
Stále nefunguje, resp. data se uloží, ale změna barvy infopointu se neprojeví ve výstavě.
