### ISSUE TITLE
Chyby v textaci

### ISSUE THREAD

**Issue by H-a-n-k-a** [LIBCAS/INDIHU-Exhibition#397]
- [x] backend - při nahrávání loga je v textaci slovenština
- [x] backend - úvod do výstavy přejmenovat na úvod do kapitoly

**Comment by motyc** [comment]
@H-a-n-k-a Prosím o test, nevím, kde přesně mám dané položky hledat.

**Comment by H-a-n-k-a** [comment]
![úvod_do_kapitoly](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/69286d3a-e6ac-439c-9c60-1d43f536d816)
takto prosím přepsat

**Comment by H-a-n-k-a** [comment]
Je to úplná maličkost, ale prosím o vymazání slov "expozice'", jak je naznačené ve fotografii, mám zpětnou vazbu, že to je prý matoucí.
![loga](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/51af3578-a2df-48fa-82e9-b1aa6ad21c47)
