### ISSUE TITLE
Klikací pole "Stále zobrazen" nejde kliknout

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#403]
U infopointů nejde kliknout do pole pole "Stále zobrazen". Volbu mohu provést pouze uvnitř v celkové nabídce funkcionalit po té, co kliknu na ikonu tužky. Prosím opravit

![stale-zobrazen](https://github.com/LIBCAS/INDIHU-Exhibition/assets/15922183/c107dafb-1ddc-42f3-b0f0-5cbbb5245940)

**Comment by motyc** [comment]
Myslím, že to není bug, ale vlastnost. Má to jen označovat, které infopointy jsou stále zobrazené a které ne.... Ale chápu, že to vypadá jako ovládací prvek a je to tím pádem matoucí.

**Comment by Werxis** [comment]
Toto issue považujem za duplicitné s nasledovným issue: #415 (ktoré je už na teste)
