### ISSUE TITLE
Přesun obrazovek - funkce drag&drop (MUO)

### ISSUE THREAD

**Issue by malinekv** [LIBCAS/INDIHU-Exhibition#41]
Pokud jsem se nepřehlédl, momentálně funguje možnost přesouvat obrazovky vždy jen horizontálně (obrazovky druhého řádu, začleněné do nějaké kapitoly; tj. obrazovky typu 1.2, 2.2, 3.6 atp.), nebo vertikálně (obrazovky prvního řádu v prvním levém sloupci, tj. mají číslo bez desetinného třídění) a neexistuje tedy možnost přesunout obrazovku „druhého“ řádu mezi obrazovky „prvního“ řádu a naopak. Nedaří se mi to ani přes nabídku „Přesunout“ ani přes nabídku „Duplikovat“. Je to v pořádku? 
![obrazek](https://user-images.githubusercontent.com/42305589/43996696-79b88688-9dc8-11e8-9c15-0ead576f8481.png)
Funkce „Přesunout“ tak momentálně jen duplikuje možnost ručního přesunu pomocí šipek.
Nebylo by lepší funkci změnit např. tak, že by se ručně zadávalo číslo obrazovky před kterou/za kterou by se měla přesouvaná obrazovka nově uložit?
Jen by se pak muselo ošetřit, zda přesun před první stránku kapitoly znamená, že se obrazovka přidá jako poslední část předcházející kapitoly, nebo zda z ní vznikne nová obrazovka „první“ úrovně v prvním sloupci (a podobně přesun za poslední stránku kapitoly)

**Comment by rudky4** [comment]
Jednotlivé obrazovky, které jsou uvnitř kapitoly je možné přesouvat nejen v rámci dané kapitoly, ale i mezi ostatními kapitolami (první select volí kapitolu, druhý pozici v kapitole). Ostatní, co je popsáno, sedí... tzn. nelze v současnosti přesunout samostatnou obrazovku do kapitoly nebo udělat z obrazovky v kapitole samostatnou obrazovku. 
Navrhujem ponechať na prípadný ďalší rozvoj.

**Comment by rudky4** [comment]
Aktualne je možne presunut pomocou dialogu:
![image](https://user-images.githubusercontent.com/7311447/46939128-c890b080-d065-11e8-9622-c8470a42fc70.png)

**Comment by nnis** [comment]
Přesun obrazovek
Stávající stav je matoucí a nelogický, protože se řeší dvěma způsoby. Jednak funkcí drag&drop, jednak přes menu ... u obrazovky. Prosíme o sjednocení tak, aby: 

1. Ať funguje pouze funkce drag&drop 
2. Odstranit funkci v menu "Přesunout" 
3. Funkce drag&drop ať funguje ve všech směrech, tedy
- přesouvám obrazovku v rámci kapitoly (teď funguje)
- přesouvám obrazovku do jiné kapitoly (teď NEfunguje)
- přesouvám obrazovku do základní linie (větve) výstavy (úvody do kapitol + samostatné obrazovky různých typů) (teď funguje)
- přesouvám obrazovku ze základní linie (větve) výstavy (úvody do kapitol + samostatné obrazovky různých typů) do některé z kapitol (teď NEfunguje)
