### ISSUE TITLE
Nefunkční tlačítko Uložit

### ISSUE THREAD

**Issue by H-a-n-k-a** [LIBCAS/INDIHU-Exhibition#413]
V administrátorském rozhraní nefunguje tlačítko uložit, pouze klávesová zkratka Ctrl+S.
![nefunguje_uložit](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/5005e174-176a-4042-b0e7-06b23ee2d7a9)

**Comment by Werxis** [comment]
Dobrý deň,

kvôli čo najrýchlejšiemu vyriešeniu.. vedeli by ste mi prosím poskytnúť:
1. Pod akým užívateľkým emailom / username ste na screenshote prihlásená ?
2. O akú výstavu ide

Hore v lište, vedľa `stav: V příprave` vidno takú ikonku, ktorá je preškrtnutá.. to symbolizuje, že daný užívateľ nemá oprávnenie editovať túto výstavu. Preto sú aj všetky tlačítka vypnuté.

**Comment by H-a-n-k-a** [comment]
Dobrý den, malé ikonky jsem si nevšimla, se vám přiznám, ale kontrolovala jsem si práva a sdílení - zde je napsané čtení a zápis. To je špatně, prosím?
![prava_uprav_vystavy](https://github.com/LIBCAS/INDIHU-Exhibition/assets/93780817/064a35de-d522-4b59-922a-fdab5d4a4481)
Jinak paní psala, že je vlastníkem. Já v tomto případě vlastníkem nejsem, tím je: 
Jméno | E-mail | Práva
-- | -- | --
Renáta Chalupová | chalupova@muo.cz | Vlastník
Výstava jménem: 2 209 králíků stav: v přípravě

**Comment by xkollar3** [comment]
Dobry den, malo by byt funkcne BE bolo v starej verzii a neposielali sa spravne prava, uz by to malo byt funkcne na vsetkych miestach, ked tak ma oznacte keby to pretrvava
