### ISSUE TITLE
Posuvník "Foto před a po"

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#47]
Funkce funguje dobře. Osobně bych přivítal, kdyby posuvník byl přímo na obrázku a nikoli zcela na kraji obrazovky, kde mi připadá trochu schovaný. Je to však spíše ke zvážení, zda by takovéto řešení vyhovovalo všem zúčastněným.

Jako příklad viz:

![obrazek](https://user-images.githubusercontent.com/42067492/44038835-fa7ea7e8-9f17-11e8-8c9e-eabdf1014372.png)

https://www.megapixel.cz/hoya-polarizacni-cirkularni-filtr-hd-82-mm

**Comment by rudky4** [comment]
@Kolemkoukolem upraveno, prosim o test

**Comment by Kolemkoukolem** [comment]
Funguje a vypadá to mnohem lépe. Pokud by to nebyl velký problém, doplnil bych na posuvník ještě symbol šipek (nahoru a dolů), aby byla funkce na první pohled patrná a intuitivní. Děkuji.

**Comment by Kolemkoukolem** [comment]
Současný posuvník se projevil v některých specifických případech jako málo nápadný a část návštěvníků si ho nevšimla. Přimlouval bych se změnu barvy např. za modrou (jako jsou infopointy, guma, vlaječky a pod.) či zvýraznění na počátku nějakým blikáním apod.

**Comment by jirkacechak** [comment]
hotovo
