### ISSUE TITLE
Přidání dokumentu ke stránce

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#62]
Zjistila jsem, že: 

- [x] Není u přidání dokumentu informační íčko, respektive se objeví až po té, co přidám dokument, což je pozdě. Na stránce je jen plusko pro přidání dokumentu. 

- [x] Když přidávám soubor pomocí URL, v nabídce chybí možnost "Webová stránka" jako typ dokumentu nebo něco jako "Článek na webu" nebo "Online zdroj". Nějak takhle by se to mělo jmenovat. 

- [x] Netuším, co dělá možnost "Žádný odkaz" - ukáže se mi to ve výpisu, ale nedovolí mi to přidat žádný soubor, nicméně ho mohu pojmenovat. 

- [x] Když přidávám dokument v módu soubor, nevybírám typ dokumentu, přitom u URL ano. Proč? Neměla bych to také vybírat? 

- [x] Nešlo mi opakovaně nahrát soubor ve formátu .docx. Tento formát by měl být podporován, protože umožňuje uživatelům se souborem nadále pracovat. 

- [x] Nešlo mi opakovaně nahrát soubor ve formátu .mp3

- [x] Máme někde seznam podporovaných formátů, které mohu přidat?

**Comment by rudky4** [comment]
@nnis 

- "Žádný odkaz" - slouží pro zadání názvu dokumentu, který není v elektronické podobě ani na url (např. název knihy),
- "Když přidávám dokument v módu soubor" - typ se vybírá pouze u url, protože u souboru se zjistí typ automaticky
- "Máme někde seznam podporovaných formátů, které mohu přidat?" - Zoznam podporovaných formátov je na Vás, aktuálne je to bez obmedzení.

Ostatné vyriešené. Pridávam label nápověda, aby sa to nestratilo.

**Comment by nnis** [comment]
Díky, zamyslíme se s Ivem na změnou textace u "Žádný odkaz", tzn. vyřešíme v nápovědě.

**Comment by nnis** [comment]
řeší issue #36
