### ISSUE TITLE
Náhled z prostředka výstavy

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#68]
Náhled mi funguje, jenže když nejdu od úvodní obrazovky, skončí náhled jen u té jedné konkrétní stránky a nepřesune se dál, viz proress bar, který už je tmavý, ale já pořád čekám. Nemel by náhled fungovat tak, že prostě pojede od té konkrétní stránky až do konce? 
![nahled-dal](https://user-images.githubusercontent.com/15922183/48540275-fada3b80-e8b9-11e8-841d-0dada658ad2d.png)

Chromium: Version 70.0.3538.77 (Official Build) Arch Linux (64-bit)

**Comment by rudky4** [comment]
@nnis náhlaď bol pôvodne zamýšľaný len pre jednu konkretnu obrazovku. Ak má výstava pokračovať do konca, nechal by som to ako enhancement na ďalší vývoj.

**Comment by rudky4** [comment]
Ešte dodatočné vyjadrenie z vývoja: Náhled obrazovky by neměl umožňovat automatický přechod na další, aby nebylo nutné načíst celou výstavu. V současnosti se načítá pouze jedna, aby k tomu došlo rychleji.  Myslím si, že by nebylo vhodné toto měnit, protože by uživatel dlouho čekal na načtení náhledu jedné obrazovky u velkých výstav.
