### ISSUE TITLE
Fungující HTML tagy v textové stránce

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#73]
Jelikož je obrazovka s textem zamýšlena např. na citace, bylo by fajn, kdyby uměla základní HTML tagy na formátování textu. Stačila by kurzíva třeba. Nebo ještě jednodušší markdown?

![obrazovka-s-textem](https://user-images.githubusercontent.com/15922183/49376445-869bf680-f707-11e8-8caf-5425a48587e5.png)

**Comment by rudky4** [comment]
@nnis přidána funkcionalita pro tagy <b> (bold) a <i> (italic), včetně zanoření
prosim o test

**Comment by nnis** [comment]
Otestováno, funguje. Kdyby byl ještě markdown, bylo by to super, ten je ještě jednodušší :)
