### ISSUE TITLE
Nápověda - íčka

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#75]
Většina textace k nápovědám je hotová (zelená), prosím tedy o nasazení, textace zde: https://docs.google.com/document/d/12gKk2r-xGFLYFsAWNWpJ_1-DbEW7WPMsSALl-i7B510/edit?usp=sharing 

Prosím o vyznačení nasazených íček do editoru, díky. Stačí k nasazeným íčkám třeba napsat OK nebo DONE nebo něco.

**Comment by rudky4** [comment]
Postupne začneme zapracovávať, po nasadení budu vyznačené v dokumente.

**Comment by rudky4** [comment]
Časť nápovědy implementovná, progress vyznačený v dokumente.
Zajtra preberieme, akým spôsobom sa má zobraziť nápoveda v časti 2.1 Nová obrazovka

**Comment by rudky4** [comment]
Ďalšia časť nápovědy implementovná, progress vyznačený v dokumente.

**Comment by nnis** [comment]
Skvělé - koukala jsem na to a mám k tomu poznámku ohledně zobrazení. Teď to jde od íčka nahoru z prostředka. U těch delších nápověd je text strašně dlouhý (i 3/4 šířky stránky) a je třeba na řádek a půl. Nebylo by možné z nápověd udělat užší rámečky třeba na šířku 4-5 cm a zobrazit je napravo od íčka? Zvlášť ta nápověda, která se zobrazí přes tu hlavní lištu nevypadá dobře. Díky za zvážení, až dáte vědět, vyzvu tým, aby se na formulaci íček podíval.

**Comment by rudky4** [comment]
úpravy podle posledního komentáře už jsou hotové

**Comment by nnis** [comment]
Perfektní! Díky a zavírám.
