### ISSUE TITLE
Fotogalerie

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#76]
Obrázky v galerii se automaticky roztáhnou na celou obrazovku a oříznou podle potřeby. To znamená, že nelze odhadnout, co ve výsledku bude na obrazovce (záleží to na konfiguraci) a mimo obrazovku mohu zmizet i infopointy. Opravdu to tak chceme?

**Comment by motyc** [comment]
Stránka:
![image](https://user-images.githubusercontent.com/20186892/49584354-56e52c80-f95b-11e8-8a3d-7180010f335c.png)

Výsledek:
![image](https://user-images.githubusercontent.com/20186892/49584375-6bc1c000-f95b-11e8-871f-a8870c728398.png)

**Comment by rudky4** [comment]
@motyc v tom prípade by bolo vhodne zobraziť obrázok bez orezu, ale nevyplní celu obrazovku

**Comment by motyc** [comment]
@rudky4 to myslím vůbec nevadí, ale můžeme se zeptat ostatních

**Comment by rudky4** [comment]
@nnis ? :)

**Comment by motyc** [comment]
Já myslím, že tady to ve vztahu k libovolně velkému monitoru/velikosti okna není řešitelné jinak než stanovením, že vertikálně se obrázek do okna musí vejít. Jinak mi to moc nedává smysl, protože při zmenšení okna (ať už uživatelsky nebo v důsledku menšího monitoru/display) by v některých případech běhaly jen velmi abstraktní výřezy z prostředka obrázků...

**Comment by rudky4** [comment]
@nnis @motyc upraveno, prosim o test (prestým refresh cache)

**Comment by motyc** [comment]
Za sebe mi nesedí dvě věci:
1) v textovém režimu chybí nějaký posuvník a než jsem přišel na to, že rolovat doprava jde kolečkem, dost mi to trvalo, navíc rolování je tak dost pomalé
2) čekal bych, že prezentační režim bude roztahovat fotografie podobně jako textový režim, tj. tak, aby se větší rozměr fotografie vešel celý na obrazovku; nyní to patrně jen zmenšuje, ale nezvětšuje

**Comment by nnis** [comment]
Souhlasím s bodem 1, tlačítko je pomalé, měla jsem tendenci se posouvat pomocí kliknutí myši (držím levé tlačítko a posouvám se ve směru dalších fotek). Co mě ještě napadá, vůbec nedostávám informaci o tom, že je tam víc fotek, zkrátka mám pocit, že nemám jako uživatel jak poznat, že je tam toho víc.
Souhlasím i s bodem dvě, teď se mi fotografie lépe zobrazují v textovém módu než v prezentačním - dvě ze tří fotek jsou v prezentačním pěkně vidět, jedna z nich je malá, přitom v textovém je normálně přes celou stránku.

**Comment by rudky4** [comment]
Info od developera: Přidán posuvník do textového módu. K prezentačnímu se před tím psalo, že se nemusí roztahovat obrázky přes celou obrazovku a teď zase ano, tak jak to je prosim? @nnis @motyc

**Comment by motyc** [comment]
1) Textový mód je myslím úplně v pořádku.
2) U roztahování obrázků jsme se asi úplně nepochopili. Původní stav byl, že obrázek se roztahoval tak, aby zcela vyplnil obrazovku, čímž docházelo k nežádoucímu ořezu. Nyní se to již neděje, ale malé obrázky zůstanou plavat uprostřed obrazovky. Ideální by bylo, aby se menší obrázky roztáhly tak, aby bez ořezu a deformace alespoň v jednom směru vyplnily monitor. Není to úplně klíčové, ale myslím, že by to vypadalo lépe a bylo by to snazší pro práci při tvorbě výstavy.

**Comment by nnis** [comment]
1. Díky za posuvník. Funguje to dobře, jen by bylo asi fajn ho nějak graficky sladit se zbytkem. Jednak je hodně výrazný, hodně vysoký, rohy má ostré a třeba ta lišta v prezentačním módu ukazující zbývající čas a načítání stránky má jednak kulaté okraje a načítá se šedivou. Zvažte prosím, jak ta lišta vypadá. A pak jsem si ještě všimla drobného detailu viz foto - posuvník je o kousíček širší a přesahuje přes fotku. 

![detail](https://user-images.githubusercontent.com/15922183/51980415-3edbe600-2490-11e9-8c5c-a40d1200ab39.png)

2. Jak píše David - teď aktuálně mi přijde, že fotogalerie lépe funguje v tom textovém módu, protože třeba jedna z fotek, na které to testuji se v textovém módu zobrazí přes celou obrazovku, v prezentačním je jen malá uprostřed. 

Viz obrázky se stejnou fotografií - první je textový, druhý prezentační mód

![textovy](https://user-images.githubusercontent.com/15922183/51980670-08529b00-2491-11e9-9b90-e5d188ee0943.png)

![prezentacni](https://user-images.githubusercontent.com/15922183/51980679-10aad600-2491-11e9-9923-4c61711e2fe4.png)

**Comment by rudky4** [comment]
@nnis podla kolegu by malo byt upravene

**Comment by nnis** [comment]
Když mám obrazovku jako fullscreen, funguje mi to snad pěkně. Může na to prosím kouknout ještě @motyc? Když si to zmenším, udělají se mi mezi obrázky černé pruhy (voz foto) a podle velikosti okna jsou užší nebo širší. Nešlo by,a by fotografie na sebe navazovaly pěkně i tak? Nebo jaký je důvod té mezery? Pokud třeba rozdílná velikost (výška jednotlivých fotografií), šlo by to ošetřit upozorněním, aby fotografie byly stejného formátu? 

![fotogalerie](https://user-images.githubusercontent.com/15922183/54535808-9de9b180-498f-11e9-926d-3b0d424ea5a2.png)

**Comment by motyc** [comment]
Ano, mám to stejně a problém se objevuje i obráceně, tedy pokud do textového režimu přepnu s malým oknem a pak ho zvětším, dojde k překryvu fotek. Ve skutečnosti jde asi o to, že poloha fotek se nastaví při vstupu do textového režimu a chování se pak už nemění bez ohledu na velikost okna. Po aktualizaci se to opraví.

![image](https://user-images.githubusercontent.com/20186892/54596461-0048bd80-4a35-11e9-9831-3124ff58ff5e.png)

**Comment by rudky4** [comment]
@nnis @motyc opraveno
