### ISSUE TITLE
Závěr - bibliografie

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#77]
Položka "Bibliografie" na závěrečné stránce vypadá jako klikatelná, ale nikam nevede - jaký tam byl záměr?
Viz
![image](https://user-images.githubusercontent.com/20186892/49584966-46ce4c80-f95d-11e8-8b57-f5b14b987485.png)

**Comment by rudky4** [comment]
@motyc defaultne nebude Bibliografie zobrazena, na klik sa zobrazi
