### ISSUE TITLE
Wiki pro manuál

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#79]
Mám problémy s wiki - chtěla jsem začít tvořit manuál  na první pohled se to zdá v pohodě, ale když začnu vytvářet novou stránku, stane se z wiki editor výstav a jsou ta najednou položky jako v editoru, ale zároveň jsem pořád na wiki. Viz screenshot: 
![wiki-indihu](https://user-images.githubusercontent.com/15922183/50763935-8ac0b400-1271-11e9-8eea-7394852eecce.png)
Můžete se na to prosím mrknout? 

Chromium: Version 71.0.3578.98 (Official Build) Arch Linux (64-bit)

**Comment by rudky4** [comment]
@nnis zabezpecime nápravu 
(ospravedlnujem sa za neskorsiu odpoved, nevsimol som si notifikaciu v e-maile)

**Comment by rudky4** [comment]
@nnis kolega zabezpečil úpravu v konfigurácií

"Niekedy sa spravil request na zlu cestu. Natvrdo som nastavil cestu aby sa nepouzivala autodetekcia, takze snad to vyriesi aj vas problem."

**Comment by nnis** [comment]
Díky moc, už se zdá, že to funguje - bývala bych Vám dneska psala :)
