### ISSUE TITLE
Přejmenování SW

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#82]
Prosím o opravu, nástroj se nejmenuje INDIHU Exhibition**s**, ale bez s na konci - pouze INDIHU Exhibition. Viz obrázek
![prejmenovani](https://user-images.githubusercontent.com/15922183/53799874-c3140400-3f3b-11e9-8ed5-6dfe75bd072f.png)

**Comment by rudky4** [comment]
Upravené
