### ISSUE TITLE
Tiráž

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#84]
Prosím o dvojí přejmenování v tiráži: 
1. Figuruje tam "Nadpis", což je ve skutečnosti spíš "Role"
2. Po kliknutí na plusko pro přidání má vyskakovací okno název "Přidat autory obrazovky nebo spolupracovníky" - prosím o změnu na "Přidat autory výstavy a spolupracovníky" - u jednotlivých obrazovek tiráž nemáme. 
![tiraz](https://user-images.githubusercontent.com/15922183/53886824-2af04a80-4021-11e9-9c51-2e23afb6a793.png)

Pak mám návrh na úpravu:
Píšu manuál a tak popisuji jednotlivé funkcionality. Nějak nevím jestli to filtrování a změna zobrazení v tiráži není trochu overkill. Po výběru z Role (Nadpis)/Osoba nebo text bych čekala, že se spíš změní pořadí sloupců. Pak se to řadí abecedně, což ale také ovládá ta šipka. Jaký je v tom tedy rozdíl? Bude tam někdo mít vůbec tolik lidí, funkcí a osob, aby to potřeboval takhle zobrazovat? To hledání jsem vyzkoušela a funguje dobře, ale také myslím, že to není potřeba, protože s největší pravděpodobností v tiráži nebude více než 20 položek, aby nestačilo klasické ctrl+F. Prosím tedy u zrušení těchto funkcionalit, je to zbytečné. 

Pak mám dotaz k pořadí záznamů v tiráži
To už by mi přišlo účelnější mít tam ještě jeden sloupec, ve kterém řeknu, jak půjdou po sobě ty jednotlivé role při procházení výstavy. Teď jsou tam v pořadí, jak jsem záznam vytvořila a nemůžu s tím hnout. Takže když např. mezi 1. a 2. pozici budu potřebovat přidat ještě třetí roli, budu muset tu druhou smazat a udělat obě najednou. A to mi přijde nešikovné.

**Comment by rudky4** [comment]
Upravené + pridané tlačítka na zmenu poradia položiek

**Comment by nnis** [comment]
Skvělý, díky. Funguje to pěkně.

**Comment by matulovaklara** [comment]
Přidám k tiráži ještě jeden podnět, tedy vlastně 2:
a) Když mám tiráž a dokumenty k výstavě, tak mi nejde scrollovat na úvodní straně k výstavě až úplně dolů. Viz Printscreen.
b) Když přidávám novou roli v tiráži, objeví se mi poslední záznam, který jsem zadala - musím smazat a navíc je to matoucí. Lze tam nastavit defaultně prázdný záznam (tak, jak tomu je, když se přidává úplně první záznam v tiráži)? 

![tiraz](https://user-images.githubusercontent.com/42234445/57706579-50738300-7666-11e9-9c3e-0642d74aced5.jpg)

![tiraz2](https://user-images.githubusercontent.com/42234445/57706585-52d5dd00-7666-11e9-8ca0-fa7023e19a58.jpg)

**Comment by rudky4** [comment]
@matulovaklara upraveno
