### ISSUE TITLE
Posunuté infopointy

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#85]
Je rozdíl v umístění infopointů mezi prezentační (špatně) a textovou verzí (správně).

Správně:
![image](https://user-images.githubusercontent.com/20186892/54136138-7b99e600-441b-11e9-9ab5-e94610ef3a50.png)

Špatně:
![image](https://user-images.githubusercontent.com/20186892/54136159-89e80200-441b-11e9-8fe0-ab29fbe4d91f.png)

**Comment by rudky4** [comment]
@motyc opraveno
