### ISSUE TITLE
Problémy s videem

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#86]
Není jasné, které formáty aplikace akceptuje. Některé formáty se navíc přehrávají jen v některých PC (např. mov použitý ve výstavě "kalendář 2019" na stránce "1.6 tanec" se spustilo jen někde). Je jasné, že videa budou problém, ale mělo by být alespoň zajištěno, že když fungují na jednom místě, budou se přehrávat všude, nebo že systém rozpozná chybu a zobrazí chybovou hlášku.

**Comment by rudky4** [comment]
'H.264 and MP3 in MP4' a 'H.264 and AAC in MP4' by měly být v nejnovějších verzích hlavních prohlížečů podporovány, u ostatních to není jisté

**Comment by Kolemkoukolem** [comment]
Proč se video nepřehrává by dle mého názoru mělo být ošetřeno i jasnou chybovou hláškou. Je potřeba přihlédnout k tomu, že potenciální uživatelé tohoto nástroje nebudou mít kdovíjaké znalosti z IT a tudíž by měli mít jasné vodítko, co dělají špatně, resp. co potenciálně může způsobovat problémy.

**Comment by nnis** [comment]
řeší issue #44
