### ISSUE TITLE
Chování paralaxu

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#87]
Paralax má několik problémů:
1) Opět se část obsahu ořezává, místo aby se přizpůsobovala, naprosto pak nelze odhadnout, co bude ve výsledku u uživatele na obrazovce.
2) Pozadí se při změně velikosti okna deformuje, popředí se správně přizpůsobuje. To navíc způsobuje, že popředí nemá vůči pozadí pevnou pozici.
3) Pozadí z nějakého důvodu má mnohem delší "dojezd" než popředí a konec paralaxu tak působí zvláštně.

**Comment by rudky4** [comment]
Odpovede od kolegu z vývoja:
1. Některé obrázky se ořezávají kvůli zvolené animaci. 
2. Pozadí (nejspodnější obrázek) se již nedeformuje. 
3. Podle návrhu má být animace u spodnějších obrázků pomalejší než u přednějších.

**Comment by motyc** [comment]
1. Nevím, jak nastavená animace souvisí s ořezem obrazu. Vše by se mělo zmenšovat/zvětšovat relativně vůči pozadí, které vytváří absolutní pozici, jinak to nikdy nemůže fungovat správně. Např. zde je vidět, co to způsobuje (na foto úplně chybí cedule, která je pro obsah důležitá):
![image](https://user-images.githubusercontent.com/20186892/54596793-abf20d80-4a35-11e9-9ff5-c139a59847ed.png)

Při změně velikosti okna dojede k tomuto:
![image](https://user-images.githubusercontent.com/20186892/54596950-f5daf380-4a35-11e9-905a-9121be1c564a.png)

Popředí se dokonce dostává mimo původní obraz.

2. ok

3. Nevím, jaké je původní zadání, ale výsledek posuďte zde (není přitom cesty, jak to uživatelsky nastavit lépe): http://inqooltest.libj.cas.cz/screen/ac131145-410d-4519-a36b-1ffac4925b3c/2/0

Nemělo by se stávat, že jedna vrstva už stojí a druhá ještě jede. Opět jde přeci jen o relativní vztah rychlostí posuvu vůči sobě, kdy ale začátek a konec musí být všude shodný.

**Comment by rudky4** [comment]
@motyc opraveno
