### ISSUE TITLE
Aplikace čas od času samovolně zamrzne a některé části výstav jsou nefunkční

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#88]
Např. sem se nedá pro úpravu vůbec dostat: http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/image/0-1/image (kalendář 2019 -> 1.1)

V prezentačním režimu však obrazovka funguje dobře.

Zmíněné zamrzání nelze blíže specifikovat (stává se náhodně při práci).

**Comment by rudky4** [comment]
specifikovaný případ opraven

**Comment by rudky4** [comment]
otestovano v Chrome, OK
