### ISSUE TITLE
Záhlaví okna

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Exhibition#89]
V záhlaví okna je pouze "INDIHU", mělo by být "INDIHU Exhibition" (podobně jako je "INDIHU OCR")

**Comment by rudky4** [comment]
@motyc už je riešené v https://github.com/LIBCAS/INDIHU-Exhibition/issues/82

**Comment by motyc** [comment]
@rudky4 Bylo tím myšleno něco jiného:
![image](https://user-images.githubusercontent.com/20186892/54597497-f45dfb00-4a36-11e9-900c-d05540b4672c.png)

**Comment by rudky4** [comment]
@motyc pardon, zabezpečíme úpravu title tagu

**Comment by rudky4** [comment]
upraveno
