### ISSUE TITLE
Home page INDIHU Exhibition

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#91]
Prosím o úpravu HP. V budoucnu ještě dodám třeba video, které produkt představí, ale už teď bych to chtěla směřovat k něčemu, co je víc "landing page". Prosím, můžete prvky poskládat nějak takhle: 
![HP-inspirace1](https://user-images.githubusercontent.com/15922183/54678376-52591400-4b05-11e9-8d13-f30254f7eca2.png)
![HP-inspirace2](https://user-images.githubusercontent.com/15922183/54678377-52591400-4b05-11e9-95fd-16f633360f44.png)

Přihlašování je potřeba rozdělit na první registraci a přihlášení. Registrační formulář pro nově příchozí umístit do rámečku s výzvou "Začněte vytvářet výstavy". Pokud jsem již registrovaný uživatel, mělo by být ideálně vpravo nahoře tlačítko Přihlásit. 

Vysvětlující text prosím umístit vlevo. 
Nadpis:
Kreativní nástroj pro tvorbu virtuálních výstav (Větší velikostí, aby to působilo jako H1)

Vysvětlující text pod to, něco jako perex, větší písmo:
Vytvářejte působivé online prezentace na libovolná témata, která budou návštěvníkům dostupná na webu. INDIHU Exhibition umožňuje vtáhnout návštěvníka do děje a tvořit obsahově bohaté prezentace. Kombinujte obrázky, texty, fotogalerie, videa, mapy s dalšími možnostmi. Zařaďte do výstavy i drobné interaktivní hry. 

Jako podkresovou fotografii z nástroje můžete použít tuto: 
![foto-landing-page](https://user-images.githubusercontent.com/15922183/54680246-ab2aab80-4b09-11e9-9e51-929a448cb224.png)

**Comment by rudky4** [comment]
@nnis otázky:
- Uvedená podkresová fotografie obsahuje naspodu texty ("Vytvářejte virtuální výstavy", "Projít si výstavu" ...), ale pokud má fotografie pokrýt celou obrazovku, tak na některých monitorech může dojít k ořezu a nemusí tam tedy zcela být vidět, pokud to nevadí, tak ok. 
- Admin má navíc možnost zakázat registrace - to se teda ruší a registrace je povolena vždy? 
- Současná patička má zůstat nebo ne?

**Comment by nnis** [comment]
1. to asi nevadí, můžeme tam pak dodat nějakou lepší časem
2. no jo vlastně, to mi nedošlo, co myslíte vy? jak dlouho teď proces schvalování trvá? pokud je to v podstatě automaticky a rychlé jako "potvrďte odkaz poslaný mailem", tak to asi můžeme nechat. pokud je to delší proces, možná bych ho zrušila. Stejně jsme se bavili o tom, že je to vlastně taková formalita, ne? 
3. současnou patičku zatím nechme, ten odkaz na GitHub je dobrý

**Comment by rudky4** [comment]
@nnis 
1. ok
2. ide o formalitu, ale aktuálne by som to ponechal tak ako bolo navrhnuté, ak bude proces pri reálnej prevádzke nevhodný, upravíme to potom
3. ok

**Comment by nnis** [comment]
Bezva, tak prosím dodat k tomu registračnímu formuláře menším písmem větu "Registrace podléhají schválení. O schválení budete informování e-mailem "DOPLNIT časový rámec".

**Comment by nnis** [comment]
Ještě prosím o dopdání věty k registračnímu formuláři pod "Začněte vytvářet výstavy" a to menším písmem "Nástroj je zcela zdarma"

**Comment by rudky4** [comment]
@nnis done
