### ISSUE TITLE
Náhled kapitoly

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#92]
Při vytváření výstavy je nyní možnost spustit náhled obrazovky nebo náhled celé výstavy. Ješte by bylo vhodné přidat možnost náhledu kapitoly.

**Comment by Kolemkoukolem** [comment]
Dodatečně jsem si všiml, že sice podobné nikoli zcela identické bylo již řešeno: #68 Šlo by tedy pro náhled kapitoly nahrát pouze danou kapitolu?

**Comment by rudky4** [comment]
Náhled pouze jedné kapitoly (kromě náhledu výstavy a náhledu obrazovky) by byla celkem dost rozsáhlá úprava, tak jestli by nebylo vhodnější například přidat tlačítko do náhledu obrazovky pro přepnutí na náhled výstavy (pro danou obrazovku), který by zjednodušil volbu uživateli, ale stejně by bylo potřeba načíst celou výstavu
