### ISSUE TITLE
Zvuková stopa kapitoly

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#93]
Zvuková stopa kapitoly se automaticky vypne pod obrazovkou s videem. To není vhodné v případě využití podkreslovací zvukové stopy. Přidal bych obrazovce s videem ve vytváření možnost zaškrtnout, zda zvukovou stopy povolit či zakázat

**Comment by rudky4** [comment]
opraveno

**Comment by motyc** [comment]
@rudky4 v pořádku, lze zavřít
