### ISSUE TITLE
Zvuková stopy v náhledu obrazovky x náhledu výstavy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#94]
Zvuková stopa v náhledu obrazovky se chová jinak než náhledu celé výstavy. Viz výstava: http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/structure

V kapitole 5.1:
- v náhledu obrazovky se přehrává zároveň zvuková stopa obrazovky i zvuková stopa kapitoly (i když je zaškrtnuto její vypnutí = špatně
- v náhledu výstavy zvukové stopy běží jak mají = správně
zároveň:
- v náhledu obrazovky je zvuková stopa obrazovky přehrána celá (podle nastavení, že délka zobrazení má být po dobu zvukové stopy) = správně
- v náhledu výstavy zvuková stopa obrazovky ukončena před jejím koncem = špatně.

Nyní jsem to ještě zkoušel na jiném počítači a problém souhry obou zvukových stop byl při náhledu výstavy i obrazovky.

Původně testováno v prostředí Win 7 Professional; Mozilla Firefox v. 65.0.2 (64 bitů) - celkem na třech počítačích v jeden den (patrně stejných vlastností) se stejným výsledkem.
Nyní zkoušeno ještě v prostředí Win 10 Home; Mozilla Firefox v. 65.0.2 (64 bitů).

**Comment by rudky4** [comment]
vypínání/zapínání hudby opraveno. Kvůli zabránění předčasnému ukončení hudby přidána 2s rezerva při vkládání zvukové stopy obrazovky - pokud se jedná o ořez audia větší než +-1s, tak prosíme o dodání odkazu na obrazovku s audiem, kde se to děje, v obrazovce na uvedeném odkazu totiž audio nebylo

**Comment by Kolemkoukolem** [comment]
Bohužel dosud jsem nemohl otestovat chování v náhledu výstavy, jelikož náhled již delší dobu u této výstavy nefunguje. V mezidobí přidána kolegyní obrazovka 9.3 "Fotogalerie 7" - http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/photogalery/8-3/description
a obrazovka 8 "obrazovka s textem 5" - http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/text/7-0/description
U obou obrazovek v současnosti se v náhledu obrazovky nespouští zvuková stopa.

**Comment by rudky4** [comment]
@Kolemkoukolem malo by byt opravene 
+ "ta hudba jde, ale záleží, co tam nahrají, teď jim při spuštění s nepodporovaným formátem audia vyskočí chybová hláška"

**Comment by Kolemkoukolem** [comment]
V případě obrazovky 6.1 "Mongolsko" - http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/image/5-1/description v náhledu obrazovky zvuková stopa nyní vůbec neběží, v případě spuštění náhledu výstavy zvuková stopa běží, ale ne v celém rozsahu, ačkoli je zaškrtnuta možnost trvání "automaticky dle mluveného slova". Audio soubor má celkovou délku 0:51 s, v náhledu výstavy je ukončen v čase 0:18.
V případě obrazovky 8.3 "Fotogalerie 7" - http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/photogalery/7-3/description
a obrazovky 7 "Obrazovka s textem 5" - http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/screen/text/6-0/description
se zvuková stopa při náhledu obrazovky nepřehrává, při náhledu výstavy přehrává.
Ani v jednom případě chybová hláška nenaskakuje, resp. při spuštění výstavy naskočí chybová hláška upozorňující na jinou skladbu: 
![obrazek](https://user-images.githubusercontent.com/42067492/55884288-1b2bcf00-5ba8-11e9-8960-d439a671bece.png)

**Comment by Kolemkoukolem** [comment]
@rudky4 U zvukové stopy problém stále přetrvává - viz komentář výše.

**Comment by rudky4** [comment]
@Kolemkoukolem 
- pokud v editoru nelze zjistit délka audia, tak je uživatelovi vypsána hláška, ať zadá délku obrazovky ručně
- po načtení obrazovky/výstavy (kromě obrazovek úvod a závěr výstavy) se zobrazí tlačítko 'Spustit výstavu' a až po kliknutí na něj se spustí obrazovka/výstava, což předchází tomu, aby prohlížeč zablokoval spuštění audia, pokud uživatel neinteragoval se stránkou
- a byla opravena chybová hláška při načítání výstavy, teď by to mělo ukázat všechny chybně načtené soubory

**Comment by Kolemkoukolem** [comment]
Otestováno. Zdá se, že vše funguje. Děkuji za vyřešení.
