### ISSUE TITLE
Stránka s externím objektem - Infogram

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#95]
Nevím přesně, jak je koncipovaná stránka s externím objektem, ale narazila jsem na službu, která nefunguje - infogram na tvorbu infografik. Zkoušela jsem jak embed, tak responzivní embed. Pokud nechceme podporovat jen některé služby, měly by fungovat ideálně všechny. 

![infogram-issues](https://user-images.githubusercontent.com/15922183/55029165-ab471180-5009-11e9-9b7e-9f8738f40e62.png)

embed: 
<div class="infogram-embed" data-id="890e4e5f-ecf8-450e-9575-371838a8a144" data-type="interactive" data-title="Klementinum"></div><script>!function(e,t,s,i){var n="InfogramEmbeds",o=e.getElementsByTagName("script")[0],d=/^http:/.test(e.location)?"http:":"https:";if(/^\/{2}/.test(i)&&(i=d+i),window[n]&&window[n].initialized)window[n].process&&window[n].process();else if(!e.getElementById(s)){var r=e.createElement("script");r.async=1,r.id=s,r.src=i,o.parentNode.insertBefore(r,o)}}(document,0,"infogram-async","https://e.infogram.com/js/dist/embed-loader-min.js");</script><div style="padding:8px 0;font-family:Arial!important;font-size:13px!important;line-height:15px!important;text-align:center;border-top:1px solid #dadada;margin:0 30px"><a href="https://infogram.com/890e4e5f-ecf8-450e-9575-371838a8a144" style="color:#989898!important;text-decoration:none!important;" target="_blank">Klementinum</a><br><a href="https://infogram.com" style="color:#989898!important;text-decoration:none!important;" target="_blank" rel="nofollow">Infogram</a></div>

responsivni embed: 
<script id="infogram_0_890e4e5f-ecf8-450e-9575-371838a8a144" title="Klementinum" src="https://e.infogram.com/js/dist/embed.js?SYU" type="text/javascript"></script><div style="padding:8px 0;font-family:Arial!important;font-size:13px!important;line-height:15px!important;text-align:center;border-top:1px solid #dadada;margin:0 30px"><a href="https://infogram.com/890e4e5f-ecf8-450e-9575-371838a8a144" style="color:#989898!important;text-decoration:none!important;" target="_blank">Klementinum</a><br><a href="https://infogram.com" style="color:#989898!important;text-decoration:none!important;" target="_blank" rel="nofollow">Infogram</a></div>

u fixed embed to tedy šlo, ten ale není doporučený formát sdílení kvůli nárokům na responzovnost

**Comment by rudky4** [comment]
@nnis 

responzvní verze nejspíše fungovat nebude, protože obsahuje skript, který by bylo nutné vložit na jiné místo než se vkládá kód, který zadá uživatel. Fungovat budou pouze embed kódy, které obsahují např. iframe (tak jako ho obsahuje fixed embed)

**Comment by nnis** [comment]
OK, díky za vysvětlení, dám to jako informaci do manuálu.
