### ISSUE TITLE
Úvod do kapitoly - obrázek

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#96]
Obrázek na pozadí úvodu obrazovky se nechová správně. Když dám animaci, obrázek se stáhne vpravo a zobrazí jen na půlku, viz: 

![uvod-animace1](https://user-images.githubusercontent.com/15922183/55031461-f9124880-500e-11e9-9487-5f037be4d5d1.png)

a bez animace to vypadá takhle:

![uvod-bez-animace](https://user-images.githubusercontent.com/15922183/55031489-07606480-500f-11e9-9cff-fd3e6a29e92a.png)

Chci se zeptat, proč ty obrázky nejsou přes celou obrazovku, to ořezavání je nepříjemné a nevypadá to dobře a hlavně je nepředvídatelné, kdy obrázek bude fullscreen a kdy ne. Jak to mohu jako uživatel ovlivnit? I když jsem škílovala obrázek na doporučený rozměr 1920x1080, tak je to opět oříznutí.

**Comment by rudky4** [comment]
opraveno

**Comment by nnis** [comment]
Funguje, super
