### ISSUE TITLE
Výběr z tří možností

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Exhibition#97]
Dělám výstavu a vytvořila jsem kvíz a je potřeba zapracovat na tom, jak ten kvíz vypadá, protože to není pěkné a vizuálně to nefunguje. V podstatě musím vyplnit vše, aby stránka byla přiměřeně zaplněná - tedy obrázek ke kvízu, tak i obrázky ke třem možnostem. Když něco z toho nevyplním, obsah se v náhledu nepřizpůsobí (např. pokud bych nedala úvodní obrázek, ty obrázky k odpovědím by byly v horní polovině stránky a zvětšily by se). 

Jenže pak jsou obrázky ke třem možnostem jsou strašně malé, čímž v podstatě ztrácejí informační hodnotu a kvíz nemůže být pojat vizuálně, al stojí na textu. 

Nebylo by nakonec lepší, aby se zrušil hlavní obrázek ke kvízu a nechal tam jen obrázky k odpovědím. 

Dále text není zarovnán u jednotlivých odpovědí hezky. tedy nejspíše na střed zarovnané podle obrázků? 

Dále chybí označení odpovědi A, B, C. Můžete to prosím dodat? Nakonec mi přijde, že vlastně editace vypadá lépe než výsledek. 

![kviz](https://user-images.githubusercontent.com/15922183/55150863-54e2eb80-514d-11e9-8076-e772a413ecf3.png)
![kviz2](https://user-images.githubusercontent.com/15922183/55150864-54e2eb80-514d-11e9-858e-79c3cd453a5b.png)

Ještě mě napadlo udělat takový "ohák", ale stejně to není ideální. Mohla bych si teoreticky pohrát s tím obrázkem, tak aby možnsti byly zobrazeny pod jednotlivým obrázkem z trojobrázku, ale v případě, že změním velikost monitoru, by to nefungovalo a u těch odpovědí je stejně strašně moc volného místa. 

![kviz3](https://user-images.githubusercontent.com/15922183/55151837-64fbca80-514f-11e9-947e-7195c5f6d9f6.png)

**Comment by rudky4** [comment]
@nnis hotovo

**Comment by nnis** [comment]
O hodně lepší, díky.
