### ISSUE TITLE
Náhled výstavy

### ISSUE THREAD

**Issue by Kolemkoukolem** [LIBCAS/INDIHU-Exhibition#99]
Opět nám nefunguje (na několika počítačích i v různých prohlížečích) náhled výstavy. Snad podobný problém již řešen #45 a #5 . Jedná se o výstavu: http://inqooltest.libj.cas.cz/expo/ac131145-410d-4519-a36b-1ffac4925b3c/structure

**Comment by Kolemkoukolem** [comment]
Naléhavě žádám o reakci na tento problém, jelikož stále přetrvává a nelze tudíž otestovat předchozí problémy a pokračovat v tvorbě výstavy, která má již sloužit k prezentaci veřejnosti.

**Comment by rudky4** [comment]
Kolega dnes od rána pracuje na oprave. Budem informovať hneď ako nasadime opravu.

**Comment by rudky4** [comment]
@Kolemkoukolem bude povoleno načtení výstavy i pokud dojde k chybě při načítání audia/obrázku a zobrazí se když tak chybová hláška

**Comment by Kolemkoukolem** [comment]
Náhled se stále nechová optimálně. U výše zmíněné výstavy se nově objevil problém náhodně určovaného (špatného) ořezu obrázků na pozadí, pakliže je výstava spuštěna ze stránky s přehledem výstav a někdy (náhodně) i pokud je náhled spuštěn z úvodní kapitoly při úpravě výstavy.
viz: 
![obrazek](https://user-images.githubusercontent.com/42067492/55882018-0fd6a480-5ba4-11e9-98a9-80352d4bc95b.png)
Zde je patrné, že chybí horní polovina obrázku.

Zároveň při manuálním procházení této výstavy v náhledu pomocí šipek náhled vždy vypadne na stránce paralaxu a objeví se bílá obrazovka:
![obrazek](https://user-images.githubusercontent.com/42067492/55882328-a1461680-5ba4-11e9-86b3-6bcb7ac4ab1f.png)
![obrazek](https://user-images.githubusercontent.com/42067492/55882383-bd49b800-5ba4-11e9-903c-bb70d6c9d2c8.png)
Při "refreshi" se výstava znovu načte a zpustí z aktuální stránky

**Comment by Kolemkoukolem** [comment]
@rudky4 už se rýsuje nějaké řešení tohoto problému?

**Comment by rudky4** [comment]
@Kolemkoukolem na zajtrajšok som pourgoval kapacity, dúfam, ze sa to vyrieši a nasadí.

**Comment by Kolemkoukolem** [comment]
@rudky4 Děkuji!

**Comment by Kolemkoukolem** [comment]
Zdá se, že vše funguje. Děkuji!
